files:
  - source: /client/src/i18n/locales/en/*.json
    translation: /client/src/i18n/locales/%two_letters_code%/*.json
  - source: /server/i18n/en.json
    translation: /server/i18n/%two_letters_code%.json
