import { BruteBody } from '@labrute/prisma';

const availableBodyParts: { male: Omit<BruteBody, 'id' | 'bruteId'>, female: Omit<BruteBody, 'id' | 'bruteId'> } = {
  male: {
    longHair: 0,
    lowerRightArm: 1,
    rightHand: 1,
    upperRightArm: 1,
    rightShoulder: 1,
    rightFoot: 1,
    lowerRightLeg: 1,
    upperRightLeg: 1,
    leftFoot: 1,
    lowerLeftLeg: 1,
    pelvis: 1,
    upperLeftLeg: 1,
    tummy: 1,
    torso: 1,
    head: 1,
    leftHand: 1,
    upperLeftArm: 1,
    lowerLeftArm: 1,
    leftShoulder: 1,
  },
  female: {
    longHair: 3,
    lowerRightArm: 1,
    rightHand: 1,
    upperRightArm: 1,
    rightShoulder: 1,
    rightFoot: 1,
    lowerRightLeg: 1,
    upperRightLeg: 1,
    leftFoot: 1,
    lowerLeftLeg: 1,
    pelvis: 1,
    upperLeftLeg: 1,
    tummy: 1,
    torso: 1,
    head: 1,
    leftHand: 1,
    upperLeftArm: 1,
    lowerLeftArm: 1,
    leftShoulder: 1,
  },
};

export default availableBodyParts;
