import { BruteBody } from '@labrute/prisma';

const availableBodyParts: { male: Omit<BruteBody, 'id' | 'bruteId'>, female: Omit<BruteBody, 'id' | 'bruteId'> } = {
  male: {
    longHair: 0,
    lowerRightArm: 1,
    rightHand: 1,
    upperRightArm: 1,
    rightShoulder: 1,
    rightFoot: 1,
    lowerRightLeg: 1,
    upperRightLeg: 1,
    leftFoot: 1,
    lowerLeftLeg: 1,
    pelvis: 1,
    upperLeftLeg: 1,
    tummy: 1,
    torso: 1,
    head: 1,
    leftHand: 1,
    upperLeftArm: 1,
    lowerLeftArm: 1,
    leftShoulder: 1,
    p2: 7,
    p3: 11,
    p4: 4,
    p7: 6,
    p1: 1,
    p1a: 1,
    p1b: 1,
    p6: 1,
    p8: 4,
    p7b: 2,
    p5: 1,
  },
  female: {
    longHair: 3,
    lowerRightArm: 1,
    rightHand: 1,
    upperRightArm: 1,
    rightShoulder: 1,
    rightFoot: 1,
    lowerRightLeg: 1,
    upperRightLeg: 1,
    leftFoot: 1,
    lowerLeftLeg: 1,
    pelvis: 1,
    upperLeftLeg: 1,
    tummy: 1,
    torso: 1,
    head: 1,
    leftHand: 1,
    upperLeftArm: 1,
    lowerLeftArm: 1,
    leftShoulder: 1,
    p2: 0,
    p3: 11,
    p4: 3,
    p7: 6,
    p1: 1,
    p1a: 1,
    p1b: 1,
    p6: 0,
    p8: 4,
    p7b: 2,
    p5: 1,
  },
} as const;

export default availableBodyParts;
