import {
  Animation, FrameProps,
} from '@eternaltwin/labrute-core/types';
import maleBruteIddle1 from './male-brute/iddle/1.js';

const FRAME: Record<
  'male' | 'female',
  Record<
    Animation,
    // eslint-disable-next-line no-unused-vars
    (((props: FrameProps) => string) | null)[]
  >
> = {
  male: {
    'arrive-end': [],
    'arrive-start': [],
    attack: [],
    block: [],
    death: [],
    drink: [],
    eat: [],
    equip: [],
    evade: [],
    grab: [],
    grabbed: [],
    hit: [],
    'hit-0': [],
    'hit-1': [],
    'hit-2': [],
    'hit-3': [],
    iddle: [maleBruteIddle1],
    launch: [],
    'monk-loop': [],
    'monk-start': [],
    'prepare-throw': [],
    run: [],
    slash: [],
    stolen: [],
    steal: [],
    strengthen: [],
    throw: [],
    train: [],
    'trapped-loop': [],
    'trapped-start': [],
    trash: [],
    win: [],
    fist: [],
    estoc: [],
    whip: [],
  },
  female: {
    'arrive-end': [],
    'arrive-start': [],
    attack: [],
    block: [],
    death: [],
    drink: [],
    eat: [],
    equip: [],
    evade: [],
    grab: [],
    grabbed: [],
    hit: [],
    'hit-0': [],
    'hit-1': [],
    'hit-2': [],
    'hit-3': [],
    iddle: [],
    launch: [],
    'monk-loop': [],
    'monk-start': [],
    'prepare-throw': [],
    run: [],
    slash: [],
    stolen: [],
    steal: [],
    strengthen: [],
    throw: [],
    train: [],
    'trapped-loop': [],
    'trapped-start': [],
    trash: [],
    win: [],
    fist: [],
    estoc: [],
    whip: [],
  },
};

const getFrame = (
  animation: Animation,
  model: 'male' | 'female',
  frame: string,
) => FRAME[model][animation][(+frame) - 1];

export default getFrame;