  ALTER TABLE "Fight" ALTER COLUMN "brute1Id" SET NOT NULL;
  ALTER TABLE "ClanPost" ALTER COLUMN "author" SET NOT NULL;
  ALTER TABLE "ClanThread" ALTER COLUMN "creator" SET NOT NULL;
  ALTER TABLE "BossDAmage" ALTER COLUMN "brute" SET NOT NULL;
