import { Animation, StepFighter } from '@eternaltwin/labrute-core/types';

export const DURATIONS: Record<
  'dog' | 'bear' | 'panther' | 'brute',
  Record<Animation, number>
> = {
  bear: {
    'arrive-start': 500,
    'arrive-end': 500,
    attack: 470,
    death: 1220,
    evade: 1000,
    hit: 500,
    'hit-0': 500,
    'hit-1': 500,
    'hit-2': 500,
    iddle: 0,
    run: 500,
    fist: 0,
    slash: 0,
    estoc: 0,
    equip: 0,
    block: 0,
    throw: 0,
    strengthen: 0,
    whip: 0,
    win: 0,
    drink: 0,
    eat: 0,
    grab: 0,
    grabbed: 0,
    launch: 0,
    'monk-start': 0,
    'monk-loop': 0,
    'prepare-throw': 0,
    stolen: 0,
    steal: 0,
    train: 0,
    'trapped-start': 0,
    'trapped-loop': 0,
    trash: 0,
  },
  panther: {
    'arrive-start': 500,
    'arrive-end': 500,
    attack: 170,
    death: 670,
    evade: 1000,
    hit: 500,
    'hit-0': 500,
    'hit-1': 500,
    'hit-2': 500,
    iddle: 0,
    run: 500,
    fist: 0,
    slash: 0,
    estoc: 0,
    equip: 0,
    block: 0,
    throw: 0,
    strengthen: 0,
    whip: 0,
    win: 0,
    drink: 0,
    eat: 0,
    grab: 0,
    grabbed: 0,
    launch: 0,
    'monk-start': 0,
    'monk-loop': 0,
    'prepare-throw': 0,
    stolen: 0,
    steal: 0,
    train: 0,
    'trapped-start': 0,
    'trapped-loop': 0,
    trash: 0,
  },
  dog: {
    'arrive-start': 500,
    'arrive-end': 500,
    attack: 170,
    death: 670,
    evade: 1000,
    hit: 500,
    'hit-0': 500,
    'hit-1': 500,
    'hit-2': 500,
    iddle: 0,
    run: 500,
    fist: 0,
    slash: 0,
    estoc: 0,
    equip: 0,
    block: 0,
    throw: 0,
    strengthen: 0,
    whip: 0,
    win: 0,
    drink: 0,
    eat: 0,
    grab: 0,
    grabbed: 0,
    launch: 0,
    'monk-start': 0,
    'monk-loop': 0,
    'prepare-throw': 0,
    stolen: 0,
    steal: 0,
    train: 0,
    'trapped-start': 0,
    'trapped-loop': 0,
    trash: 0,
  },
  brute: {
    'arrive-start': 500,
    'arrive-end': 500,
    death: 0,
    attack: 0,
    evade: 1000,
    hit: 500,
    'hit-0': 500,
    'hit-1': 500,
    'hit-2': 500,
    iddle: 0,
    run: 500,
    fist: 400,
    slash: 300,
    estoc: 250,
    equip: 370,
    block: 570,
    throw: 350,
    strengthen: 620,
    whip: 350,
    win: 1370,
    drink: 0,
    eat: 0,
    grab: 0,
    grabbed: 0,
    launch: 0,
    'monk-start': 0,
    'monk-loop': 0,
    'prepare-throw': 0,
    stolen: 0,
    steal: 0,
    train: 0,
    'trapped-start': 0,
    'trapped-loop': 0,
    trash: 0,
  },
};

const getMoveDuration = (
  animation: Animation,
  fighter: StepFighter,
) => {
  const type = fighter.type === 'pet'
    ? fighter.name.startsWith('dog')
      ? 'dog' : fighter.name as 'bear' | 'panther'
    : 'brute';

  return DURATIONS[type][animation];
};

export default getMoveDuration;