import { AchievementName } from '@labrute/prisma';
import { AchievementData, AchievementRarety } from './Achievements';

export const BaseTitleRequirements = {
  [AchievementRarety.common]: [250, 500, 1000, 2500, 5000],
  [AchievementRarety.uncommon]: [50, 100, 250, 500, 1000],
  [AchievementRarety.rare]: [10, 25, 50, 100, 250],
  [AchievementRarety.epic]: [5, 10, 25, 50, 100],
  [AchievementRarety.legendary]: [1, 5, 10, 25, 50],
};

export const TitleRequirements: Record<AchievementName, number[]> = {
  wins: BaseTitleRequirements[AchievementData.wins.rarety],
  defeats: BaseTitleRequirements[AchievementData.defeats.rarety],
  flawless: BaseTitleRequirements[AchievementData.flawless.rarety],
  winWith1HP: BaseTitleRequirements[AchievementData.winWith1HP.rarety],
  steal2Weapons: BaseTitleRequirements[AchievementData.steal2Weapons.rarety],
  singleHitWin: BaseTitleRequirements[AchievementData.singleHitWin.rarety],
  combo3: BaseTitleRequirements[AchievementData.combo3.rarety],
  combo4: BaseTitleRequirements[AchievementData.combo4.rarety],
  combo5: BaseTitleRequirements[AchievementData.combo5.rarety],
  counter5: BaseTitleRequirements[AchievementData.counter5.rarety],
  evade10: BaseTitleRequirements[AchievementData.evade10.rarety],
  block25: BaseTitleRequirements[AchievementData.block25.rarety],
  counter4b2b: BaseTitleRequirements[AchievementData.counter4b2b.rarety],
  reversal4b2b: BaseTitleRequirements[AchievementData.reversal4b2b.rarety],
  block4b2b: BaseTitleRequirements[AchievementData.block4b2b.rarety],
  evade4b2b: BaseTitleRequirements[AchievementData.evade4b2b.rarety],
  throw10b2b: BaseTitleRequirements[AchievementData.throw10b2b.rarety],
  disarm4: BaseTitleRequirements[AchievementData.disarm4.rarety],
  disarm8: BaseTitleRequirements[AchievementData.disarm8.rarety],
  damage50once: BaseTitleRequirements[AchievementData.damage50once.rarety],
  damage100once: BaseTitleRequirements[AchievementData.damage100once.rarety],
  hit20times: BaseTitleRequirements[AchievementData.hit20times.rarety],
  kill3pets: BaseTitleRequirements[AchievementData.kill3pets.rarety],
  use10skills: BaseTitleRequirements[AchievementData.use10skills.rarety],
  saboteur: BaseTitleRequirements[AchievementData.saboteur.rarety],
  dog: BaseTitleRequirements[AchievementData.dog.rarety],
  panther: BaseTitleRequirements[AchievementData.panther.rarety],
  bear: BaseTitleRequirements[AchievementData.bear.rarety],
  panther_bear: BaseTitleRequirements[AchievementData.panther_bear.rarety],
  felAg_fistsOfF: BaseTitleRequirements[AchievementData.felAg_fistsOfF.rarety],
  felAg_fistsOfF_untouch_relentless: BaseTitleRequirements[
    AchievementData.felAg_fistsOfF_untouch_relentless.rarety
  ],
  vita_armor_toughened: BaseTitleRequirements[AchievementData.vita_armor_toughened.rarety],
  herculStr_hammer_fierceBrute: BaseTitleRequirements[
    AchievementData.herculStr_hammer_fierceBrute.rarety
  ],
  shock: BaseTitleRequirements[AchievementData.shock.rarety],
  balletShoes_survival: BaseTitleRequirements[AchievementData.balletShoes_survival.rarety],
  cryOfTheDamned_hypnosis: BaseTitleRequirements[AchievementData.cryOfTheDamned_hypnosis.rarety],
  shield_counterAttack: BaseTitleRequirements[AchievementData.shield_counterAttack.rarety],
  reconnaissance_monk: BaseTitleRequirements[AchievementData.reconnaissance_monk.rarety],
  immortality: BaseTitleRequirements[AchievementData.immortality.rarety],
  doubleBoost: BaseTitleRequirements[AchievementData.doubleBoost.rarety],
  tripleBoost: BaseTitleRequirements[AchievementData.tripleBoost.rarety],
  quadrupleBoost: BaseTitleRequirements[AchievementData.quadrupleBoost.rarety],
  regeneration_potion: BaseTitleRequirements[AchievementData.regeneration_potion.rarety],
  bear_tamer: BaseTitleRequirements[AchievementData.bear_tamer.rarety],
  tripleDogs: BaseTitleRequirements[AchievementData.tripleDogs.rarety],
  fiveWeapons: BaseTitleRequirements[AchievementData.fiveWeapons.rarety],
  tenWeapons: BaseTitleRequirements[AchievementData.tenWeapons.rarety],
  fifteenWeapons: BaseTitleRequirements[AchievementData.fifteenWeapons.rarety],
  twentyWeapons: BaseTitleRequirements[AchievementData.twentyWeapons.rarety],
  twentyThreeWeapons: BaseTitleRequirements[AchievementData.twentyThreeWeapons.rarety],
  monk_sixthSense_whip: BaseTitleRequirements[AchievementData.monk_sixthSense_whip.rarety],
  weaponsMaster_sharp_bodybuilder_heavy: BaseTitleRequirements[
    AchievementData.weaponsMaster_sharp_bodybuilder_heavy.rarety
  ],
  hostility_counterWeapon: BaseTitleRequirements[AchievementData.hostility_counterWeapon.rarety],
  flashFlood_twelveWeapons: BaseTitleRequirements[AchievementData.flashFlood_twelveWeapons.rarety],
  lightningBolt_firstStrike: BaseTitleRequirements[
    AchievementData.lightningBolt_firstStrike.rarety
  ],
  herculeanStrength: BaseTitleRequirements[AchievementData.herculeanStrength.rarety],
  felineAgility: BaseTitleRequirements[AchievementData.felineAgility.rarety],
  lightningBolt: BaseTitleRequirements[AchievementData.lightningBolt.rarety],
  vitality: BaseTitleRequirements[AchievementData.vitality.rarety],
  potion_chef: BaseTitleRequirements[AchievementData.potion_chef.rarety],
  tamer_net: BaseTitleRequirements[AchievementData.tamer_net.rarety],
  untouchable_balletShoes: BaseTitleRequirements[AchievementData.untouchable_balletShoes.rarety],
  survival_resistant: BaseTitleRequirements[AchievementData.survival_resistant.rarety],
  hideaway_spy: BaseTitleRequirements[AchievementData.hideaway_spy.rarety],
  weaponsFast3: BaseTitleRequirements[AchievementData.weaponsFast3.rarety],
  weaponsSharp3: BaseTitleRequirements[AchievementData.weaponsSharp3.rarety],
  weaponsHeavy3: BaseTitleRequirements[AchievementData.weaponsHeavy3.rarety],
  weaponsLong3: BaseTitleRequirements[AchievementData.weaponsLong3.rarety],
  weaponsThrown3: BaseTitleRequirements[AchievementData.weaponsThrown3.rarety],
  weaponsBlunt3: BaseTitleRequirements[AchievementData.weaponsBlunt3.rarety],
  agility50: BaseTitleRequirements[AchievementData.agility50.rarety],
  agility100: BaseTitleRequirements[AchievementData.agility100.rarety],
  speed50: BaseTitleRequirements[AchievementData.speed50.rarety],
  speed100: BaseTitleRequirements[AchievementData.speed100.rarety],
  strength50: BaseTitleRequirements[AchievementData.strength50.rarety],
  strength100: BaseTitleRequirements[AchievementData.strength100.rarety],
  hp300: BaseTitleRequirements[AchievementData.hp300.rarety],
  hp600: BaseTitleRequirements[AchievementData.hp600.rarety],
  winTournamentAs20: BaseTitleRequirements[AchievementData.winTournamentAs20.rarety],
  winTournamentAs15: BaseTitleRequirements[AchievementData.winTournamentAs15.rarety],
  looseAgainst2: BaseTitleRequirements[AchievementData.looseAgainst2.rarety],
  looseAgainst3: BaseTitleRequirements[AchievementData.looseAgainst3.rarety],
  looseAgainst4: BaseTitleRequirements[AchievementData.looseAgainst4.rarety],
  winAgainst2: BaseTitleRequirements[AchievementData.winAgainst2.rarety],
  winAgainst3: BaseTitleRequirements[AchievementData.winAgainst3.rarety],
  winAgainst4: BaseTitleRequirements[AchievementData.winAgainst4.rarety],
  winAsLower: BaseTitleRequirements[AchievementData.winAsLower.rarety],
  win: BaseTitleRequirements[AchievementData.win.rarety],
  rankUp10: BaseTitleRequirements[AchievementData.rankUp10.rarety],
  rankUp9: BaseTitleRequirements[AchievementData.rankUp9.rarety],
  rankUp8: BaseTitleRequirements[AchievementData.rankUp8.rarety],
  rankUp7: BaseTitleRequirements[AchievementData.rankUp7.rarety],
  rankUp6: BaseTitleRequirements[AchievementData.rankUp6.rarety],
  rankUp5: BaseTitleRequirements[AchievementData.rankUp5.rarety],
  rankUp4: BaseTitleRequirements[AchievementData.rankUp4.rarety],
  rankUp3: BaseTitleRequirements[AchievementData.rankUp3.rarety],
  rankUp2: BaseTitleRequirements[AchievementData.rankUp2.rarety],
  rankUp1: BaseTitleRequirements[AchievementData.rankUp1.rarety],
  rankUp0: BaseTitleRequirements[AchievementData.rankUp0.rarety],
  sacrifice: BaseTitleRequirements[AchievementData.sacrifice.rarety],
  beta: BaseTitleRequirements[AchievementData.beta.rarety],
  bug: BaseTitleRequirements[AchievementData.bug.rarety],
};