
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model UserLog
 * 
 */
export type UserLog = Prisma.UserLogModel
/**
 * Model Brute
 * 
 */
export type Brute = Prisma.BruteModel
/**
 * Model BruteStartingStats
 * 
 */
export type BruteStartingStats = Prisma.BruteStartingStatsModel
/**
 * Model Fight
 * 
 */
export type Fight = Prisma.FightModel
/**
 * Model Log
 * 
 */
export type Log = Prisma.LogModel
/**
 * Model DestinyChoice
 * 
 */
export type DestinyChoice = Prisma.DestinyChoiceModel
/**
 * Model Tournament
 * 
 */
export type Tournament = Prisma.TournamentModel
/**
 * Model TournamentAchievement
 * 
 */
export type TournamentAchievement = Prisma.TournamentAchievementModel
/**
 * Model TournamentGold
 * 
 */
export type TournamentGold = Prisma.TournamentGoldModel
/**
 * Model TournamentXp
 * 
 */
export type TournamentXp = Prisma.TournamentXpModel
/**
 * Model Achievement
 * 
 */
export type Achievement = Prisma.AchievementModel
/**
 * Model BruteReport
 * 
 */
export type BruteReport = Prisma.BruteReportModel
/**
 * Model ServerState
 * 
 */
export type ServerState = Prisma.ServerStateModel
/**
 * Model BannedWord
 * 
 */
export type BannedWord = Prisma.BannedWordModel
/**
 * Model BannedIp
 * 
 */
export type BannedIp = Prisma.BannedIpModel
/**
 * Model BannedFingerprint
 * 
 */
export type BannedFingerprint = Prisma.BannedFingerprintModel
/**
 * Model KnownFingerprint
 * 
 */
export type KnownFingerprint = Prisma.KnownFingerprintModel
/**
 * Model Clan
 * 
 */
export type Clan = Prisma.ClanModel
/**
 * Model ClanThread
 * 
 */
export type ClanThread = Prisma.ClanThreadModel
/**
 * Model ClanPost
 * 
 */
export type ClanPost = Prisma.ClanPostModel
/**
 * Model BossDamage
 * 
 */
export type BossDamage = Prisma.BossDamageModel
/**
 * Model ClanWar
 * 
 */
export type ClanWar = Prisma.ClanWarModel
/**
 * Model ClanWarFighters
 * 
 */
export type ClanWarFighters = Prisma.ClanWarFightersModel
/**
 * Model InventoryItem
 * 
 */
export type InventoryItem = Prisma.InventoryItemModel
/**
 * Model Release
 * 
 */
export type Release = Prisma.ReleaseModel
/**
 * Model Event
 * 
 */
export type Event = Prisma.EventModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
/**
 * Model Config
 * 
 */
export type Config = Prisma.ConfigModel
