"use strict";
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/
Object.defineProperty(exports, "__esModule", { value: true });
exports.NotificationSeverity = exports.EventStatus = exports.EventType = exports.InventoryItemType = exports.ClanWarType = exports.ClanWarStatus = exports.BossName = exports.BruteReportReason = exports.BruteReportStatus = exports.AchievementName = exports.TournamentType = exports.BruteStat = exports.DestinyChoiceType = exports.LogType = exports.FightModifier = exports.FighterType = exports.PetName = exports.SkillName = exports.WeaponName = exports.Gender = exports.DestinyChoiceSide = exports.UserLogType = exports.Lang = void 0;
exports.Lang = {
    en: 'en',
    fr: 'fr',
    de: 'de',
    es: 'es',
    ru: 'ru',
    pt: 'pt'
};
exports.UserLogType = {
    CONNECT: 'CONNECT',
    DISCONNECT: 'DISCONNECT',
    GOLD_WIN: 'GOLD_WIN',
    GOLD_LOSS: 'GOLD_LOSS',
    CREATE_BRUTE: 'CREATE_BRUTE',
    RENAME_BRUTE: 'RENAME_BRUTE',
    SACRIFICE_BRUTE: 'SACRIFICE_BRUTE',
    TRANSFER_BRUTE: 'TRANSFER_BRUTE',
    BANNED: 'BANNED',
    DELETED: 'DELETED'
};
exports.DestinyChoiceSide = {
    LEFT: 'LEFT',
    RIGHT: 'RIGHT'
};
exports.Gender = {
    male: 'male',
    female: 'female'
};
exports.WeaponName = {
    fan: 'fan',
    keyboard: 'keyboard',
    knife: 'knife',
    leek: 'leek',
    mug: 'mug',
    sai: 'sai',
    racquet: 'racquet',
    axe: 'axe',
    bumps: 'bumps',
    flail: 'flail',
    fryingPan: 'fryingPan',
    hatchet: 'hatchet',
    mammothBone: 'mammothBone',
    morningStar: 'morningStar',
    trombone: 'trombone',
    baton: 'baton',
    halbard: 'halbard',
    lance: 'lance',
    trident: 'trident',
    whip: 'whip',
    noodleBowl: 'noodleBowl',
    piopio: 'piopio',
    shuriken: 'shuriken',
    broadsword: 'broadsword',
    scimitar: 'scimitar',
    sword: 'sword'
};
exports.SkillName = {
    herculeanStrength: 'herculeanStrength',
    felineAgility: 'felineAgility',
    lightningBolt: 'lightningBolt',
    vitality: 'vitality',
    immortality: 'immortality',
    reconnaissance: 'reconnaissance',
    weaponsMaster: 'weaponsMaster',
    martialArts: 'martialArts',
    sixthSense: 'sixthSense',
    hostility: 'hostility',
    fistsOfFury: 'fistsOfFury',
    shield: 'shield',
    armor: 'armor',
    toughenedSkin: 'toughenedSkin',
    untouchable: 'untouchable',
    sabotage: 'sabotage',
    shock: 'shock',
    bodybuilder: 'bodybuilder',
    relentless: 'relentless',
    survival: 'survival',
    leadSkeleton: 'leadSkeleton',
    balletShoes: 'balletShoes',
    determination: 'determination',
    firstStrike: 'firstStrike',
    resistant: 'resistant',
    counterAttack: 'counterAttack',
    ironHead: 'ironHead',
    thief: 'thief',
    fierceBrute: 'fierceBrute',
    tragicPotion: 'tragicPotion',
    net: 'net',
    bomb: 'bomb',
    hammer: 'hammer',
    cryOfTheDamned: 'cryOfTheDamned',
    hypnosis: 'hypnosis',
    flashFlood: 'flashFlood',
    tamer: 'tamer',
    regeneration: 'regeneration',
    chef: 'chef',
    spy: 'spy',
    saboteur: 'saboteur',
    backup: 'backup',
    hideaway: 'hideaway',
    monk: 'monk',
    vampirism: 'vampirism',
    chaining: 'chaining',
    haste: 'haste',
    treat: 'treat',
    repulse: 'repulse',
    fastMetabolism: 'fastMetabolism'
};
exports.PetName = {
    dog1: 'dog1',
    dog2: 'dog2',
    dog3: 'dog3',
    panther: 'panther',
    bear: 'bear'
};
exports.FighterType = {
    brute: 'brute',
    pet: 'pet'
};
exports.FightModifier = {
    noThrows: 'noThrows',
    focusOpponent: 'focusOpponent',
    alwaysUseSupers: 'alwaysUseSupers',
    drawEveryWeapon: 'drawEveryWeapon',
    doubleAgility: 'doubleAgility',
    randomSkill: 'randomSkill',
    randomWeapon: 'randomWeapon',
    bareHandsFirstHit: 'bareHandsFirstHit',
    startWithWeapon: 'startWithWeapon',
    chaos: 'chaos'
};
exports.LogType = {
    win: 'win',
    lose: 'lose',
    child: 'child',
    childup: 'childup',
    up: 'up',
    lvl: 'lvl',
    ascend: 'ascend',
    tournament: 'tournament',
    tournamentXp: 'tournamentXp',
    bossFight: 'bossFight',
    bossDefeat: 'bossDefeat'
};
exports.DestinyChoiceType = {
    skill: 'skill',
    weapon: 'weapon',
    pet: 'pet',
    stats: 'stats'
};
exports.BruteStat = {
    endurance: 'endurance',
    strength: 'strength',
    agility: 'agility',
    speed: 'speed'
};
exports.TournamentType = {
    DAILY: 'DAILY',
    GLOBAL: 'GLOBAL',
    UNLIMITED_GLOBAL: 'UNLIMITED_GLOBAL',
    CUSTOM: 'CUSTOM',
    BATTLE_ROYALE: 'BATTLE_ROYALE'
};
exports.AchievementName = {
    wins: 'wins',
    defeats: 'defeats',
    flawless: 'flawless',
    winWith1HP: 'winWith1HP',
    steal2Weapons: 'steal2Weapons',
    singleHitWin: 'singleHitWin',
    combo3: 'combo3',
    combo4: 'combo4',
    combo5: 'combo5',
    counter5: 'counter5',
    evade10: 'evade10',
    block25: 'block25',
    counter4b2b: 'counter4b2b',
    reversal4b2b: 'reversal4b2b',
    block4b2b: 'block4b2b',
    evade4b2b: 'evade4b2b',
    throw10b2b: 'throw10b2b',
    disarm4: 'disarm4',
    disarm8: 'disarm8',
    damage50once: 'damage50once',
    damage100once: 'damage100once',
    hit20times: 'hit20times',
    use10skills: 'use10skills',
    kill3pets: 'kill3pets',
    maxDamage: 'maxDamage',
    hpHealed: 'hpHealed',
    saboteur: 'saboteur',
    dog: 'dog',
    panther: 'panther',
    bear: 'bear',
    panther_bear: 'panther_bear',
    felAg_fistsOfF: 'felAg_fistsOfF',
    felAg_fistsOfF_untouch_relentless: 'felAg_fistsOfF_untouch_relentless',
    vita_armor_toughened: 'vita_armor_toughened',
    herculStr_hammer_fierceBrute: 'herculStr_hammer_fierceBrute',
    shock: 'shock',
    balletShoes_survival: 'balletShoes_survival',
    cryOfTheDamned_hypnosis: 'cryOfTheDamned_hypnosis',
    shield_counterAttack: 'shield_counterAttack',
    reconnaissance_monk: 'reconnaissance_monk',
    immortality: 'immortality',
    doubleBoost: 'doubleBoost',
    tripleBoost: 'tripleBoost',
    quadrupleBoost: 'quadrupleBoost',
    regeneration_potion: 'regeneration_potion',
    bear_tamer: 'bear_tamer',
    tripleDogs: 'tripleDogs',
    fiveWeapons: 'fiveWeapons',
    tenWeapons: 'tenWeapons',
    fifteenWeapons: 'fifteenWeapons',
    twentyWeapons: 'twentyWeapons',
    twentyThreeWeapons: 'twentyThreeWeapons',
    monk_sixthSense_whip: 'monk_sixthSense_whip',
    weaponsMaster_sharp_bodybuilder_heavy: 'weaponsMaster_sharp_bodybuilder_heavy',
    hostility_counterWeapon: 'hostility_counterWeapon',
    flashFlood_twelveWeapons: 'flashFlood_twelveWeapons',
    lightningBolt_firstStrike: 'lightningBolt_firstStrike',
    herculeanStrength: 'herculeanStrength',
    felineAgility: 'felineAgility',
    lightningBolt: 'lightningBolt',
    vitality: 'vitality',
    potion_chef: 'potion_chef',
    tamer_net: 'tamer_net',
    untouchable_balletShoes: 'untouchable_balletShoes',
    survival_resistant: 'survival_resistant',
    hideaway_spy: 'hideaway_spy',
    weaponsFast3: 'weaponsFast3',
    weaponsSharp3: 'weaponsSharp3',
    weaponsHeavy3: 'weaponsHeavy3',
    weaponsLong3: 'weaponsLong3',
    weaponsThrown3: 'weaponsThrown3',
    weaponsBlunt3: 'weaponsBlunt3',
    thor: 'thor',
    deflector: 'deflector',
    allFastWeapons: 'allFastWeapons',
    allSharpWeapons: 'allSharpWeapons',
    allHeavyWeapons: 'allHeavyWeapons',
    allLongWeapons: 'allLongWeapons',
    allThrownWeapons: 'allThrownWeapons',
    allBluntWeapons: 'allBluntWeapons',
    agility50: 'agility50',
    agility100: 'agility100',
    speed50: 'speed50',
    speed100: 'speed100',
    strength50: 'strength50',
    strength100: 'strength100',
    hp300: 'hp300',
    hp600: 'hp600',
    maxLevel: 'maxLevel',
    allAchievements: 'allAchievements',
    winTournamentAs20: 'winTournamentAs20',
    winTournamentAs15: 'winTournamentAs15',
    looseAgainst2: 'looseAgainst2',
    looseAgainst3: 'looseAgainst3',
    looseAgainst4: 'looseAgainst4',
    winAgainst2: 'winAgainst2',
    winAgainst3: 'winAgainst3',
    winAgainst4: 'winAgainst4',
    winAsLower: 'winAsLower',
    win: 'win',
    battleRoyaleWin: 'battleRoyaleWin',
    rankUp10: 'rankUp10',
    rankUp9: 'rankUp9',
    rankUp8: 'rankUp8',
    rankUp7: 'rankUp7',
    rankUp6: 'rankUp6',
    rankUp5: 'rankUp5',
    rankUp4: 'rankUp4',
    rankUp3: 'rankUp3',
    rankUp2: 'rankUp2',
    rankUp1: 'rankUp1',
    rankUp0: 'rankUp0',
    ascend: 'ascend',
    sacrifice: 'sacrifice',
    beta: 'beta',
    bug: 'bug'
};
exports.BruteReportStatus = {
    pending: 'pending',
    accepted: 'accepted',
    rejected: 'rejected'
};
exports.BruteReportReason = {
    name: 'name'
};
exports.BossName = {
    GoldClaw: 'GoldClaw',
    EmberFang: 'EmberFang',
    Cerberus: 'Cerberus'
};
exports.ClanWarStatus = {
    pending: 'pending',
    ongoing: 'ongoing',
    waitingForRewards: 'waitingForRewards',
    finished: 'finished'
};
exports.ClanWarType = {
    friendly: 'friendly',
    official: 'official'
};
exports.InventoryItemType = {
    visualReset: 'visualReset',
    bossTicket: 'bossTicket',
    nameChange: 'nameChange',
    favoriteFight: 'favoriteFight'
};
exports.EventType = {
    battleRoyale: 'battleRoyale'
};
exports.EventStatus = {
    starting: 'starting',
    ongoing: 'ongoing',
    finished: 'finished'
};
exports.NotificationSeverity = {
    info: 'info',
    success: 'success',
    warning: 'warning',
    error: 'error'
};
//# sourceMappingURL=enums.js.map