export declare const Lang: {
    readonly en: "en";
    readonly fr: "fr";
    readonly de: "de";
    readonly es: "es";
    readonly ru: "ru";
    readonly pt: "pt";
};
export type Lang = (typeof Lang)[keyof typeof Lang];
export declare const UserLogType: {
    readonly CONNECT: "CONNECT";
    readonly DISCONNECT: "DISCONNECT";
    readonly GOLD_WIN: "GOLD_WIN";
    readonly GOLD_LOSS: "GOLD_LOSS";
    readonly CREATE_BRUTE: "CREATE_BRUTE";
    readonly RENAME_BRUTE: "RENAME_BRUTE";
    readonly SACRIFICE_BRUTE: "SACRIFICE_BRUTE";
    readonly TRANSFER_BRUTE: "TRANSFER_BRUTE";
    readonly BANNED: "BANNED";
    readonly DELETED: "DELETED";
};
export type UserLogType = (typeof UserLogType)[keyof typeof UserLogType];
export declare const DestinyChoiceSide: {
    readonly LEFT: "LEFT";
    readonly RIGHT: "RIGHT";
};
export type DestinyChoiceSide = (typeof DestinyChoiceSide)[keyof typeof DestinyChoiceSide];
export declare const Gender: {
    readonly male: "male";
    readonly female: "female";
};
export type Gender = (typeof Gender)[keyof typeof Gender];
export declare const WeaponName: {
    readonly fan: "fan";
    readonly keyboard: "keyboard";
    readonly knife: "knife";
    readonly leek: "leek";
    readonly mug: "mug";
    readonly sai: "sai";
    readonly racquet: "racquet";
    readonly axe: "axe";
    readonly bumps: "bumps";
    readonly flail: "flail";
    readonly fryingPan: "fryingPan";
    readonly hatchet: "hatchet";
    readonly mammothBone: "mammothBone";
    readonly morningStar: "morningStar";
    readonly trombone: "trombone";
    readonly baton: "baton";
    readonly halbard: "halbard";
    readonly lance: "lance";
    readonly trident: "trident";
    readonly whip: "whip";
    readonly noodleBowl: "noodleBowl";
    readonly piopio: "piopio";
    readonly shuriken: "shuriken";
    readonly broadsword: "broadsword";
    readonly scimitar: "scimitar";
    readonly sword: "sword";
};
export type WeaponName = (typeof WeaponName)[keyof typeof WeaponName];
export declare const SkillName: {
    readonly herculeanStrength: "herculeanStrength";
    readonly felineAgility: "felineAgility";
    readonly lightningBolt: "lightningBolt";
    readonly vitality: "vitality";
    readonly immortality: "immortality";
    readonly reconnaissance: "reconnaissance";
    readonly weaponsMaster: "weaponsMaster";
    readonly martialArts: "martialArts";
    readonly sixthSense: "sixthSense";
    readonly hostility: "hostility";
    readonly fistsOfFury: "fistsOfFury";
    readonly shield: "shield";
    readonly armor: "armor";
    readonly toughenedSkin: "toughenedSkin";
    readonly untouchable: "untouchable";
    readonly sabotage: "sabotage";
    readonly shock: "shock";
    readonly bodybuilder: "bodybuilder";
    readonly relentless: "relentless";
    readonly survival: "survival";
    readonly leadSkeleton: "leadSkeleton";
    readonly balletShoes: "balletShoes";
    readonly determination: "determination";
    readonly firstStrike: "firstStrike";
    readonly resistant: "resistant";
    readonly counterAttack: "counterAttack";
    readonly ironHead: "ironHead";
    readonly thief: "thief";
    readonly fierceBrute: "fierceBrute";
    readonly tragicPotion: "tragicPotion";
    readonly net: "net";
    readonly bomb: "bomb";
    readonly hammer: "hammer";
    readonly cryOfTheDamned: "cryOfTheDamned";
    readonly hypnosis: "hypnosis";
    readonly flashFlood: "flashFlood";
    readonly tamer: "tamer";
    readonly regeneration: "regeneration";
    readonly chef: "chef";
    readonly spy: "spy";
    readonly saboteur: "saboteur";
    readonly backup: "backup";
    readonly hideaway: "hideaway";
    readonly monk: "monk";
    readonly vampirism: "vampirism";
    readonly chaining: "chaining";
    readonly haste: "haste";
    readonly treat: "treat";
    readonly repulse: "repulse";
    readonly fastMetabolism: "fastMetabolism";
};
export type SkillName = (typeof SkillName)[keyof typeof SkillName];
export declare const PetName: {
    readonly dog1: "dog1";
    readonly dog2: "dog2";
    readonly dog3: "dog3";
    readonly panther: "panther";
    readonly bear: "bear";
};
export type PetName = (typeof PetName)[keyof typeof PetName];
export declare const FighterType: {
    readonly brute: "brute";
    readonly pet: "pet";
};
export type FighterType = (typeof FighterType)[keyof typeof FighterType];
export declare const FightModifier: {
    readonly noThrows: "noThrows";
    readonly focusOpponent: "focusOpponent";
    readonly alwaysUseSupers: "alwaysUseSupers";
    readonly drawEveryWeapon: "drawEveryWeapon";
    readonly doubleAgility: "doubleAgility";
    readonly randomSkill: "randomSkill";
    readonly randomWeapon: "randomWeapon";
    readonly bareHandsFirstHit: "bareHandsFirstHit";
    readonly startWithWeapon: "startWithWeapon";
    readonly chaos: "chaos";
};
export type FightModifier = (typeof FightModifier)[keyof typeof FightModifier];
export declare const LogType: {
    readonly win: "win";
    readonly lose: "lose";
    readonly child: "child";
    readonly childup: "childup";
    readonly up: "up";
    readonly lvl: "lvl";
    readonly ascend: "ascend";
    readonly tournament: "tournament";
    readonly tournamentXp: "tournamentXp";
    readonly bossFight: "bossFight";
    readonly bossDefeat: "bossDefeat";
};
export type LogType = (typeof LogType)[keyof typeof LogType];
export declare const DestinyChoiceType: {
    readonly skill: "skill";
    readonly weapon: "weapon";
    readonly pet: "pet";
    readonly stats: "stats";
};
export type DestinyChoiceType = (typeof DestinyChoiceType)[keyof typeof DestinyChoiceType];
export declare const BruteStat: {
    readonly endurance: "endurance";
    readonly strength: "strength";
    readonly agility: "agility";
    readonly speed: "speed";
};
export type BruteStat = (typeof BruteStat)[keyof typeof BruteStat];
export declare const TournamentType: {
    readonly DAILY: "DAILY";
    readonly GLOBAL: "GLOBAL";
    readonly UNLIMITED_GLOBAL: "UNLIMITED_GLOBAL";
    readonly CUSTOM: "CUSTOM";
    readonly BATTLE_ROYALE: "BATTLE_ROYALE";
};
export type TournamentType = (typeof TournamentType)[keyof typeof TournamentType];
export declare const AchievementName: {
    readonly wins: "wins";
    readonly defeats: "defeats";
    readonly flawless: "flawless";
    readonly winWith1HP: "winWith1HP";
    readonly steal2Weapons: "steal2Weapons";
    readonly singleHitWin: "singleHitWin";
    readonly combo3: "combo3";
    readonly combo4: "combo4";
    readonly combo5: "combo5";
    readonly counter5: "counter5";
    readonly evade10: "evade10";
    readonly block25: "block25";
    readonly counter4b2b: "counter4b2b";
    readonly reversal4b2b: "reversal4b2b";
    readonly block4b2b: "block4b2b";
    readonly evade4b2b: "evade4b2b";
    readonly throw10b2b: "throw10b2b";
    readonly disarm4: "disarm4";
    readonly disarm8: "disarm8";
    readonly damage50once: "damage50once";
    readonly damage100once: "damage100once";
    readonly hit20times: "hit20times";
    readonly use10skills: "use10skills";
    readonly kill3pets: "kill3pets";
    readonly maxDamage: "maxDamage";
    readonly hpHealed: "hpHealed";
    readonly saboteur: "saboteur";
    readonly dog: "dog";
    readonly panther: "panther";
    readonly bear: "bear";
    readonly panther_bear: "panther_bear";
    readonly felAg_fistsOfF: "felAg_fistsOfF";
    readonly felAg_fistsOfF_untouch_relentless: "felAg_fistsOfF_untouch_relentless";
    readonly vita_armor_toughened: "vita_armor_toughened";
    readonly herculStr_hammer_fierceBrute: "herculStr_hammer_fierceBrute";
    readonly shock: "shock";
    readonly balletShoes_survival: "balletShoes_survival";
    readonly cryOfTheDamned_hypnosis: "cryOfTheDamned_hypnosis";
    readonly shield_counterAttack: "shield_counterAttack";
    readonly reconnaissance_monk: "reconnaissance_monk";
    readonly immortality: "immortality";
    readonly doubleBoost: "doubleBoost";
    readonly tripleBoost: "tripleBoost";
    readonly quadrupleBoost: "quadrupleBoost";
    readonly regeneration_potion: "regeneration_potion";
    readonly bear_tamer: "bear_tamer";
    readonly tripleDogs: "tripleDogs";
    readonly fiveWeapons: "fiveWeapons";
    readonly tenWeapons: "tenWeapons";
    readonly fifteenWeapons: "fifteenWeapons";
    readonly twentyWeapons: "twentyWeapons";
    readonly twentyThreeWeapons: "twentyThreeWeapons";
    readonly monk_sixthSense_whip: "monk_sixthSense_whip";
    readonly weaponsMaster_sharp_bodybuilder_heavy: "weaponsMaster_sharp_bodybuilder_heavy";
    readonly hostility_counterWeapon: "hostility_counterWeapon";
    readonly flashFlood_twelveWeapons: "flashFlood_twelveWeapons";
    readonly lightningBolt_firstStrike: "lightningBolt_firstStrike";
    readonly herculeanStrength: "herculeanStrength";
    readonly felineAgility: "felineAgility";
    readonly lightningBolt: "lightningBolt";
    readonly vitality: "vitality";
    readonly potion_chef: "potion_chef";
    readonly tamer_net: "tamer_net";
    readonly untouchable_balletShoes: "untouchable_balletShoes";
    readonly survival_resistant: "survival_resistant";
    readonly hideaway_spy: "hideaway_spy";
    readonly weaponsFast3: "weaponsFast3";
    readonly weaponsSharp3: "weaponsSharp3";
    readonly weaponsHeavy3: "weaponsHeavy3";
    readonly weaponsLong3: "weaponsLong3";
    readonly weaponsThrown3: "weaponsThrown3";
    readonly weaponsBlunt3: "weaponsBlunt3";
    readonly thor: "thor";
    readonly deflector: "deflector";
    readonly allFastWeapons: "allFastWeapons";
    readonly allSharpWeapons: "allSharpWeapons";
    readonly allHeavyWeapons: "allHeavyWeapons";
    readonly allLongWeapons: "allLongWeapons";
    readonly allThrownWeapons: "allThrownWeapons";
    readonly allBluntWeapons: "allBluntWeapons";
    readonly agility50: "agility50";
    readonly agility100: "agility100";
    readonly speed50: "speed50";
    readonly speed100: "speed100";
    readonly strength50: "strength50";
    readonly strength100: "strength100";
    readonly hp300: "hp300";
    readonly hp600: "hp600";
    readonly maxLevel: "maxLevel";
    readonly allAchievements: "allAchievements";
    readonly winTournamentAs20: "winTournamentAs20";
    readonly winTournamentAs15: "winTournamentAs15";
    readonly looseAgainst2: "looseAgainst2";
    readonly looseAgainst3: "looseAgainst3";
    readonly looseAgainst4: "looseAgainst4";
    readonly winAgainst2: "winAgainst2";
    readonly winAgainst3: "winAgainst3";
    readonly winAgainst4: "winAgainst4";
    readonly winAsLower: "winAsLower";
    readonly win: "win";
    readonly battleRoyaleWin: "battleRoyaleWin";
    readonly rankUp10: "rankUp10";
    readonly rankUp9: "rankUp9";
    readonly rankUp8: "rankUp8";
    readonly rankUp7: "rankUp7";
    readonly rankUp6: "rankUp6";
    readonly rankUp5: "rankUp5";
    readonly rankUp4: "rankUp4";
    readonly rankUp3: "rankUp3";
    readonly rankUp2: "rankUp2";
    readonly rankUp1: "rankUp1";
    readonly rankUp0: "rankUp0";
    readonly ascend: "ascend";
    readonly sacrifice: "sacrifice";
    readonly beta: "beta";
    readonly bug: "bug";
};
export type AchievementName = (typeof AchievementName)[keyof typeof AchievementName];
export declare const BruteReportStatus: {
    readonly pending: "pending";
    readonly accepted: "accepted";
    readonly rejected: "rejected";
};
export type BruteReportStatus = (typeof BruteReportStatus)[keyof typeof BruteReportStatus];
export declare const BruteReportReason: {
    readonly name: "name";
};
export type BruteReportReason = (typeof BruteReportReason)[keyof typeof BruteReportReason];
export declare const BossName: {
    readonly GoldClaw: "GoldClaw";
    readonly EmberFang: "EmberFang";
    readonly Cerberus: "Cerberus";
};
export type BossName = (typeof BossName)[keyof typeof BossName];
export declare const ClanWarStatus: {
    readonly pending: "pending";
    readonly ongoing: "ongoing";
    readonly waitingForRewards: "waitingForRewards";
    readonly finished: "finished";
};
export type ClanWarStatus = (typeof ClanWarStatus)[keyof typeof ClanWarStatus];
export declare const ClanWarType: {
    readonly friendly: "friendly";
    readonly official: "official";
};
export type ClanWarType = (typeof ClanWarType)[keyof typeof ClanWarType];
export declare const InventoryItemType: {
    readonly visualReset: "visualReset";
    readonly bossTicket: "bossTicket";
    readonly nameChange: "nameChange";
    readonly favoriteFight: "favoriteFight";
};
export type InventoryItemType = (typeof InventoryItemType)[keyof typeof InventoryItemType];
export declare const EventType: {
    readonly battleRoyale: "battleRoyale";
};
export type EventType = (typeof EventType)[keyof typeof EventType];
export declare const EventStatus: {
    readonly starting: "starting";
    readonly ongoing: "ongoing";
    readonly finished: "finished";
};
export type EventStatus = (typeof EventStatus)[keyof typeof EventStatus];
export declare const NotificationSeverity: {
    readonly info: "info";
    readonly success: "success";
    readonly warning: "warning";
    readonly error: "error";
};
export type NotificationSeverity = (typeof NotificationSeverity)[keyof typeof NotificationSeverity];
