import {
  Animation,
} from '@eternaltwin/labrute-core/types';

const FRAMES: Record<'male' | 'female', Record<Animation, number>> = {
  male: {
    'arrive-end': 1,
    'arrive-start': 1,
    attack: 1,
    block: 1,
    death: 1,
    drink: 1,
    eat: 1,
    equip: 1,
    evade: 1,
    grab: 1,
    grabbed: 1,
    hit: 1,
    'hit-0': 1,
    'hit-1': 1,
    'hit-2': 1,
    'hit-3': 1,
    iddle: 39,
    launch: 1,
    'monk-loop': 1,
    'monk-start': 1,
    'prepare-throw': 1,
    run: 1,
    slash: 1,
    stolen: 1,
    steal: 1,
    strengthen: 1,
    throw: 1,
    train: 1,
    'trapped-loop': 1,
    'trapped-start': 1,
    trash: 1,
    win: 1,
    fist: 1,
    estoc: 1,
    whip: 1,
  },
  female: {
    'arrive-end': 1,
    'arrive-start': 1,
    attack: 1,
    block: 1,
    death: 1,
    drink: 1,
    eat: 1,
    equip: 1,
    evade: 1,
    grab: 1,
    grabbed: 1,
    hit: 1,
    'hit-0': 1,
    'hit-1': 1,
    'hit-2': 1,
    'hit-3': 1,
    iddle: 1,
    launch: 1,
    'monk-loop': 1,
    'monk-start': 1,
    'prepare-throw': 1,
    run: 1,
    slash: 1,
    stolen: 1,
    steal: 1,
    strengthen: 1,
    throw: 1,
    train: 1,
    'trapped-loop': 1,
    'trapped-start': 1,
    trash: 1,
    win: 1,
    fist: 1,
    estoc: 1,
    whip: 1,
  },
};

export default FRAMES;