
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Achievement` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Achievement
 * 
 */
export type AchievementModel = runtime.Types.Result.DefaultSelection<Prisma.$AchievementPayload>

export type AggregateAchievement = {
  _count: AchievementCountAggregateOutputType | null
  _avg: AchievementAvgAggregateOutputType | null
  _sum: AchievementSumAggregateOutputType | null
  _min: AchievementMinAggregateOutputType | null
  _max: AchievementMaxAggregateOutputType | null
}

export type AchievementAvgAggregateOutputType = {
  count: number | null
}

export type AchievementSumAggregateOutputType = {
  count: number | null
}

export type AchievementMinAggregateOutputType = {
  id: string | null
  name: $Enums.AchievementName | null
  count: number | null
  bruteId: string | null
  userId: string | null
}

export type AchievementMaxAggregateOutputType = {
  id: string | null
  name: $Enums.AchievementName | null
  count: number | null
  bruteId: string | null
  userId: string | null
}

export type AchievementCountAggregateOutputType = {
  id: number
  name: number
  count: number
  bruteId: number
  userId: number
  _all: number
}


export type AchievementAvgAggregateInputType = {
  count?: true
}

export type AchievementSumAggregateInputType = {
  count?: true
}

export type AchievementMinAggregateInputType = {
  id?: true
  name?: true
  count?: true
  bruteId?: true
  userId?: true
}

export type AchievementMaxAggregateInputType = {
  id?: true
  name?: true
  count?: true
  bruteId?: true
  userId?: true
}

export type AchievementCountAggregateInputType = {
  id?: true
  name?: true
  count?: true
  bruteId?: true
  userId?: true
  _all?: true
}

export type AchievementAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Achievement to aggregate.
   */
  where?: Prisma.AchievementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Achievements to fetch.
   */
  orderBy?: Prisma.AchievementOrderByWithRelationInput | Prisma.AchievementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AchievementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Achievements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Achievements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Achievements
  **/
  _count?: true | AchievementCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AchievementAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AchievementSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AchievementMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AchievementMaxAggregateInputType
}

export type GetAchievementAggregateType<T extends AchievementAggregateArgs> = {
      [P in keyof T & keyof AggregateAchievement]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAchievement[P]>
    : Prisma.GetScalarType<T[P], AggregateAchievement[P]>
}




export type AchievementGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AchievementWhereInput
  orderBy?: Prisma.AchievementOrderByWithAggregationInput | Prisma.AchievementOrderByWithAggregationInput[]
  by: Prisma.AchievementScalarFieldEnum[] | Prisma.AchievementScalarFieldEnum
  having?: Prisma.AchievementScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AchievementCountAggregateInputType | true
  _avg?: AchievementAvgAggregateInputType
  _sum?: AchievementSumAggregateInputType
  _min?: AchievementMinAggregateInputType
  _max?: AchievementMaxAggregateInputType
}

export type AchievementGroupByOutputType = {
  id: string
  name: $Enums.AchievementName
  count: number
  bruteId: string | null
  userId: string | null
  _count: AchievementCountAggregateOutputType | null
  _avg: AchievementAvgAggregateOutputType | null
  _sum: AchievementSumAggregateOutputType | null
  _min: AchievementMinAggregateOutputType | null
  _max: AchievementMaxAggregateOutputType | null
}

export type GetAchievementGroupByPayload<T extends AchievementGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AchievementGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AchievementGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AchievementGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AchievementGroupByOutputType[P]>
      }
    >
  >



export type AchievementWhereInput = {
  AND?: Prisma.AchievementWhereInput | Prisma.AchievementWhereInput[]
  OR?: Prisma.AchievementWhereInput[]
  NOT?: Prisma.AchievementWhereInput | Prisma.AchievementWhereInput[]
  id?: Prisma.UuidFilter<"Achievement"> | string
  name?: Prisma.EnumAchievementNameFilter<"Achievement"> | $Enums.AchievementName
  count?: Prisma.IntFilter<"Achievement"> | number
  bruteId?: Prisma.UuidNullableFilter<"Achievement"> | string | null
  userId?: Prisma.UuidNullableFilter<"Achievement"> | string | null
  brute?: Prisma.XOR<Prisma.BruteNullableScalarRelationFilter, Prisma.BruteWhereInput> | null
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type AchievementOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  count?: Prisma.SortOrder
  bruteId?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  brute?: Prisma.BruteOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type AchievementWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name_bruteId?: Prisma.AchievementNameBruteIdCompoundUniqueInput
  AND?: Prisma.AchievementWhereInput | Prisma.AchievementWhereInput[]
  OR?: Prisma.AchievementWhereInput[]
  NOT?: Prisma.AchievementWhereInput | Prisma.AchievementWhereInput[]
  name?: Prisma.EnumAchievementNameFilter<"Achievement"> | $Enums.AchievementName
  count?: Prisma.IntFilter<"Achievement"> | number
  bruteId?: Prisma.UuidNullableFilter<"Achievement"> | string | null
  userId?: Prisma.UuidNullableFilter<"Achievement"> | string | null
  brute?: Prisma.XOR<Prisma.BruteNullableScalarRelationFilter, Prisma.BruteWhereInput> | null
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id" | "id" | "name_bruteId">

export type AchievementOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  count?: Prisma.SortOrder
  bruteId?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.AchievementCountOrderByAggregateInput
  _avg?: Prisma.AchievementAvgOrderByAggregateInput
  _max?: Prisma.AchievementMaxOrderByAggregateInput
  _min?: Prisma.AchievementMinOrderByAggregateInput
  _sum?: Prisma.AchievementSumOrderByAggregateInput
}

export type AchievementScalarWhereWithAggregatesInput = {
  AND?: Prisma.AchievementScalarWhereWithAggregatesInput | Prisma.AchievementScalarWhereWithAggregatesInput[]
  OR?: Prisma.AchievementScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AchievementScalarWhereWithAggregatesInput | Prisma.AchievementScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Achievement"> | string
  name?: Prisma.EnumAchievementNameWithAggregatesFilter<"Achievement"> | $Enums.AchievementName
  count?: Prisma.IntWithAggregatesFilter<"Achievement"> | number
  bruteId?: Prisma.UuidNullableWithAggregatesFilter<"Achievement"> | string | null
  userId?: Prisma.UuidNullableWithAggregatesFilter<"Achievement"> | string | null
}

export type AchievementCreateInput = {
  id?: string
  name: $Enums.AchievementName
  count?: number
  brute?: Prisma.BruteCreateNestedOneWithoutAchievementsInput
  user?: Prisma.UserCreateNestedOneWithoutAchievementsInput
}

export type AchievementUncheckedCreateInput = {
  id?: string
  name: $Enums.AchievementName
  count?: number
  bruteId?: string | null
  userId?: string | null
}

export type AchievementUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  count?: Prisma.IntFieldUpdateOperationsInput | number
  brute?: Prisma.BruteUpdateOneWithoutAchievementsNestedInput
  user?: Prisma.UserUpdateOneWithoutAchievementsNestedInput
}

export type AchievementUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  count?: Prisma.IntFieldUpdateOperationsInput | number
  bruteId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AchievementCreateManyInput = {
  id?: string
  name: $Enums.AchievementName
  count?: number
  bruteId?: string | null
  userId?: string | null
}

export type AchievementUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  count?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AchievementUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  count?: Prisma.IntFieldUpdateOperationsInput | number
  bruteId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AchievementListRelationFilter = {
  every?: Prisma.AchievementWhereInput
  some?: Prisma.AchievementWhereInput
  none?: Prisma.AchievementWhereInput
}

export type AchievementOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AchievementNameBruteIdCompoundUniqueInput = {
  name: $Enums.AchievementName
  bruteId: string
}

export type AchievementCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  count?: Prisma.SortOrder
  bruteId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type AchievementAvgOrderByAggregateInput = {
  count?: Prisma.SortOrder
}

export type AchievementMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  count?: Prisma.SortOrder
  bruteId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type AchievementMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  count?: Prisma.SortOrder
  bruteId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type AchievementSumOrderByAggregateInput = {
  count?: Prisma.SortOrder
}

export type AchievementCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AchievementCreateWithoutUserInput, Prisma.AchievementUncheckedCreateWithoutUserInput> | Prisma.AchievementCreateWithoutUserInput[] | Prisma.AchievementUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AchievementCreateOrConnectWithoutUserInput | Prisma.AchievementCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AchievementCreateManyUserInputEnvelope
  connect?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
}

export type AchievementUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AchievementCreateWithoutUserInput, Prisma.AchievementUncheckedCreateWithoutUserInput> | Prisma.AchievementCreateWithoutUserInput[] | Prisma.AchievementUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AchievementCreateOrConnectWithoutUserInput | Prisma.AchievementCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AchievementCreateManyUserInputEnvelope
  connect?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
}

export type AchievementUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AchievementCreateWithoutUserInput, Prisma.AchievementUncheckedCreateWithoutUserInput> | Prisma.AchievementCreateWithoutUserInput[] | Prisma.AchievementUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AchievementCreateOrConnectWithoutUserInput | Prisma.AchievementCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AchievementUpsertWithWhereUniqueWithoutUserInput | Prisma.AchievementUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AchievementCreateManyUserInputEnvelope
  set?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
  disconnect?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
  delete?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
  connect?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
  update?: Prisma.AchievementUpdateWithWhereUniqueWithoutUserInput | Prisma.AchievementUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AchievementUpdateManyWithWhereWithoutUserInput | Prisma.AchievementUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AchievementScalarWhereInput | Prisma.AchievementScalarWhereInput[]
}

export type AchievementUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AchievementCreateWithoutUserInput, Prisma.AchievementUncheckedCreateWithoutUserInput> | Prisma.AchievementCreateWithoutUserInput[] | Prisma.AchievementUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AchievementCreateOrConnectWithoutUserInput | Prisma.AchievementCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AchievementUpsertWithWhereUniqueWithoutUserInput | Prisma.AchievementUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AchievementCreateManyUserInputEnvelope
  set?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
  disconnect?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
  delete?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
  connect?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
  update?: Prisma.AchievementUpdateWithWhereUniqueWithoutUserInput | Prisma.AchievementUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AchievementUpdateManyWithWhereWithoutUserInput | Prisma.AchievementUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AchievementScalarWhereInput | Prisma.AchievementScalarWhereInput[]
}

export type AchievementCreateNestedManyWithoutBruteInput = {
  create?: Prisma.XOR<Prisma.AchievementCreateWithoutBruteInput, Prisma.AchievementUncheckedCreateWithoutBruteInput> | Prisma.AchievementCreateWithoutBruteInput[] | Prisma.AchievementUncheckedCreateWithoutBruteInput[]
  connectOrCreate?: Prisma.AchievementCreateOrConnectWithoutBruteInput | Prisma.AchievementCreateOrConnectWithoutBruteInput[]
  createMany?: Prisma.AchievementCreateManyBruteInputEnvelope
  connect?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
}

export type AchievementUncheckedCreateNestedManyWithoutBruteInput = {
  create?: Prisma.XOR<Prisma.AchievementCreateWithoutBruteInput, Prisma.AchievementUncheckedCreateWithoutBruteInput> | Prisma.AchievementCreateWithoutBruteInput[] | Prisma.AchievementUncheckedCreateWithoutBruteInput[]
  connectOrCreate?: Prisma.AchievementCreateOrConnectWithoutBruteInput | Prisma.AchievementCreateOrConnectWithoutBruteInput[]
  createMany?: Prisma.AchievementCreateManyBruteInputEnvelope
  connect?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
}

export type AchievementUpdateManyWithoutBruteNestedInput = {
  create?: Prisma.XOR<Prisma.AchievementCreateWithoutBruteInput, Prisma.AchievementUncheckedCreateWithoutBruteInput> | Prisma.AchievementCreateWithoutBruteInput[] | Prisma.AchievementUncheckedCreateWithoutBruteInput[]
  connectOrCreate?: Prisma.AchievementCreateOrConnectWithoutBruteInput | Prisma.AchievementCreateOrConnectWithoutBruteInput[]
  upsert?: Prisma.AchievementUpsertWithWhereUniqueWithoutBruteInput | Prisma.AchievementUpsertWithWhereUniqueWithoutBruteInput[]
  createMany?: Prisma.AchievementCreateManyBruteInputEnvelope
  set?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
  disconnect?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
  delete?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
  connect?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
  update?: Prisma.AchievementUpdateWithWhereUniqueWithoutBruteInput | Prisma.AchievementUpdateWithWhereUniqueWithoutBruteInput[]
  updateMany?: Prisma.AchievementUpdateManyWithWhereWithoutBruteInput | Prisma.AchievementUpdateManyWithWhereWithoutBruteInput[]
  deleteMany?: Prisma.AchievementScalarWhereInput | Prisma.AchievementScalarWhereInput[]
}

export type AchievementUncheckedUpdateManyWithoutBruteNestedInput = {
  create?: Prisma.XOR<Prisma.AchievementCreateWithoutBruteInput, Prisma.AchievementUncheckedCreateWithoutBruteInput> | Prisma.AchievementCreateWithoutBruteInput[] | Prisma.AchievementUncheckedCreateWithoutBruteInput[]
  connectOrCreate?: Prisma.AchievementCreateOrConnectWithoutBruteInput | Prisma.AchievementCreateOrConnectWithoutBruteInput[]
  upsert?: Prisma.AchievementUpsertWithWhereUniqueWithoutBruteInput | Prisma.AchievementUpsertWithWhereUniqueWithoutBruteInput[]
  createMany?: Prisma.AchievementCreateManyBruteInputEnvelope
  set?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
  disconnect?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
  delete?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
  connect?: Prisma.AchievementWhereUniqueInput | Prisma.AchievementWhereUniqueInput[]
  update?: Prisma.AchievementUpdateWithWhereUniqueWithoutBruteInput | Prisma.AchievementUpdateWithWhereUniqueWithoutBruteInput[]
  updateMany?: Prisma.AchievementUpdateManyWithWhereWithoutBruteInput | Prisma.AchievementUpdateManyWithWhereWithoutBruteInput[]
  deleteMany?: Prisma.AchievementScalarWhereInput | Prisma.AchievementScalarWhereInput[]
}

export type AchievementCreateWithoutUserInput = {
  id?: string
  name: $Enums.AchievementName
  count?: number
  brute?: Prisma.BruteCreateNestedOneWithoutAchievementsInput
}

export type AchievementUncheckedCreateWithoutUserInput = {
  id?: string
  name: $Enums.AchievementName
  count?: number
  bruteId?: string | null
}

export type AchievementCreateOrConnectWithoutUserInput = {
  where: Prisma.AchievementWhereUniqueInput
  create: Prisma.XOR<Prisma.AchievementCreateWithoutUserInput, Prisma.AchievementUncheckedCreateWithoutUserInput>
}

export type AchievementCreateManyUserInputEnvelope = {
  data: Prisma.AchievementCreateManyUserInput | Prisma.AchievementCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type AchievementUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.AchievementWhereUniqueInput
  update: Prisma.XOR<Prisma.AchievementUpdateWithoutUserInput, Prisma.AchievementUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AchievementCreateWithoutUserInput, Prisma.AchievementUncheckedCreateWithoutUserInput>
}

export type AchievementUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.AchievementWhereUniqueInput
  data: Prisma.XOR<Prisma.AchievementUpdateWithoutUserInput, Prisma.AchievementUncheckedUpdateWithoutUserInput>
}

export type AchievementUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.AchievementScalarWhereInput
  data: Prisma.XOR<Prisma.AchievementUpdateManyMutationInput, Prisma.AchievementUncheckedUpdateManyWithoutUserInput>
}

export type AchievementScalarWhereInput = {
  AND?: Prisma.AchievementScalarWhereInput | Prisma.AchievementScalarWhereInput[]
  OR?: Prisma.AchievementScalarWhereInput[]
  NOT?: Prisma.AchievementScalarWhereInput | Prisma.AchievementScalarWhereInput[]
  id?: Prisma.UuidFilter<"Achievement"> | string
  name?: Prisma.EnumAchievementNameFilter<"Achievement"> | $Enums.AchievementName
  count?: Prisma.IntFilter<"Achievement"> | number
  bruteId?: Prisma.UuidNullableFilter<"Achievement"> | string | null
  userId?: Prisma.UuidNullableFilter<"Achievement"> | string | null
}

export type AchievementCreateWithoutBruteInput = {
  id?: string
  name: $Enums.AchievementName
  count?: number
  user?: Prisma.UserCreateNestedOneWithoutAchievementsInput
}

export type AchievementUncheckedCreateWithoutBruteInput = {
  id?: string
  name: $Enums.AchievementName
  count?: number
  userId?: string | null
}

export type AchievementCreateOrConnectWithoutBruteInput = {
  where: Prisma.AchievementWhereUniqueInput
  create: Prisma.XOR<Prisma.AchievementCreateWithoutBruteInput, Prisma.AchievementUncheckedCreateWithoutBruteInput>
}

export type AchievementCreateManyBruteInputEnvelope = {
  data: Prisma.AchievementCreateManyBruteInput | Prisma.AchievementCreateManyBruteInput[]
  skipDuplicates?: boolean
}

export type AchievementUpsertWithWhereUniqueWithoutBruteInput = {
  where: Prisma.AchievementWhereUniqueInput
  update: Prisma.XOR<Prisma.AchievementUpdateWithoutBruteInput, Prisma.AchievementUncheckedUpdateWithoutBruteInput>
  create: Prisma.XOR<Prisma.AchievementCreateWithoutBruteInput, Prisma.AchievementUncheckedCreateWithoutBruteInput>
}

export type AchievementUpdateWithWhereUniqueWithoutBruteInput = {
  where: Prisma.AchievementWhereUniqueInput
  data: Prisma.XOR<Prisma.AchievementUpdateWithoutBruteInput, Prisma.AchievementUncheckedUpdateWithoutBruteInput>
}

export type AchievementUpdateManyWithWhereWithoutBruteInput = {
  where: Prisma.AchievementScalarWhereInput
  data: Prisma.XOR<Prisma.AchievementUpdateManyMutationInput, Prisma.AchievementUncheckedUpdateManyWithoutBruteInput>
}

export type AchievementCreateManyUserInput = {
  id?: string
  name: $Enums.AchievementName
  count?: number
  bruteId?: string | null
}

export type AchievementUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  count?: Prisma.IntFieldUpdateOperationsInput | number
  brute?: Prisma.BruteUpdateOneWithoutAchievementsNestedInput
}

export type AchievementUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  count?: Prisma.IntFieldUpdateOperationsInput | number
  bruteId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AchievementUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  count?: Prisma.IntFieldUpdateOperationsInput | number
  bruteId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AchievementCreateManyBruteInput = {
  id?: string
  name: $Enums.AchievementName
  count?: number
  userId?: string | null
}

export type AchievementUpdateWithoutBruteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  count?: Prisma.IntFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneWithoutAchievementsNestedInput
}

export type AchievementUncheckedUpdateWithoutBruteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  count?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AchievementUncheckedUpdateManyWithoutBruteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  count?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type AchievementSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  count?: boolean
  bruteId?: boolean
  userId?: boolean
  brute?: boolean | Prisma.Achievement$bruteArgs<ExtArgs>
  user?: boolean | Prisma.Achievement$userArgs<ExtArgs>
}, ExtArgs["result"]["achievement"]>

export type AchievementSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  count?: boolean
  bruteId?: boolean
  userId?: boolean
  brute?: boolean | Prisma.Achievement$bruteArgs<ExtArgs>
  user?: boolean | Prisma.Achievement$userArgs<ExtArgs>
}, ExtArgs["result"]["achievement"]>

export type AchievementSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  count?: boolean
  bruteId?: boolean
  userId?: boolean
  brute?: boolean | Prisma.Achievement$bruteArgs<ExtArgs>
  user?: boolean | Prisma.Achievement$userArgs<ExtArgs>
}, ExtArgs["result"]["achievement"]>

export type AchievementSelectScalar = {
  id?: boolean
  name?: boolean
  count?: boolean
  bruteId?: boolean
  userId?: boolean
}

export type AchievementOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "count" | "bruteId" | "userId", ExtArgs["result"]["achievement"]>
export type AchievementInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  brute?: boolean | Prisma.Achievement$bruteArgs<ExtArgs>
  user?: boolean | Prisma.Achievement$userArgs<ExtArgs>
}
export type AchievementIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  brute?: boolean | Prisma.Achievement$bruteArgs<ExtArgs>
  user?: boolean | Prisma.Achievement$userArgs<ExtArgs>
}
export type AchievementIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  brute?: boolean | Prisma.Achievement$bruteArgs<ExtArgs>
  user?: boolean | Prisma.Achievement$userArgs<ExtArgs>
}

export type $AchievementPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Achievement"
  objects: {
    brute: Prisma.$BrutePayload<ExtArgs> | null
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: $Enums.AchievementName
    count: number
    bruteId: string | null
    userId: string | null
  }, ExtArgs["result"]["achievement"]>
  composites: {}
}

export type AchievementGetPayload<S extends boolean | null | undefined | AchievementDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AchievementPayload, S>

export type AchievementCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AchievementFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: AchievementCountAggregateInputType | true
  }

export interface AchievementDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Achievement'], meta: { name: 'Achievement' } }
  /**
   * Find zero or one Achievement that matches the filter.
   * @param {AchievementFindUniqueArgs} args - Arguments to find a Achievement
   * @example
   * // Get one Achievement
   * const achievement = await prisma.achievement.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AchievementFindUniqueArgs>(args: Prisma.SelectSubset<T, AchievementFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AchievementClient<runtime.Types.Result.GetResult<Prisma.$AchievementPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Achievement that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AchievementFindUniqueOrThrowArgs} args - Arguments to find a Achievement
   * @example
   * // Get one Achievement
   * const achievement = await prisma.achievement.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AchievementFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AchievementFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AchievementClient<runtime.Types.Result.GetResult<Prisma.$AchievementPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Achievement that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AchievementFindFirstArgs} args - Arguments to find a Achievement
   * @example
   * // Get one Achievement
   * const achievement = await prisma.achievement.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AchievementFindFirstArgs>(args?: Prisma.SelectSubset<T, AchievementFindFirstArgs<ExtArgs>>): Prisma.Prisma__AchievementClient<runtime.Types.Result.GetResult<Prisma.$AchievementPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Achievement that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AchievementFindFirstOrThrowArgs} args - Arguments to find a Achievement
   * @example
   * // Get one Achievement
   * const achievement = await prisma.achievement.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AchievementFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AchievementFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AchievementClient<runtime.Types.Result.GetResult<Prisma.$AchievementPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Achievements that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AchievementFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Achievements
   * const achievements = await prisma.achievement.findMany()
   * 
   * // Get first 10 Achievements
   * const achievements = await prisma.achievement.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const achievementWithIdOnly = await prisma.achievement.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AchievementFindManyArgs>(args?: Prisma.SelectSubset<T, AchievementFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AchievementPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Achievement.
   * @param {AchievementCreateArgs} args - Arguments to create a Achievement.
   * @example
   * // Create one Achievement
   * const Achievement = await prisma.achievement.create({
   *   data: {
   *     // ... data to create a Achievement
   *   }
   * })
   * 
   */
  create<T extends AchievementCreateArgs>(args: Prisma.SelectSubset<T, AchievementCreateArgs<ExtArgs>>): Prisma.Prisma__AchievementClient<runtime.Types.Result.GetResult<Prisma.$AchievementPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Achievements.
   * @param {AchievementCreateManyArgs} args - Arguments to create many Achievements.
   * @example
   * // Create many Achievements
   * const achievement = await prisma.achievement.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AchievementCreateManyArgs>(args?: Prisma.SelectSubset<T, AchievementCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Achievements and returns the data saved in the database.
   * @param {AchievementCreateManyAndReturnArgs} args - Arguments to create many Achievements.
   * @example
   * // Create many Achievements
   * const achievement = await prisma.achievement.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Achievements and only return the `id`
   * const achievementWithIdOnly = await prisma.achievement.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AchievementCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AchievementCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AchievementPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Achievement.
   * @param {AchievementDeleteArgs} args - Arguments to delete one Achievement.
   * @example
   * // Delete one Achievement
   * const Achievement = await prisma.achievement.delete({
   *   where: {
   *     // ... filter to delete one Achievement
   *   }
   * })
   * 
   */
  delete<T extends AchievementDeleteArgs>(args: Prisma.SelectSubset<T, AchievementDeleteArgs<ExtArgs>>): Prisma.Prisma__AchievementClient<runtime.Types.Result.GetResult<Prisma.$AchievementPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Achievement.
   * @param {AchievementUpdateArgs} args - Arguments to update one Achievement.
   * @example
   * // Update one Achievement
   * const achievement = await prisma.achievement.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AchievementUpdateArgs>(args: Prisma.SelectSubset<T, AchievementUpdateArgs<ExtArgs>>): Prisma.Prisma__AchievementClient<runtime.Types.Result.GetResult<Prisma.$AchievementPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Achievements.
   * @param {AchievementDeleteManyArgs} args - Arguments to filter Achievements to delete.
   * @example
   * // Delete a few Achievements
   * const { count } = await prisma.achievement.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AchievementDeleteManyArgs>(args?: Prisma.SelectSubset<T, AchievementDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Achievements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AchievementUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Achievements
   * const achievement = await prisma.achievement.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AchievementUpdateManyArgs>(args: Prisma.SelectSubset<T, AchievementUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Achievements and returns the data updated in the database.
   * @param {AchievementUpdateManyAndReturnArgs} args - Arguments to update many Achievements.
   * @example
   * // Update many Achievements
   * const achievement = await prisma.achievement.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Achievements and only return the `id`
   * const achievementWithIdOnly = await prisma.achievement.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AchievementUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AchievementUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AchievementPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Achievement.
   * @param {AchievementUpsertArgs} args - Arguments to update or create a Achievement.
   * @example
   * // Update or create a Achievement
   * const achievement = await prisma.achievement.upsert({
   *   create: {
   *     // ... data to create a Achievement
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Achievement we want to update
   *   }
   * })
   */
  upsert<T extends AchievementUpsertArgs>(args: Prisma.SelectSubset<T, AchievementUpsertArgs<ExtArgs>>): Prisma.Prisma__AchievementClient<runtime.Types.Result.GetResult<Prisma.$AchievementPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Achievements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AchievementCountArgs} args - Arguments to filter Achievements to count.
   * @example
   * // Count the number of Achievements
   * const count = await prisma.achievement.count({
   *   where: {
   *     // ... the filter for the Achievements we want to count
   *   }
   * })
  **/
  count<T extends AchievementCountArgs>(
    args?: Prisma.Subset<T, AchievementCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AchievementCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Achievement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AchievementAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AchievementAggregateArgs>(args: Prisma.Subset<T, AchievementAggregateArgs>): Prisma.PrismaPromise<GetAchievementAggregateType<T>>

  /**
   * Group by Achievement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AchievementGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AchievementGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AchievementGroupByArgs['orderBy'] }
      : { orderBy?: AchievementGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AchievementGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAchievementGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Achievement model
 */
readonly fields: AchievementFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Achievement.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AchievementClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  brute<T extends Prisma.Achievement$bruteArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Achievement$bruteArgs<ExtArgs>>): Prisma.Prisma__BruteClient<runtime.Types.Result.GetResult<Prisma.$BrutePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.Achievement$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Achievement$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Achievement model
 */
export interface AchievementFieldRefs {
  readonly id: Prisma.FieldRef<"Achievement", 'String'>
  readonly name: Prisma.FieldRef<"Achievement", 'AchievementName'>
  readonly count: Prisma.FieldRef<"Achievement", 'Int'>
  readonly bruteId: Prisma.FieldRef<"Achievement", 'String'>
  readonly userId: Prisma.FieldRef<"Achievement", 'String'>
}
    

// Custom InputTypes
/**
 * Achievement findUnique
 */
export type AchievementFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Achievement
   */
  select?: Prisma.AchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Achievement
   */
  omit?: Prisma.AchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AchievementInclude<ExtArgs> | null
  /**
   * Filter, which Achievement to fetch.
   */
  where: Prisma.AchievementWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Achievement findUniqueOrThrow
 */
export type AchievementFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Achievement
   */
  select?: Prisma.AchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Achievement
   */
  omit?: Prisma.AchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AchievementInclude<ExtArgs> | null
  /**
   * Filter, which Achievement to fetch.
   */
  where: Prisma.AchievementWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Achievement findFirst
 */
export type AchievementFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Achievement
   */
  select?: Prisma.AchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Achievement
   */
  omit?: Prisma.AchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AchievementInclude<ExtArgs> | null
  /**
   * Filter, which Achievement to fetch.
   */
  where?: Prisma.AchievementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Achievements to fetch.
   */
  orderBy?: Prisma.AchievementOrderByWithRelationInput | Prisma.AchievementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Achievements.
   */
  cursor?: Prisma.AchievementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Achievements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Achievements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Achievements.
   */
  distinct?: Prisma.AchievementScalarFieldEnum | Prisma.AchievementScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Achievement findFirstOrThrow
 */
export type AchievementFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Achievement
   */
  select?: Prisma.AchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Achievement
   */
  omit?: Prisma.AchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AchievementInclude<ExtArgs> | null
  /**
   * Filter, which Achievement to fetch.
   */
  where?: Prisma.AchievementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Achievements to fetch.
   */
  orderBy?: Prisma.AchievementOrderByWithRelationInput | Prisma.AchievementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Achievements.
   */
  cursor?: Prisma.AchievementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Achievements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Achievements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Achievements.
   */
  distinct?: Prisma.AchievementScalarFieldEnum | Prisma.AchievementScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Achievement findMany
 */
export type AchievementFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Achievement
   */
  select?: Prisma.AchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Achievement
   */
  omit?: Prisma.AchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AchievementInclude<ExtArgs> | null
  /**
   * Filter, which Achievements to fetch.
   */
  where?: Prisma.AchievementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Achievements to fetch.
   */
  orderBy?: Prisma.AchievementOrderByWithRelationInput | Prisma.AchievementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Achievements.
   */
  cursor?: Prisma.AchievementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Achievements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Achievements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Achievements.
   */
  distinct?: Prisma.AchievementScalarFieldEnum | Prisma.AchievementScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Achievement create
 */
export type AchievementCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Achievement
   */
  select?: Prisma.AchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Achievement
   */
  omit?: Prisma.AchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AchievementInclude<ExtArgs> | null
  /**
   * The data needed to create a Achievement.
   */
  data: Prisma.XOR<Prisma.AchievementCreateInput, Prisma.AchievementUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Achievement createMany
 */
export type AchievementCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Achievements.
   */
  data: Prisma.AchievementCreateManyInput | Prisma.AchievementCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Achievement createManyAndReturn
 */
export type AchievementCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Achievement
   */
  select?: Prisma.AchievementSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Achievement
   */
  omit?: Prisma.AchievementOmit<ExtArgs> | null
  /**
   * The data used to create many Achievements.
   */
  data: Prisma.AchievementCreateManyInput | Prisma.AchievementCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AchievementIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Achievement update
 */
export type AchievementUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Achievement
   */
  select?: Prisma.AchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Achievement
   */
  omit?: Prisma.AchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AchievementInclude<ExtArgs> | null
  /**
   * The data needed to update a Achievement.
   */
  data: Prisma.XOR<Prisma.AchievementUpdateInput, Prisma.AchievementUncheckedUpdateInput>
  /**
   * Choose, which Achievement to update.
   */
  where: Prisma.AchievementWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Achievement updateMany
 */
export type AchievementUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Achievements.
   */
  data: Prisma.XOR<Prisma.AchievementUpdateManyMutationInput, Prisma.AchievementUncheckedUpdateManyInput>
  /**
   * Filter which Achievements to update
   */
  where?: Prisma.AchievementWhereInput
  /**
   * Limit how many Achievements to update.
   */
  limit?: number
}

/**
 * Achievement updateManyAndReturn
 */
export type AchievementUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Achievement
   */
  select?: Prisma.AchievementSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Achievement
   */
  omit?: Prisma.AchievementOmit<ExtArgs> | null
  /**
   * The data used to update Achievements.
   */
  data: Prisma.XOR<Prisma.AchievementUpdateManyMutationInput, Prisma.AchievementUncheckedUpdateManyInput>
  /**
   * Filter which Achievements to update
   */
  where?: Prisma.AchievementWhereInput
  /**
   * Limit how many Achievements to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AchievementIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Achievement upsert
 */
export type AchievementUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Achievement
   */
  select?: Prisma.AchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Achievement
   */
  omit?: Prisma.AchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AchievementInclude<ExtArgs> | null
  /**
   * The filter to search for the Achievement to update in case it exists.
   */
  where: Prisma.AchievementWhereUniqueInput
  /**
   * In case the Achievement found by the `where` argument doesn't exist, create a new Achievement with this data.
   */
  create: Prisma.XOR<Prisma.AchievementCreateInput, Prisma.AchievementUncheckedCreateInput>
  /**
   * In case the Achievement was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AchievementUpdateInput, Prisma.AchievementUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Achievement delete
 */
export type AchievementDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Achievement
   */
  select?: Prisma.AchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Achievement
   */
  omit?: Prisma.AchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AchievementInclude<ExtArgs> | null
  /**
   * Filter which Achievement to delete.
   */
  where: Prisma.AchievementWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Achievement deleteMany
 */
export type AchievementDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Achievements to delete
   */
  where?: Prisma.AchievementWhereInput
  /**
   * Limit how many Achievements to delete.
   */
  limit?: number
}

/**
 * Achievement.brute
 */
export type Achievement$bruteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Brute
   */
  select?: Prisma.BruteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Brute
   */
  omit?: Prisma.BruteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BruteInclude<ExtArgs> | null
  where?: Prisma.BruteWhereInput
}

/**
 * Achievement.user
 */
export type Achievement$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Achievement without action
 */
export type AchievementDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Achievement
   */
  select?: Prisma.AchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Achievement
   */
  omit?: Prisma.AchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AchievementInclude<ExtArgs> | null
}
