
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BannedIp` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BannedIp
 * 
 */
export type BannedIpModel = runtime.Types.Result.DefaultSelection<Prisma.$BannedIpPayload>

export type AggregateBannedIp = {
  _count: BannedIpCountAggregateOutputType | null
  _min: BannedIpMinAggregateOutputType | null
  _max: BannedIpMaxAggregateOutputType | null
}

export type BannedIpMinAggregateOutputType = {
  id: string | null
}

export type BannedIpMaxAggregateOutputType = {
  id: string | null
}

export type BannedIpCountAggregateOutputType = {
  id: number
  _all: number
}


export type BannedIpMinAggregateInputType = {
  id?: true
}

export type BannedIpMaxAggregateInputType = {
  id?: true
}

export type BannedIpCountAggregateInputType = {
  id?: true
  _all?: true
}

export type BannedIpAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BannedIp to aggregate.
   */
  where?: Prisma.BannedIpWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BannedIps to fetch.
   */
  orderBy?: Prisma.BannedIpOrderByWithRelationInput | Prisma.BannedIpOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BannedIpWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BannedIps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BannedIps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BannedIps
  **/
  _count?: true | BannedIpCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BannedIpMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BannedIpMaxAggregateInputType
}

export type GetBannedIpAggregateType<T extends BannedIpAggregateArgs> = {
      [P in keyof T & keyof AggregateBannedIp]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBannedIp[P]>
    : Prisma.GetScalarType<T[P], AggregateBannedIp[P]>
}




export type BannedIpGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BannedIpWhereInput
  orderBy?: Prisma.BannedIpOrderByWithAggregationInput | Prisma.BannedIpOrderByWithAggregationInput[]
  by: Prisma.BannedIpScalarFieldEnum[] | Prisma.BannedIpScalarFieldEnum
  having?: Prisma.BannedIpScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BannedIpCountAggregateInputType | true
  _min?: BannedIpMinAggregateInputType
  _max?: BannedIpMaxAggregateInputType
}

export type BannedIpGroupByOutputType = {
  id: string
  _count: BannedIpCountAggregateOutputType | null
  _min: BannedIpMinAggregateOutputType | null
  _max: BannedIpMaxAggregateOutputType | null
}

export type GetBannedIpGroupByPayload<T extends BannedIpGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BannedIpGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BannedIpGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BannedIpGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BannedIpGroupByOutputType[P]>
      }
    >
  >



export type BannedIpWhereInput = {
  AND?: Prisma.BannedIpWhereInput | Prisma.BannedIpWhereInput[]
  OR?: Prisma.BannedIpWhereInput[]
  NOT?: Prisma.BannedIpWhereInput | Prisma.BannedIpWhereInput[]
  id?: Prisma.StringFilter<"BannedIp"> | string
}

export type BannedIpOrderByWithRelationInput = {
  id?: Prisma.SortOrder
}

export type BannedIpWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BannedIpWhereInput | Prisma.BannedIpWhereInput[]
  OR?: Prisma.BannedIpWhereInput[]
  NOT?: Prisma.BannedIpWhereInput | Prisma.BannedIpWhereInput[]
}, "id">

export type BannedIpOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  _count?: Prisma.BannedIpCountOrderByAggregateInput
  _max?: Prisma.BannedIpMaxOrderByAggregateInput
  _min?: Prisma.BannedIpMinOrderByAggregateInput
}

export type BannedIpScalarWhereWithAggregatesInput = {
  AND?: Prisma.BannedIpScalarWhereWithAggregatesInput | Prisma.BannedIpScalarWhereWithAggregatesInput[]
  OR?: Prisma.BannedIpScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BannedIpScalarWhereWithAggregatesInput | Prisma.BannedIpScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BannedIp"> | string
}

export type BannedIpCreateInput = {
  id: string
}

export type BannedIpUncheckedCreateInput = {
  id: string
}

export type BannedIpUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BannedIpUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BannedIpCreateManyInput = {
  id: string
}

export type BannedIpUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BannedIpUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BannedIpCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type BannedIpMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type BannedIpMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type BannedIpSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
}, ExtArgs["result"]["bannedIp"]>

export type BannedIpSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
}, ExtArgs["result"]["bannedIp"]>

export type BannedIpSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
}, ExtArgs["result"]["bannedIp"]>

export type BannedIpSelectScalar = {
  id?: boolean
}

export type BannedIpOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id", ExtArgs["result"]["bannedIp"]>

export type $BannedIpPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BannedIp"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
  }, ExtArgs["result"]["bannedIp"]>
  composites: {}
}

export type BannedIpGetPayload<S extends boolean | null | undefined | BannedIpDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BannedIpPayload, S>

export type BannedIpCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BannedIpFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: BannedIpCountAggregateInputType | true
  }

export interface BannedIpDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BannedIp'], meta: { name: 'BannedIp' } }
  /**
   * Find zero or one BannedIp that matches the filter.
   * @param {BannedIpFindUniqueArgs} args - Arguments to find a BannedIp
   * @example
   * // Get one BannedIp
   * const bannedIp = await prisma.bannedIp.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BannedIpFindUniqueArgs>(args: Prisma.SelectSubset<T, BannedIpFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BannedIpClient<runtime.Types.Result.GetResult<Prisma.$BannedIpPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BannedIp that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BannedIpFindUniqueOrThrowArgs} args - Arguments to find a BannedIp
   * @example
   * // Get one BannedIp
   * const bannedIp = await prisma.bannedIp.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BannedIpFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BannedIpFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BannedIpClient<runtime.Types.Result.GetResult<Prisma.$BannedIpPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BannedIp that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BannedIpFindFirstArgs} args - Arguments to find a BannedIp
   * @example
   * // Get one BannedIp
   * const bannedIp = await prisma.bannedIp.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BannedIpFindFirstArgs>(args?: Prisma.SelectSubset<T, BannedIpFindFirstArgs<ExtArgs>>): Prisma.Prisma__BannedIpClient<runtime.Types.Result.GetResult<Prisma.$BannedIpPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BannedIp that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BannedIpFindFirstOrThrowArgs} args - Arguments to find a BannedIp
   * @example
   * // Get one BannedIp
   * const bannedIp = await prisma.bannedIp.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BannedIpFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BannedIpFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BannedIpClient<runtime.Types.Result.GetResult<Prisma.$BannedIpPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BannedIps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BannedIpFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BannedIps
   * const bannedIps = await prisma.bannedIp.findMany()
   * 
   * // Get first 10 BannedIps
   * const bannedIps = await prisma.bannedIp.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const bannedIpWithIdOnly = await prisma.bannedIp.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BannedIpFindManyArgs>(args?: Prisma.SelectSubset<T, BannedIpFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BannedIpPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BannedIp.
   * @param {BannedIpCreateArgs} args - Arguments to create a BannedIp.
   * @example
   * // Create one BannedIp
   * const BannedIp = await prisma.bannedIp.create({
   *   data: {
   *     // ... data to create a BannedIp
   *   }
   * })
   * 
   */
  create<T extends BannedIpCreateArgs>(args: Prisma.SelectSubset<T, BannedIpCreateArgs<ExtArgs>>): Prisma.Prisma__BannedIpClient<runtime.Types.Result.GetResult<Prisma.$BannedIpPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BannedIps.
   * @param {BannedIpCreateManyArgs} args - Arguments to create many BannedIps.
   * @example
   * // Create many BannedIps
   * const bannedIp = await prisma.bannedIp.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BannedIpCreateManyArgs>(args?: Prisma.SelectSubset<T, BannedIpCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BannedIps and returns the data saved in the database.
   * @param {BannedIpCreateManyAndReturnArgs} args - Arguments to create many BannedIps.
   * @example
   * // Create many BannedIps
   * const bannedIp = await prisma.bannedIp.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BannedIps and only return the `id`
   * const bannedIpWithIdOnly = await prisma.bannedIp.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BannedIpCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BannedIpCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BannedIpPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BannedIp.
   * @param {BannedIpDeleteArgs} args - Arguments to delete one BannedIp.
   * @example
   * // Delete one BannedIp
   * const BannedIp = await prisma.bannedIp.delete({
   *   where: {
   *     // ... filter to delete one BannedIp
   *   }
   * })
   * 
   */
  delete<T extends BannedIpDeleteArgs>(args: Prisma.SelectSubset<T, BannedIpDeleteArgs<ExtArgs>>): Prisma.Prisma__BannedIpClient<runtime.Types.Result.GetResult<Prisma.$BannedIpPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BannedIp.
   * @param {BannedIpUpdateArgs} args - Arguments to update one BannedIp.
   * @example
   * // Update one BannedIp
   * const bannedIp = await prisma.bannedIp.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BannedIpUpdateArgs>(args: Prisma.SelectSubset<T, BannedIpUpdateArgs<ExtArgs>>): Prisma.Prisma__BannedIpClient<runtime.Types.Result.GetResult<Prisma.$BannedIpPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BannedIps.
   * @param {BannedIpDeleteManyArgs} args - Arguments to filter BannedIps to delete.
   * @example
   * // Delete a few BannedIps
   * const { count } = await prisma.bannedIp.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BannedIpDeleteManyArgs>(args?: Prisma.SelectSubset<T, BannedIpDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BannedIps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BannedIpUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BannedIps
   * const bannedIp = await prisma.bannedIp.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BannedIpUpdateManyArgs>(args: Prisma.SelectSubset<T, BannedIpUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BannedIps and returns the data updated in the database.
   * @param {BannedIpUpdateManyAndReturnArgs} args - Arguments to update many BannedIps.
   * @example
   * // Update many BannedIps
   * const bannedIp = await prisma.bannedIp.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BannedIps and only return the `id`
   * const bannedIpWithIdOnly = await prisma.bannedIp.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BannedIpUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BannedIpUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BannedIpPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BannedIp.
   * @param {BannedIpUpsertArgs} args - Arguments to update or create a BannedIp.
   * @example
   * // Update or create a BannedIp
   * const bannedIp = await prisma.bannedIp.upsert({
   *   create: {
   *     // ... data to create a BannedIp
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BannedIp we want to update
   *   }
   * })
   */
  upsert<T extends BannedIpUpsertArgs>(args: Prisma.SelectSubset<T, BannedIpUpsertArgs<ExtArgs>>): Prisma.Prisma__BannedIpClient<runtime.Types.Result.GetResult<Prisma.$BannedIpPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BannedIps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BannedIpCountArgs} args - Arguments to filter BannedIps to count.
   * @example
   * // Count the number of BannedIps
   * const count = await prisma.bannedIp.count({
   *   where: {
   *     // ... the filter for the BannedIps we want to count
   *   }
   * })
  **/
  count<T extends BannedIpCountArgs>(
    args?: Prisma.Subset<T, BannedIpCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BannedIpCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BannedIp.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BannedIpAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BannedIpAggregateArgs>(args: Prisma.Subset<T, BannedIpAggregateArgs>): Prisma.PrismaPromise<GetBannedIpAggregateType<T>>

  /**
   * Group by BannedIp.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BannedIpGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BannedIpGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BannedIpGroupByArgs['orderBy'] }
      : { orderBy?: BannedIpGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BannedIpGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBannedIpGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BannedIp model
 */
readonly fields: BannedIpFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BannedIp.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BannedIpClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BannedIp model
 */
export interface BannedIpFieldRefs {
  readonly id: Prisma.FieldRef<"BannedIp", 'String'>
}
    

// Custom InputTypes
/**
 * BannedIp findUnique
 */
export type BannedIpFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedIp
   */
  select?: Prisma.BannedIpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedIp
   */
  omit?: Prisma.BannedIpOmit<ExtArgs> | null
  /**
   * Filter, which BannedIp to fetch.
   */
  where: Prisma.BannedIpWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * BannedIp findUniqueOrThrow
 */
export type BannedIpFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedIp
   */
  select?: Prisma.BannedIpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedIp
   */
  omit?: Prisma.BannedIpOmit<ExtArgs> | null
  /**
   * Filter, which BannedIp to fetch.
   */
  where: Prisma.BannedIpWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * BannedIp findFirst
 */
export type BannedIpFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedIp
   */
  select?: Prisma.BannedIpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedIp
   */
  omit?: Prisma.BannedIpOmit<ExtArgs> | null
  /**
   * Filter, which BannedIp to fetch.
   */
  where?: Prisma.BannedIpWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BannedIps to fetch.
   */
  orderBy?: Prisma.BannedIpOrderByWithRelationInput | Prisma.BannedIpOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BannedIps.
   */
  cursor?: Prisma.BannedIpWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BannedIps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BannedIps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BannedIps.
   */
  distinct?: Prisma.BannedIpScalarFieldEnum | Prisma.BannedIpScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * BannedIp findFirstOrThrow
 */
export type BannedIpFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedIp
   */
  select?: Prisma.BannedIpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedIp
   */
  omit?: Prisma.BannedIpOmit<ExtArgs> | null
  /**
   * Filter, which BannedIp to fetch.
   */
  where?: Prisma.BannedIpWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BannedIps to fetch.
   */
  orderBy?: Prisma.BannedIpOrderByWithRelationInput | Prisma.BannedIpOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BannedIps.
   */
  cursor?: Prisma.BannedIpWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BannedIps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BannedIps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BannedIps.
   */
  distinct?: Prisma.BannedIpScalarFieldEnum | Prisma.BannedIpScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * BannedIp findMany
 */
export type BannedIpFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedIp
   */
  select?: Prisma.BannedIpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedIp
   */
  omit?: Prisma.BannedIpOmit<ExtArgs> | null
  /**
   * Filter, which BannedIps to fetch.
   */
  where?: Prisma.BannedIpWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BannedIps to fetch.
   */
  orderBy?: Prisma.BannedIpOrderByWithRelationInput | Prisma.BannedIpOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BannedIps.
   */
  cursor?: Prisma.BannedIpWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BannedIps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BannedIps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BannedIps.
   */
  distinct?: Prisma.BannedIpScalarFieldEnum | Prisma.BannedIpScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * BannedIp create
 */
export type BannedIpCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedIp
   */
  select?: Prisma.BannedIpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedIp
   */
  omit?: Prisma.BannedIpOmit<ExtArgs> | null
  /**
   * The data needed to create a BannedIp.
   */
  data: Prisma.XOR<Prisma.BannedIpCreateInput, Prisma.BannedIpUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * BannedIp createMany
 */
export type BannedIpCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BannedIps.
   */
  data: Prisma.BannedIpCreateManyInput | Prisma.BannedIpCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BannedIp createManyAndReturn
 */
export type BannedIpCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedIp
   */
  select?: Prisma.BannedIpSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BannedIp
   */
  omit?: Prisma.BannedIpOmit<ExtArgs> | null
  /**
   * The data used to create many BannedIps.
   */
  data: Prisma.BannedIpCreateManyInput | Prisma.BannedIpCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BannedIp update
 */
export type BannedIpUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedIp
   */
  select?: Prisma.BannedIpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedIp
   */
  omit?: Prisma.BannedIpOmit<ExtArgs> | null
  /**
   * The data needed to update a BannedIp.
   */
  data: Prisma.XOR<Prisma.BannedIpUpdateInput, Prisma.BannedIpUncheckedUpdateInput>
  /**
   * Choose, which BannedIp to update.
   */
  where: Prisma.BannedIpWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * BannedIp updateMany
 */
export type BannedIpUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BannedIps.
   */
  data: Prisma.XOR<Prisma.BannedIpUpdateManyMutationInput, Prisma.BannedIpUncheckedUpdateManyInput>
  /**
   * Filter which BannedIps to update
   */
  where?: Prisma.BannedIpWhereInput
  /**
   * Limit how many BannedIps to update.
   */
  limit?: number
}

/**
 * BannedIp updateManyAndReturn
 */
export type BannedIpUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedIp
   */
  select?: Prisma.BannedIpSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BannedIp
   */
  omit?: Prisma.BannedIpOmit<ExtArgs> | null
  /**
   * The data used to update BannedIps.
   */
  data: Prisma.XOR<Prisma.BannedIpUpdateManyMutationInput, Prisma.BannedIpUncheckedUpdateManyInput>
  /**
   * Filter which BannedIps to update
   */
  where?: Prisma.BannedIpWhereInput
  /**
   * Limit how many BannedIps to update.
   */
  limit?: number
}

/**
 * BannedIp upsert
 */
export type BannedIpUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedIp
   */
  select?: Prisma.BannedIpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedIp
   */
  omit?: Prisma.BannedIpOmit<ExtArgs> | null
  /**
   * The filter to search for the BannedIp to update in case it exists.
   */
  where: Prisma.BannedIpWhereUniqueInput
  /**
   * In case the BannedIp found by the `where` argument doesn't exist, create a new BannedIp with this data.
   */
  create: Prisma.XOR<Prisma.BannedIpCreateInput, Prisma.BannedIpUncheckedCreateInput>
  /**
   * In case the BannedIp was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BannedIpUpdateInput, Prisma.BannedIpUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * BannedIp delete
 */
export type BannedIpDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedIp
   */
  select?: Prisma.BannedIpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedIp
   */
  omit?: Prisma.BannedIpOmit<ExtArgs> | null
  /**
   * Filter which BannedIp to delete.
   */
  where: Prisma.BannedIpWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * BannedIp deleteMany
 */
export type BannedIpDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BannedIps to delete
   */
  where?: Prisma.BannedIpWhereInput
  /**
   * Limit how many BannedIps to delete.
   */
  limit?: number
}

/**
 * BannedIp without action
 */
export type BannedIpDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedIp
   */
  select?: Prisma.BannedIpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedIp
   */
  omit?: Prisma.BannedIpOmit<ExtArgs> | null
}
