
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Log` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Log
 * 
 */
export type LogModel = runtime.Types.Result.DefaultSelection<Prisma.$LogPayload>

export type AggregateLog = {
  _count: LogCountAggregateOutputType | null
  _avg: LogAvgAggregateOutputType | null
  _sum: LogSumAggregateOutputType | null
  _min: LogMinAggregateOutputType | null
  _max: LogMaxAggregateOutputType | null
}

export type LogAvgAggregateOutputType = {
  level: number | null
  xp: number | null
  gold: number | null
}

export type LogSumAggregateOutputType = {
  level: number | null
  xp: number | null
  gold: number | null
}

export type LogMinAggregateOutputType = {
  id: string | null
  date: Date | null
  currentBruteId: string | null
  type: $Enums.LogType | null
  level: number | null
  brute: string | null
  fightId: string | null
  xp: number | null
  gold: number | null
  template: string | null
  destinyChoiceId: string | null
}

export type LogMaxAggregateOutputType = {
  id: string | null
  date: Date | null
  currentBruteId: string | null
  type: $Enums.LogType | null
  level: number | null
  brute: string | null
  fightId: string | null
  xp: number | null
  gold: number | null
  template: string | null
  destinyChoiceId: string | null
}

export type LogCountAggregateOutputType = {
  id: number
  date: number
  currentBruteId: number
  type: number
  level: number
  brute: number
  fightId: number
  xp: number
  gold: number
  template: number
  destinyChoiceId: number
  _all: number
}


export type LogAvgAggregateInputType = {
  level?: true
  xp?: true
  gold?: true
}

export type LogSumAggregateInputType = {
  level?: true
  xp?: true
  gold?: true
}

export type LogMinAggregateInputType = {
  id?: true
  date?: true
  currentBruteId?: true
  type?: true
  level?: true
  brute?: true
  fightId?: true
  xp?: true
  gold?: true
  template?: true
  destinyChoiceId?: true
}

export type LogMaxAggregateInputType = {
  id?: true
  date?: true
  currentBruteId?: true
  type?: true
  level?: true
  brute?: true
  fightId?: true
  xp?: true
  gold?: true
  template?: true
  destinyChoiceId?: true
}

export type LogCountAggregateInputType = {
  id?: true
  date?: true
  currentBruteId?: true
  type?: true
  level?: true
  brute?: true
  fightId?: true
  xp?: true
  gold?: true
  template?: true
  destinyChoiceId?: true
  _all?: true
}

export type LogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Log to aggregate.
   */
  where?: Prisma.LogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Logs to fetch.
   */
  orderBy?: Prisma.LogOrderByWithRelationInput | Prisma.LogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Logs
  **/
  _count?: true | LogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LogMaxAggregateInputType
}

export type GetLogAggregateType<T extends LogAggregateArgs> = {
      [P in keyof T & keyof AggregateLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLog[P]>
    : Prisma.GetScalarType<T[P], AggregateLog[P]>
}




export type LogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LogWhereInput
  orderBy?: Prisma.LogOrderByWithAggregationInput | Prisma.LogOrderByWithAggregationInput[]
  by: Prisma.LogScalarFieldEnum[] | Prisma.LogScalarFieldEnum
  having?: Prisma.LogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LogCountAggregateInputType | true
  _avg?: LogAvgAggregateInputType
  _sum?: LogSumAggregateInputType
  _min?: LogMinAggregateInputType
  _max?: LogMaxAggregateInputType
}

export type LogGroupByOutputType = {
  id: string
  date: Date
  currentBruteId: string
  type: $Enums.LogType
  level: number | null
  brute: string | null
  fightId: string | null
  xp: number | null
  gold: number | null
  template: string | null
  destinyChoiceId: string | null
  _count: LogCountAggregateOutputType | null
  _avg: LogAvgAggregateOutputType | null
  _sum: LogSumAggregateOutputType | null
  _min: LogMinAggregateOutputType | null
  _max: LogMaxAggregateOutputType | null
}

export type GetLogGroupByPayload<T extends LogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LogGroupByOutputType[P]>
      }
    >
  >



export type LogWhereInput = {
  AND?: Prisma.LogWhereInput | Prisma.LogWhereInput[]
  OR?: Prisma.LogWhereInput[]
  NOT?: Prisma.LogWhereInput | Prisma.LogWhereInput[]
  id?: Prisma.UuidFilter<"Log"> | string
  date?: Prisma.DateTimeFilter<"Log"> | Date | string
  currentBruteId?: Prisma.UuidFilter<"Log"> | string
  type?: Prisma.EnumLogTypeFilter<"Log"> | $Enums.LogType
  level?: Prisma.IntNullableFilter<"Log"> | number | null
  brute?: Prisma.StringNullableFilter<"Log"> | string | null
  fightId?: Prisma.UuidNullableFilter<"Log"> | string | null
  xp?: Prisma.IntNullableFilter<"Log"> | number | null
  gold?: Prisma.IntNullableFilter<"Log"> | number | null
  template?: Prisma.StringNullableFilter<"Log"> | string | null
  destinyChoiceId?: Prisma.UuidNullableFilter<"Log"> | string | null
  currentBrute?: Prisma.XOR<Prisma.BruteScalarRelationFilter, Prisma.BruteWhereInput>
  fight?: Prisma.XOR<Prisma.FightNullableScalarRelationFilter, Prisma.FightWhereInput> | null
  destinyChoice?: Prisma.XOR<Prisma.DestinyChoiceNullableScalarRelationFilter, Prisma.DestinyChoiceWhereInput> | null
}

export type LogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  currentBruteId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  level?: Prisma.SortOrderInput | Prisma.SortOrder
  brute?: Prisma.SortOrderInput | Prisma.SortOrder
  fightId?: Prisma.SortOrderInput | Prisma.SortOrder
  xp?: Prisma.SortOrderInput | Prisma.SortOrder
  gold?: Prisma.SortOrderInput | Prisma.SortOrder
  template?: Prisma.SortOrderInput | Prisma.SortOrder
  destinyChoiceId?: Prisma.SortOrderInput | Prisma.SortOrder
  currentBrute?: Prisma.BruteOrderByWithRelationInput
  fight?: Prisma.FightOrderByWithRelationInput
  destinyChoice?: Prisma.DestinyChoiceOrderByWithRelationInput
}

export type LogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.LogWhereInput | Prisma.LogWhereInput[]
  OR?: Prisma.LogWhereInput[]
  NOT?: Prisma.LogWhereInput | Prisma.LogWhereInput[]
  date?: Prisma.DateTimeFilter<"Log"> | Date | string
  currentBruteId?: Prisma.UuidFilter<"Log"> | string
  type?: Prisma.EnumLogTypeFilter<"Log"> | $Enums.LogType
  level?: Prisma.IntNullableFilter<"Log"> | number | null
  brute?: Prisma.StringNullableFilter<"Log"> | string | null
  fightId?: Prisma.UuidNullableFilter<"Log"> | string | null
  xp?: Prisma.IntNullableFilter<"Log"> | number | null
  gold?: Prisma.IntNullableFilter<"Log"> | number | null
  template?: Prisma.StringNullableFilter<"Log"> | string | null
  destinyChoiceId?: Prisma.UuidNullableFilter<"Log"> | string | null
  currentBrute?: Prisma.XOR<Prisma.BruteScalarRelationFilter, Prisma.BruteWhereInput>
  fight?: Prisma.XOR<Prisma.FightNullableScalarRelationFilter, Prisma.FightWhereInput> | null
  destinyChoice?: Prisma.XOR<Prisma.DestinyChoiceNullableScalarRelationFilter, Prisma.DestinyChoiceWhereInput> | null
}, "id" | "id">

export type LogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  currentBruteId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  level?: Prisma.SortOrderInput | Prisma.SortOrder
  brute?: Prisma.SortOrderInput | Prisma.SortOrder
  fightId?: Prisma.SortOrderInput | Prisma.SortOrder
  xp?: Prisma.SortOrderInput | Prisma.SortOrder
  gold?: Prisma.SortOrderInput | Prisma.SortOrder
  template?: Prisma.SortOrderInput | Prisma.SortOrder
  destinyChoiceId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.LogCountOrderByAggregateInput
  _avg?: Prisma.LogAvgOrderByAggregateInput
  _max?: Prisma.LogMaxOrderByAggregateInput
  _min?: Prisma.LogMinOrderByAggregateInput
  _sum?: Prisma.LogSumOrderByAggregateInput
}

export type LogScalarWhereWithAggregatesInput = {
  AND?: Prisma.LogScalarWhereWithAggregatesInput | Prisma.LogScalarWhereWithAggregatesInput[]
  OR?: Prisma.LogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LogScalarWhereWithAggregatesInput | Prisma.LogScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Log"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"Log"> | Date | string
  currentBruteId?: Prisma.UuidWithAggregatesFilter<"Log"> | string
  type?: Prisma.EnumLogTypeWithAggregatesFilter<"Log"> | $Enums.LogType
  level?: Prisma.IntNullableWithAggregatesFilter<"Log"> | number | null
  brute?: Prisma.StringNullableWithAggregatesFilter<"Log"> | string | null
  fightId?: Prisma.UuidNullableWithAggregatesFilter<"Log"> | string | null
  xp?: Prisma.IntNullableWithAggregatesFilter<"Log"> | number | null
  gold?: Prisma.IntNullableWithAggregatesFilter<"Log"> | number | null
  template?: Prisma.StringNullableWithAggregatesFilter<"Log"> | string | null
  destinyChoiceId?: Prisma.UuidNullableWithAggregatesFilter<"Log"> | string | null
}

export type LogCreateInput = {
  id?: string
  date?: Date | string
  type: $Enums.LogType
  level?: number | null
  brute?: string | null
  xp?: number | null
  gold?: number | null
  template?: string | null
  currentBrute: Prisma.BruteCreateNestedOneWithoutLogsInput
  fight?: Prisma.FightCreateNestedOneWithoutLogsInput
  destinyChoice?: Prisma.DestinyChoiceCreateNestedOneWithoutLogsInput
}

export type LogUncheckedCreateInput = {
  id?: string
  date?: Date | string
  currentBruteId: string
  type: $Enums.LogType
  level?: number | null
  brute?: string | null
  fightId?: string | null
  xp?: number | null
  gold?: number | null
  template?: string | null
  destinyChoiceId?: string | null
}

export type LogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumLogTypeFieldUpdateOperationsInput | $Enums.LogType
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  brute?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  xp?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  gold?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentBrute?: Prisma.BruteUpdateOneRequiredWithoutLogsNestedInput
  fight?: Prisma.FightUpdateOneWithoutLogsNestedInput
  destinyChoice?: Prisma.DestinyChoiceUpdateOneWithoutLogsNestedInput
}

export type LogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  currentBruteId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumLogTypeFieldUpdateOperationsInput | $Enums.LogType
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  brute?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fightId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  xp?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  gold?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  destinyChoiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type LogCreateManyInput = {
  id?: string
  date?: Date | string
  currentBruteId: string
  type: $Enums.LogType
  level?: number | null
  brute?: string | null
  fightId?: string | null
  xp?: number | null
  gold?: number | null
  template?: string | null
  destinyChoiceId?: string | null
}

export type LogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumLogTypeFieldUpdateOperationsInput | $Enums.LogType
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  brute?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  xp?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  gold?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type LogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  currentBruteId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumLogTypeFieldUpdateOperationsInput | $Enums.LogType
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  brute?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fightId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  xp?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  gold?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  destinyChoiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type LogListRelationFilter = {
  every?: Prisma.LogWhereInput
  some?: Prisma.LogWhereInput
  none?: Prisma.LogWhereInput
}

export type LogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  currentBruteId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  level?: Prisma.SortOrder
  brute?: Prisma.SortOrder
  fightId?: Prisma.SortOrder
  xp?: Prisma.SortOrder
  gold?: Prisma.SortOrder
  template?: Prisma.SortOrder
  destinyChoiceId?: Prisma.SortOrder
}

export type LogAvgOrderByAggregateInput = {
  level?: Prisma.SortOrder
  xp?: Prisma.SortOrder
  gold?: Prisma.SortOrder
}

export type LogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  currentBruteId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  level?: Prisma.SortOrder
  brute?: Prisma.SortOrder
  fightId?: Prisma.SortOrder
  xp?: Prisma.SortOrder
  gold?: Prisma.SortOrder
  template?: Prisma.SortOrder
  destinyChoiceId?: Prisma.SortOrder
}

export type LogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  currentBruteId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  level?: Prisma.SortOrder
  brute?: Prisma.SortOrder
  fightId?: Prisma.SortOrder
  xp?: Prisma.SortOrder
  gold?: Prisma.SortOrder
  template?: Prisma.SortOrder
  destinyChoiceId?: Prisma.SortOrder
}

export type LogSumOrderByAggregateInput = {
  level?: Prisma.SortOrder
  xp?: Prisma.SortOrder
  gold?: Prisma.SortOrder
}

export type LogCreateNestedManyWithoutCurrentBruteInput = {
  create?: Prisma.XOR<Prisma.LogCreateWithoutCurrentBruteInput, Prisma.LogUncheckedCreateWithoutCurrentBruteInput> | Prisma.LogCreateWithoutCurrentBruteInput[] | Prisma.LogUncheckedCreateWithoutCurrentBruteInput[]
  connectOrCreate?: Prisma.LogCreateOrConnectWithoutCurrentBruteInput | Prisma.LogCreateOrConnectWithoutCurrentBruteInput[]
  createMany?: Prisma.LogCreateManyCurrentBruteInputEnvelope
  connect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
}

export type LogUncheckedCreateNestedManyWithoutCurrentBruteInput = {
  create?: Prisma.XOR<Prisma.LogCreateWithoutCurrentBruteInput, Prisma.LogUncheckedCreateWithoutCurrentBruteInput> | Prisma.LogCreateWithoutCurrentBruteInput[] | Prisma.LogUncheckedCreateWithoutCurrentBruteInput[]
  connectOrCreate?: Prisma.LogCreateOrConnectWithoutCurrentBruteInput | Prisma.LogCreateOrConnectWithoutCurrentBruteInput[]
  createMany?: Prisma.LogCreateManyCurrentBruteInputEnvelope
  connect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
}

export type LogUpdateManyWithoutCurrentBruteNestedInput = {
  create?: Prisma.XOR<Prisma.LogCreateWithoutCurrentBruteInput, Prisma.LogUncheckedCreateWithoutCurrentBruteInput> | Prisma.LogCreateWithoutCurrentBruteInput[] | Prisma.LogUncheckedCreateWithoutCurrentBruteInput[]
  connectOrCreate?: Prisma.LogCreateOrConnectWithoutCurrentBruteInput | Prisma.LogCreateOrConnectWithoutCurrentBruteInput[]
  upsert?: Prisma.LogUpsertWithWhereUniqueWithoutCurrentBruteInput | Prisma.LogUpsertWithWhereUniqueWithoutCurrentBruteInput[]
  createMany?: Prisma.LogCreateManyCurrentBruteInputEnvelope
  set?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  disconnect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  delete?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  connect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  update?: Prisma.LogUpdateWithWhereUniqueWithoutCurrentBruteInput | Prisma.LogUpdateWithWhereUniqueWithoutCurrentBruteInput[]
  updateMany?: Prisma.LogUpdateManyWithWhereWithoutCurrentBruteInput | Prisma.LogUpdateManyWithWhereWithoutCurrentBruteInput[]
  deleteMany?: Prisma.LogScalarWhereInput | Prisma.LogScalarWhereInput[]
}

export type LogUncheckedUpdateManyWithoutCurrentBruteNestedInput = {
  create?: Prisma.XOR<Prisma.LogCreateWithoutCurrentBruteInput, Prisma.LogUncheckedCreateWithoutCurrentBruteInput> | Prisma.LogCreateWithoutCurrentBruteInput[] | Prisma.LogUncheckedCreateWithoutCurrentBruteInput[]
  connectOrCreate?: Prisma.LogCreateOrConnectWithoutCurrentBruteInput | Prisma.LogCreateOrConnectWithoutCurrentBruteInput[]
  upsert?: Prisma.LogUpsertWithWhereUniqueWithoutCurrentBruteInput | Prisma.LogUpsertWithWhereUniqueWithoutCurrentBruteInput[]
  createMany?: Prisma.LogCreateManyCurrentBruteInputEnvelope
  set?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  disconnect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  delete?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  connect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  update?: Prisma.LogUpdateWithWhereUniqueWithoutCurrentBruteInput | Prisma.LogUpdateWithWhereUniqueWithoutCurrentBruteInput[]
  updateMany?: Prisma.LogUpdateManyWithWhereWithoutCurrentBruteInput | Prisma.LogUpdateManyWithWhereWithoutCurrentBruteInput[]
  deleteMany?: Prisma.LogScalarWhereInput | Prisma.LogScalarWhereInput[]
}

export type LogCreateNestedManyWithoutFightInput = {
  create?: Prisma.XOR<Prisma.LogCreateWithoutFightInput, Prisma.LogUncheckedCreateWithoutFightInput> | Prisma.LogCreateWithoutFightInput[] | Prisma.LogUncheckedCreateWithoutFightInput[]
  connectOrCreate?: Prisma.LogCreateOrConnectWithoutFightInput | Prisma.LogCreateOrConnectWithoutFightInput[]
  createMany?: Prisma.LogCreateManyFightInputEnvelope
  connect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
}

export type LogUncheckedCreateNestedManyWithoutFightInput = {
  create?: Prisma.XOR<Prisma.LogCreateWithoutFightInput, Prisma.LogUncheckedCreateWithoutFightInput> | Prisma.LogCreateWithoutFightInput[] | Prisma.LogUncheckedCreateWithoutFightInput[]
  connectOrCreate?: Prisma.LogCreateOrConnectWithoutFightInput | Prisma.LogCreateOrConnectWithoutFightInput[]
  createMany?: Prisma.LogCreateManyFightInputEnvelope
  connect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
}

export type LogUpdateManyWithoutFightNestedInput = {
  create?: Prisma.XOR<Prisma.LogCreateWithoutFightInput, Prisma.LogUncheckedCreateWithoutFightInput> | Prisma.LogCreateWithoutFightInput[] | Prisma.LogUncheckedCreateWithoutFightInput[]
  connectOrCreate?: Prisma.LogCreateOrConnectWithoutFightInput | Prisma.LogCreateOrConnectWithoutFightInput[]
  upsert?: Prisma.LogUpsertWithWhereUniqueWithoutFightInput | Prisma.LogUpsertWithWhereUniqueWithoutFightInput[]
  createMany?: Prisma.LogCreateManyFightInputEnvelope
  set?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  disconnect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  delete?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  connect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  update?: Prisma.LogUpdateWithWhereUniqueWithoutFightInput | Prisma.LogUpdateWithWhereUniqueWithoutFightInput[]
  updateMany?: Prisma.LogUpdateManyWithWhereWithoutFightInput | Prisma.LogUpdateManyWithWhereWithoutFightInput[]
  deleteMany?: Prisma.LogScalarWhereInput | Prisma.LogScalarWhereInput[]
}

export type LogUncheckedUpdateManyWithoutFightNestedInput = {
  create?: Prisma.XOR<Prisma.LogCreateWithoutFightInput, Prisma.LogUncheckedCreateWithoutFightInput> | Prisma.LogCreateWithoutFightInput[] | Prisma.LogUncheckedCreateWithoutFightInput[]
  connectOrCreate?: Prisma.LogCreateOrConnectWithoutFightInput | Prisma.LogCreateOrConnectWithoutFightInput[]
  upsert?: Prisma.LogUpsertWithWhereUniqueWithoutFightInput | Prisma.LogUpsertWithWhereUniqueWithoutFightInput[]
  createMany?: Prisma.LogCreateManyFightInputEnvelope
  set?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  disconnect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  delete?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  connect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  update?: Prisma.LogUpdateWithWhereUniqueWithoutFightInput | Prisma.LogUpdateWithWhereUniqueWithoutFightInput[]
  updateMany?: Prisma.LogUpdateManyWithWhereWithoutFightInput | Prisma.LogUpdateManyWithWhereWithoutFightInput[]
  deleteMany?: Prisma.LogScalarWhereInput | Prisma.LogScalarWhereInput[]
}

export type EnumLogTypeFieldUpdateOperationsInput = {
  set?: $Enums.LogType
}

export type LogCreateNestedManyWithoutDestinyChoiceInput = {
  create?: Prisma.XOR<Prisma.LogCreateWithoutDestinyChoiceInput, Prisma.LogUncheckedCreateWithoutDestinyChoiceInput> | Prisma.LogCreateWithoutDestinyChoiceInput[] | Prisma.LogUncheckedCreateWithoutDestinyChoiceInput[]
  connectOrCreate?: Prisma.LogCreateOrConnectWithoutDestinyChoiceInput | Prisma.LogCreateOrConnectWithoutDestinyChoiceInput[]
  createMany?: Prisma.LogCreateManyDestinyChoiceInputEnvelope
  connect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
}

export type LogUncheckedCreateNestedManyWithoutDestinyChoiceInput = {
  create?: Prisma.XOR<Prisma.LogCreateWithoutDestinyChoiceInput, Prisma.LogUncheckedCreateWithoutDestinyChoiceInput> | Prisma.LogCreateWithoutDestinyChoiceInput[] | Prisma.LogUncheckedCreateWithoutDestinyChoiceInput[]
  connectOrCreate?: Prisma.LogCreateOrConnectWithoutDestinyChoiceInput | Prisma.LogCreateOrConnectWithoutDestinyChoiceInput[]
  createMany?: Prisma.LogCreateManyDestinyChoiceInputEnvelope
  connect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
}

export type LogUpdateManyWithoutDestinyChoiceNestedInput = {
  create?: Prisma.XOR<Prisma.LogCreateWithoutDestinyChoiceInput, Prisma.LogUncheckedCreateWithoutDestinyChoiceInput> | Prisma.LogCreateWithoutDestinyChoiceInput[] | Prisma.LogUncheckedCreateWithoutDestinyChoiceInput[]
  connectOrCreate?: Prisma.LogCreateOrConnectWithoutDestinyChoiceInput | Prisma.LogCreateOrConnectWithoutDestinyChoiceInput[]
  upsert?: Prisma.LogUpsertWithWhereUniqueWithoutDestinyChoiceInput | Prisma.LogUpsertWithWhereUniqueWithoutDestinyChoiceInput[]
  createMany?: Prisma.LogCreateManyDestinyChoiceInputEnvelope
  set?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  disconnect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  delete?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  connect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  update?: Prisma.LogUpdateWithWhereUniqueWithoutDestinyChoiceInput | Prisma.LogUpdateWithWhereUniqueWithoutDestinyChoiceInput[]
  updateMany?: Prisma.LogUpdateManyWithWhereWithoutDestinyChoiceInput | Prisma.LogUpdateManyWithWhereWithoutDestinyChoiceInput[]
  deleteMany?: Prisma.LogScalarWhereInput | Prisma.LogScalarWhereInput[]
}

export type LogUncheckedUpdateManyWithoutDestinyChoiceNestedInput = {
  create?: Prisma.XOR<Prisma.LogCreateWithoutDestinyChoiceInput, Prisma.LogUncheckedCreateWithoutDestinyChoiceInput> | Prisma.LogCreateWithoutDestinyChoiceInput[] | Prisma.LogUncheckedCreateWithoutDestinyChoiceInput[]
  connectOrCreate?: Prisma.LogCreateOrConnectWithoutDestinyChoiceInput | Prisma.LogCreateOrConnectWithoutDestinyChoiceInput[]
  upsert?: Prisma.LogUpsertWithWhereUniqueWithoutDestinyChoiceInput | Prisma.LogUpsertWithWhereUniqueWithoutDestinyChoiceInput[]
  createMany?: Prisma.LogCreateManyDestinyChoiceInputEnvelope
  set?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  disconnect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  delete?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  connect?: Prisma.LogWhereUniqueInput | Prisma.LogWhereUniqueInput[]
  update?: Prisma.LogUpdateWithWhereUniqueWithoutDestinyChoiceInput | Prisma.LogUpdateWithWhereUniqueWithoutDestinyChoiceInput[]
  updateMany?: Prisma.LogUpdateManyWithWhereWithoutDestinyChoiceInput | Prisma.LogUpdateManyWithWhereWithoutDestinyChoiceInput[]
  deleteMany?: Prisma.LogScalarWhereInput | Prisma.LogScalarWhereInput[]
}

export type LogCreateWithoutCurrentBruteInput = {
  id?: string
  date?: Date | string
  type: $Enums.LogType
  level?: number | null
  brute?: string | null
  xp?: number | null
  gold?: number | null
  template?: string | null
  fight?: Prisma.FightCreateNestedOneWithoutLogsInput
  destinyChoice?: Prisma.DestinyChoiceCreateNestedOneWithoutLogsInput
}

export type LogUncheckedCreateWithoutCurrentBruteInput = {
  id?: string
  date?: Date | string
  type: $Enums.LogType
  level?: number | null
  brute?: string | null
  fightId?: string | null
  xp?: number | null
  gold?: number | null
  template?: string | null
  destinyChoiceId?: string | null
}

export type LogCreateOrConnectWithoutCurrentBruteInput = {
  where: Prisma.LogWhereUniqueInput
  create: Prisma.XOR<Prisma.LogCreateWithoutCurrentBruteInput, Prisma.LogUncheckedCreateWithoutCurrentBruteInput>
}

export type LogCreateManyCurrentBruteInputEnvelope = {
  data: Prisma.LogCreateManyCurrentBruteInput | Prisma.LogCreateManyCurrentBruteInput[]
  skipDuplicates?: boolean
}

export type LogUpsertWithWhereUniqueWithoutCurrentBruteInput = {
  where: Prisma.LogWhereUniqueInput
  update: Prisma.XOR<Prisma.LogUpdateWithoutCurrentBruteInput, Prisma.LogUncheckedUpdateWithoutCurrentBruteInput>
  create: Prisma.XOR<Prisma.LogCreateWithoutCurrentBruteInput, Prisma.LogUncheckedCreateWithoutCurrentBruteInput>
}

export type LogUpdateWithWhereUniqueWithoutCurrentBruteInput = {
  where: Prisma.LogWhereUniqueInput
  data: Prisma.XOR<Prisma.LogUpdateWithoutCurrentBruteInput, Prisma.LogUncheckedUpdateWithoutCurrentBruteInput>
}

export type LogUpdateManyWithWhereWithoutCurrentBruteInput = {
  where: Prisma.LogScalarWhereInput
  data: Prisma.XOR<Prisma.LogUpdateManyMutationInput, Prisma.LogUncheckedUpdateManyWithoutCurrentBruteInput>
}

export type LogScalarWhereInput = {
  AND?: Prisma.LogScalarWhereInput | Prisma.LogScalarWhereInput[]
  OR?: Prisma.LogScalarWhereInput[]
  NOT?: Prisma.LogScalarWhereInput | Prisma.LogScalarWhereInput[]
  id?: Prisma.UuidFilter<"Log"> | string
  date?: Prisma.DateTimeFilter<"Log"> | Date | string
  currentBruteId?: Prisma.UuidFilter<"Log"> | string
  type?: Prisma.EnumLogTypeFilter<"Log"> | $Enums.LogType
  level?: Prisma.IntNullableFilter<"Log"> | number | null
  brute?: Prisma.StringNullableFilter<"Log"> | string | null
  fightId?: Prisma.UuidNullableFilter<"Log"> | string | null
  xp?: Prisma.IntNullableFilter<"Log"> | number | null
  gold?: Prisma.IntNullableFilter<"Log"> | number | null
  template?: Prisma.StringNullableFilter<"Log"> | string | null
  destinyChoiceId?: Prisma.UuidNullableFilter<"Log"> | string | null
}

export type LogCreateWithoutFightInput = {
  id?: string
  date?: Date | string
  type: $Enums.LogType
  level?: number | null
  brute?: string | null
  xp?: number | null
  gold?: number | null
  template?: string | null
  currentBrute: Prisma.BruteCreateNestedOneWithoutLogsInput
  destinyChoice?: Prisma.DestinyChoiceCreateNestedOneWithoutLogsInput
}

export type LogUncheckedCreateWithoutFightInput = {
  id?: string
  date?: Date | string
  currentBruteId: string
  type: $Enums.LogType
  level?: number | null
  brute?: string | null
  xp?: number | null
  gold?: number | null
  template?: string | null
  destinyChoiceId?: string | null
}

export type LogCreateOrConnectWithoutFightInput = {
  where: Prisma.LogWhereUniqueInput
  create: Prisma.XOR<Prisma.LogCreateWithoutFightInput, Prisma.LogUncheckedCreateWithoutFightInput>
}

export type LogCreateManyFightInputEnvelope = {
  data: Prisma.LogCreateManyFightInput | Prisma.LogCreateManyFightInput[]
  skipDuplicates?: boolean
}

export type LogUpsertWithWhereUniqueWithoutFightInput = {
  where: Prisma.LogWhereUniqueInput
  update: Prisma.XOR<Prisma.LogUpdateWithoutFightInput, Prisma.LogUncheckedUpdateWithoutFightInput>
  create: Prisma.XOR<Prisma.LogCreateWithoutFightInput, Prisma.LogUncheckedCreateWithoutFightInput>
}

export type LogUpdateWithWhereUniqueWithoutFightInput = {
  where: Prisma.LogWhereUniqueInput
  data: Prisma.XOR<Prisma.LogUpdateWithoutFightInput, Prisma.LogUncheckedUpdateWithoutFightInput>
}

export type LogUpdateManyWithWhereWithoutFightInput = {
  where: Prisma.LogScalarWhereInput
  data: Prisma.XOR<Prisma.LogUpdateManyMutationInput, Prisma.LogUncheckedUpdateManyWithoutFightInput>
}

export type LogCreateWithoutDestinyChoiceInput = {
  id?: string
  date?: Date | string
  type: $Enums.LogType
  level?: number | null
  brute?: string | null
  xp?: number | null
  gold?: number | null
  template?: string | null
  currentBrute: Prisma.BruteCreateNestedOneWithoutLogsInput
  fight?: Prisma.FightCreateNestedOneWithoutLogsInput
}

export type LogUncheckedCreateWithoutDestinyChoiceInput = {
  id?: string
  date?: Date | string
  currentBruteId: string
  type: $Enums.LogType
  level?: number | null
  brute?: string | null
  fightId?: string | null
  xp?: number | null
  gold?: number | null
  template?: string | null
}

export type LogCreateOrConnectWithoutDestinyChoiceInput = {
  where: Prisma.LogWhereUniqueInput
  create: Prisma.XOR<Prisma.LogCreateWithoutDestinyChoiceInput, Prisma.LogUncheckedCreateWithoutDestinyChoiceInput>
}

export type LogCreateManyDestinyChoiceInputEnvelope = {
  data: Prisma.LogCreateManyDestinyChoiceInput | Prisma.LogCreateManyDestinyChoiceInput[]
  skipDuplicates?: boolean
}

export type LogUpsertWithWhereUniqueWithoutDestinyChoiceInput = {
  where: Prisma.LogWhereUniqueInput
  update: Prisma.XOR<Prisma.LogUpdateWithoutDestinyChoiceInput, Prisma.LogUncheckedUpdateWithoutDestinyChoiceInput>
  create: Prisma.XOR<Prisma.LogCreateWithoutDestinyChoiceInput, Prisma.LogUncheckedCreateWithoutDestinyChoiceInput>
}

export type LogUpdateWithWhereUniqueWithoutDestinyChoiceInput = {
  where: Prisma.LogWhereUniqueInput
  data: Prisma.XOR<Prisma.LogUpdateWithoutDestinyChoiceInput, Prisma.LogUncheckedUpdateWithoutDestinyChoiceInput>
}

export type LogUpdateManyWithWhereWithoutDestinyChoiceInput = {
  where: Prisma.LogScalarWhereInput
  data: Prisma.XOR<Prisma.LogUpdateManyMutationInput, Prisma.LogUncheckedUpdateManyWithoutDestinyChoiceInput>
}

export type LogCreateManyCurrentBruteInput = {
  id?: string
  date?: Date | string
  type: $Enums.LogType
  level?: number | null
  brute?: string | null
  fightId?: string | null
  xp?: number | null
  gold?: number | null
  template?: string | null
  destinyChoiceId?: string | null
}

export type LogUpdateWithoutCurrentBruteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumLogTypeFieldUpdateOperationsInput | $Enums.LogType
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  brute?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  xp?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  gold?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fight?: Prisma.FightUpdateOneWithoutLogsNestedInput
  destinyChoice?: Prisma.DestinyChoiceUpdateOneWithoutLogsNestedInput
}

export type LogUncheckedUpdateWithoutCurrentBruteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumLogTypeFieldUpdateOperationsInput | $Enums.LogType
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  brute?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fightId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  xp?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  gold?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  destinyChoiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type LogUncheckedUpdateManyWithoutCurrentBruteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumLogTypeFieldUpdateOperationsInput | $Enums.LogType
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  brute?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fightId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  xp?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  gold?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  destinyChoiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type LogCreateManyFightInput = {
  id?: string
  date?: Date | string
  currentBruteId: string
  type: $Enums.LogType
  level?: number | null
  brute?: string | null
  xp?: number | null
  gold?: number | null
  template?: string | null
  destinyChoiceId?: string | null
}

export type LogUpdateWithoutFightInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumLogTypeFieldUpdateOperationsInput | $Enums.LogType
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  brute?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  xp?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  gold?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentBrute?: Prisma.BruteUpdateOneRequiredWithoutLogsNestedInput
  destinyChoice?: Prisma.DestinyChoiceUpdateOneWithoutLogsNestedInput
}

export type LogUncheckedUpdateWithoutFightInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  currentBruteId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumLogTypeFieldUpdateOperationsInput | $Enums.LogType
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  brute?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  xp?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  gold?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  destinyChoiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type LogUncheckedUpdateManyWithoutFightInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  currentBruteId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumLogTypeFieldUpdateOperationsInput | $Enums.LogType
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  brute?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  xp?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  gold?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  destinyChoiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type LogCreateManyDestinyChoiceInput = {
  id?: string
  date?: Date | string
  currentBruteId: string
  type: $Enums.LogType
  level?: number | null
  brute?: string | null
  fightId?: string | null
  xp?: number | null
  gold?: number | null
  template?: string | null
}

export type LogUpdateWithoutDestinyChoiceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.EnumLogTypeFieldUpdateOperationsInput | $Enums.LogType
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  brute?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  xp?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  gold?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentBrute?: Prisma.BruteUpdateOneRequiredWithoutLogsNestedInput
  fight?: Prisma.FightUpdateOneWithoutLogsNestedInput
}

export type LogUncheckedUpdateWithoutDestinyChoiceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  currentBruteId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumLogTypeFieldUpdateOperationsInput | $Enums.LogType
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  brute?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fightId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  xp?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  gold?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type LogUncheckedUpdateManyWithoutDestinyChoiceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  currentBruteId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumLogTypeFieldUpdateOperationsInput | $Enums.LogType
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  brute?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fightId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  xp?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  gold?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type LogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  currentBruteId?: boolean
  type?: boolean
  level?: boolean
  brute?: boolean
  fightId?: boolean
  xp?: boolean
  gold?: boolean
  template?: boolean
  destinyChoiceId?: boolean
  currentBrute?: boolean | Prisma.BruteDefaultArgs<ExtArgs>
  fight?: boolean | Prisma.Log$fightArgs<ExtArgs>
  destinyChoice?: boolean | Prisma.Log$destinyChoiceArgs<ExtArgs>
}, ExtArgs["result"]["log"]>

export type LogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  currentBruteId?: boolean
  type?: boolean
  level?: boolean
  brute?: boolean
  fightId?: boolean
  xp?: boolean
  gold?: boolean
  template?: boolean
  destinyChoiceId?: boolean
  currentBrute?: boolean | Prisma.BruteDefaultArgs<ExtArgs>
  fight?: boolean | Prisma.Log$fightArgs<ExtArgs>
  destinyChoice?: boolean | Prisma.Log$destinyChoiceArgs<ExtArgs>
}, ExtArgs["result"]["log"]>

export type LogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  currentBruteId?: boolean
  type?: boolean
  level?: boolean
  brute?: boolean
  fightId?: boolean
  xp?: boolean
  gold?: boolean
  template?: boolean
  destinyChoiceId?: boolean
  currentBrute?: boolean | Prisma.BruteDefaultArgs<ExtArgs>
  fight?: boolean | Prisma.Log$fightArgs<ExtArgs>
  destinyChoice?: boolean | Prisma.Log$destinyChoiceArgs<ExtArgs>
}, ExtArgs["result"]["log"]>

export type LogSelectScalar = {
  id?: boolean
  date?: boolean
  currentBruteId?: boolean
  type?: boolean
  level?: boolean
  brute?: boolean
  fightId?: boolean
  xp?: boolean
  gold?: boolean
  template?: boolean
  destinyChoiceId?: boolean
}

export type LogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "currentBruteId" | "type" | "level" | "brute" | "fightId" | "xp" | "gold" | "template" | "destinyChoiceId", ExtArgs["result"]["log"]>
export type LogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  currentBrute?: boolean | Prisma.BruteDefaultArgs<ExtArgs>
  fight?: boolean | Prisma.Log$fightArgs<ExtArgs>
  destinyChoice?: boolean | Prisma.Log$destinyChoiceArgs<ExtArgs>
}
export type LogIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  currentBrute?: boolean | Prisma.BruteDefaultArgs<ExtArgs>
  fight?: boolean | Prisma.Log$fightArgs<ExtArgs>
  destinyChoice?: boolean | Prisma.Log$destinyChoiceArgs<ExtArgs>
}
export type LogIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  currentBrute?: boolean | Prisma.BruteDefaultArgs<ExtArgs>
  fight?: boolean | Prisma.Log$fightArgs<ExtArgs>
  destinyChoice?: boolean | Prisma.Log$destinyChoiceArgs<ExtArgs>
}

export type $LogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Log"
  objects: {
    currentBrute: Prisma.$BrutePayload<ExtArgs>
    fight: Prisma.$FightPayload<ExtArgs> | null
    destinyChoice: Prisma.$DestinyChoicePayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    date: Date
    currentBruteId: string
    type: $Enums.LogType
    level: number | null
    brute: string | null
    fightId: string | null
    xp: number | null
    gold: number | null
    template: string | null
    destinyChoiceId: string | null
  }, ExtArgs["result"]["log"]>
  composites: {}
}

export type LogGetPayload<S extends boolean | null | undefined | LogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LogPayload, S>

export type LogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: LogCountAggregateInputType | true
  }

export interface LogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Log'], meta: { name: 'Log' } }
  /**
   * Find zero or one Log that matches the filter.
   * @param {LogFindUniqueArgs} args - Arguments to find a Log
   * @example
   * // Get one Log
   * const log = await prisma.log.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LogFindUniqueArgs>(args: Prisma.SelectSubset<T, LogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LogClient<runtime.Types.Result.GetResult<Prisma.$LogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Log that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LogFindUniqueOrThrowArgs} args - Arguments to find a Log
   * @example
   * // Get one Log
   * const log = await prisma.log.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LogClient<runtime.Types.Result.GetResult<Prisma.$LogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Log that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogFindFirstArgs} args - Arguments to find a Log
   * @example
   * // Get one Log
   * const log = await prisma.log.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LogFindFirstArgs>(args?: Prisma.SelectSubset<T, LogFindFirstArgs<ExtArgs>>): Prisma.Prisma__LogClient<runtime.Types.Result.GetResult<Prisma.$LogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Log that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogFindFirstOrThrowArgs} args - Arguments to find a Log
   * @example
   * // Get one Log
   * const log = await prisma.log.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LogClient<runtime.Types.Result.GetResult<Prisma.$LogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Logs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Logs
   * const logs = await prisma.log.findMany()
   * 
   * // Get first 10 Logs
   * const logs = await prisma.log.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const logWithIdOnly = await prisma.log.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LogFindManyArgs>(args?: Prisma.SelectSubset<T, LogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Log.
   * @param {LogCreateArgs} args - Arguments to create a Log.
   * @example
   * // Create one Log
   * const Log = await prisma.log.create({
   *   data: {
   *     // ... data to create a Log
   *   }
   * })
   * 
   */
  create<T extends LogCreateArgs>(args: Prisma.SelectSubset<T, LogCreateArgs<ExtArgs>>): Prisma.Prisma__LogClient<runtime.Types.Result.GetResult<Prisma.$LogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Logs.
   * @param {LogCreateManyArgs} args - Arguments to create many Logs.
   * @example
   * // Create many Logs
   * const log = await prisma.log.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LogCreateManyArgs>(args?: Prisma.SelectSubset<T, LogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Logs and returns the data saved in the database.
   * @param {LogCreateManyAndReturnArgs} args - Arguments to create many Logs.
   * @example
   * // Create many Logs
   * const log = await prisma.log.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Logs and only return the `id`
   * const logWithIdOnly = await prisma.log.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Log.
   * @param {LogDeleteArgs} args - Arguments to delete one Log.
   * @example
   * // Delete one Log
   * const Log = await prisma.log.delete({
   *   where: {
   *     // ... filter to delete one Log
   *   }
   * })
   * 
   */
  delete<T extends LogDeleteArgs>(args: Prisma.SelectSubset<T, LogDeleteArgs<ExtArgs>>): Prisma.Prisma__LogClient<runtime.Types.Result.GetResult<Prisma.$LogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Log.
   * @param {LogUpdateArgs} args - Arguments to update one Log.
   * @example
   * // Update one Log
   * const log = await prisma.log.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LogUpdateArgs>(args: Prisma.SelectSubset<T, LogUpdateArgs<ExtArgs>>): Prisma.Prisma__LogClient<runtime.Types.Result.GetResult<Prisma.$LogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Logs.
   * @param {LogDeleteManyArgs} args - Arguments to filter Logs to delete.
   * @example
   * // Delete a few Logs
   * const { count } = await prisma.log.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LogDeleteManyArgs>(args?: Prisma.SelectSubset<T, LogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Logs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Logs
   * const log = await prisma.log.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LogUpdateManyArgs>(args: Prisma.SelectSubset<T, LogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Logs and returns the data updated in the database.
   * @param {LogUpdateManyAndReturnArgs} args - Arguments to update many Logs.
   * @example
   * // Update many Logs
   * const log = await prisma.log.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Logs and only return the `id`
   * const logWithIdOnly = await prisma.log.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Log.
   * @param {LogUpsertArgs} args - Arguments to update or create a Log.
   * @example
   * // Update or create a Log
   * const log = await prisma.log.upsert({
   *   create: {
   *     // ... data to create a Log
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Log we want to update
   *   }
   * })
   */
  upsert<T extends LogUpsertArgs>(args: Prisma.SelectSubset<T, LogUpsertArgs<ExtArgs>>): Prisma.Prisma__LogClient<runtime.Types.Result.GetResult<Prisma.$LogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Logs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogCountArgs} args - Arguments to filter Logs to count.
   * @example
   * // Count the number of Logs
   * const count = await prisma.log.count({
   *   where: {
   *     // ... the filter for the Logs we want to count
   *   }
   * })
  **/
  count<T extends LogCountArgs>(
    args?: Prisma.Subset<T, LogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Log.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LogAggregateArgs>(args: Prisma.Subset<T, LogAggregateArgs>): Prisma.PrismaPromise<GetLogAggregateType<T>>

  /**
   * Group by Log.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LogGroupByArgs['orderBy'] }
      : { orderBy?: LogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Log model
 */
readonly fields: LogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Log.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  currentBrute<T extends Prisma.BruteDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BruteDefaultArgs<ExtArgs>>): Prisma.Prisma__BruteClient<runtime.Types.Result.GetResult<Prisma.$BrutePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  fight<T extends Prisma.Log$fightArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Log$fightArgs<ExtArgs>>): Prisma.Prisma__FightClient<runtime.Types.Result.GetResult<Prisma.$FightPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  destinyChoice<T extends Prisma.Log$destinyChoiceArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Log$destinyChoiceArgs<ExtArgs>>): Prisma.Prisma__DestinyChoiceClient<runtime.Types.Result.GetResult<Prisma.$DestinyChoicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Log model
 */
export interface LogFieldRefs {
  readonly id: Prisma.FieldRef<"Log", 'String'>
  readonly date: Prisma.FieldRef<"Log", 'DateTime'>
  readonly currentBruteId: Prisma.FieldRef<"Log", 'String'>
  readonly type: Prisma.FieldRef<"Log", 'LogType'>
  readonly level: Prisma.FieldRef<"Log", 'Int'>
  readonly brute: Prisma.FieldRef<"Log", 'String'>
  readonly fightId: Prisma.FieldRef<"Log", 'String'>
  readonly xp: Prisma.FieldRef<"Log", 'Int'>
  readonly gold: Prisma.FieldRef<"Log", 'Int'>
  readonly template: Prisma.FieldRef<"Log", 'String'>
  readonly destinyChoiceId: Prisma.FieldRef<"Log", 'String'>
}
    

// Custom InputTypes
/**
 * Log findUnique
 */
export type LogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Log
   */
  select?: Prisma.LogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Log
   */
  omit?: Prisma.LogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogInclude<ExtArgs> | null
  /**
   * Filter, which Log to fetch.
   */
  where: Prisma.LogWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Log findUniqueOrThrow
 */
export type LogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Log
   */
  select?: Prisma.LogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Log
   */
  omit?: Prisma.LogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogInclude<ExtArgs> | null
  /**
   * Filter, which Log to fetch.
   */
  where: Prisma.LogWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Log findFirst
 */
export type LogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Log
   */
  select?: Prisma.LogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Log
   */
  omit?: Prisma.LogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogInclude<ExtArgs> | null
  /**
   * Filter, which Log to fetch.
   */
  where?: Prisma.LogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Logs to fetch.
   */
  orderBy?: Prisma.LogOrderByWithRelationInput | Prisma.LogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Logs.
   */
  cursor?: Prisma.LogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Logs.
   */
  distinct?: Prisma.LogScalarFieldEnum | Prisma.LogScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Log findFirstOrThrow
 */
export type LogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Log
   */
  select?: Prisma.LogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Log
   */
  omit?: Prisma.LogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogInclude<ExtArgs> | null
  /**
   * Filter, which Log to fetch.
   */
  where?: Prisma.LogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Logs to fetch.
   */
  orderBy?: Prisma.LogOrderByWithRelationInput | Prisma.LogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Logs.
   */
  cursor?: Prisma.LogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Logs.
   */
  distinct?: Prisma.LogScalarFieldEnum | Prisma.LogScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Log findMany
 */
export type LogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Log
   */
  select?: Prisma.LogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Log
   */
  omit?: Prisma.LogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogInclude<ExtArgs> | null
  /**
   * Filter, which Logs to fetch.
   */
  where?: Prisma.LogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Logs to fetch.
   */
  orderBy?: Prisma.LogOrderByWithRelationInput | Prisma.LogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Logs.
   */
  cursor?: Prisma.LogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Logs.
   */
  distinct?: Prisma.LogScalarFieldEnum | Prisma.LogScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Log create
 */
export type LogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Log
   */
  select?: Prisma.LogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Log
   */
  omit?: Prisma.LogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogInclude<ExtArgs> | null
  /**
   * The data needed to create a Log.
   */
  data: Prisma.XOR<Prisma.LogCreateInput, Prisma.LogUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Log createMany
 */
export type LogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Logs.
   */
  data: Prisma.LogCreateManyInput | Prisma.LogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Log createManyAndReturn
 */
export type LogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Log
   */
  select?: Prisma.LogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Log
   */
  omit?: Prisma.LogOmit<ExtArgs> | null
  /**
   * The data used to create many Logs.
   */
  data: Prisma.LogCreateManyInput | Prisma.LogCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Log update
 */
export type LogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Log
   */
  select?: Prisma.LogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Log
   */
  omit?: Prisma.LogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogInclude<ExtArgs> | null
  /**
   * The data needed to update a Log.
   */
  data: Prisma.XOR<Prisma.LogUpdateInput, Prisma.LogUncheckedUpdateInput>
  /**
   * Choose, which Log to update.
   */
  where: Prisma.LogWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Log updateMany
 */
export type LogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Logs.
   */
  data: Prisma.XOR<Prisma.LogUpdateManyMutationInput, Prisma.LogUncheckedUpdateManyInput>
  /**
   * Filter which Logs to update
   */
  where?: Prisma.LogWhereInput
  /**
   * Limit how many Logs to update.
   */
  limit?: number
}

/**
 * Log updateManyAndReturn
 */
export type LogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Log
   */
  select?: Prisma.LogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Log
   */
  omit?: Prisma.LogOmit<ExtArgs> | null
  /**
   * The data used to update Logs.
   */
  data: Prisma.XOR<Prisma.LogUpdateManyMutationInput, Prisma.LogUncheckedUpdateManyInput>
  /**
   * Filter which Logs to update
   */
  where?: Prisma.LogWhereInput
  /**
   * Limit how many Logs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Log upsert
 */
export type LogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Log
   */
  select?: Prisma.LogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Log
   */
  omit?: Prisma.LogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogInclude<ExtArgs> | null
  /**
   * The filter to search for the Log to update in case it exists.
   */
  where: Prisma.LogWhereUniqueInput
  /**
   * In case the Log found by the `where` argument doesn't exist, create a new Log with this data.
   */
  create: Prisma.XOR<Prisma.LogCreateInput, Prisma.LogUncheckedCreateInput>
  /**
   * In case the Log was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LogUpdateInput, Prisma.LogUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Log delete
 */
export type LogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Log
   */
  select?: Prisma.LogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Log
   */
  omit?: Prisma.LogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogInclude<ExtArgs> | null
  /**
   * Filter which Log to delete.
   */
  where: Prisma.LogWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Log deleteMany
 */
export type LogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Logs to delete
   */
  where?: Prisma.LogWhereInput
  /**
   * Limit how many Logs to delete.
   */
  limit?: number
}

/**
 * Log.fight
 */
export type Log$fightArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fight
   */
  select?: Prisma.FightSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fight
   */
  omit?: Prisma.FightOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FightInclude<ExtArgs> | null
  where?: Prisma.FightWhereInput
}

/**
 * Log.destinyChoice
 */
export type Log$destinyChoiceArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DestinyChoice
   */
  select?: Prisma.DestinyChoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DestinyChoice
   */
  omit?: Prisma.DestinyChoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DestinyChoiceInclude<ExtArgs> | null
  where?: Prisma.DestinyChoiceWhereInput
}

/**
 * Log without action
 */
export type LogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Log
   */
  select?: Prisma.LogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Log
   */
  omit?: Prisma.LogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogInclude<ExtArgs> | null
}
