
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TournamentAchievement` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TournamentAchievement
 * 
 */
export type TournamentAchievementModel = runtime.Types.Result.DefaultSelection<Prisma.$TournamentAchievementPayload>

export type AggregateTournamentAchievement = {
  _count: TournamentAchievementCountAggregateOutputType | null
  _avg: TournamentAchievementAvgAggregateOutputType | null
  _sum: TournamentAchievementSumAggregateOutputType | null
  _min: TournamentAchievementMinAggregateOutputType | null
  _max: TournamentAchievementMaxAggregateOutputType | null
}

export type TournamentAchievementAvgAggregateOutputType = {
  achievementCount: number | null
}

export type TournamentAchievementSumAggregateOutputType = {
  achievementCount: number | null
}

export type TournamentAchievementMinAggregateOutputType = {
  id: string | null
  bruteId: string | null
  date: Date | null
  achievement: $Enums.AchievementName | null
  achievementCount: number | null
}

export type TournamentAchievementMaxAggregateOutputType = {
  id: string | null
  bruteId: string | null
  date: Date | null
  achievement: $Enums.AchievementName | null
  achievementCount: number | null
}

export type TournamentAchievementCountAggregateOutputType = {
  id: number
  bruteId: number
  date: number
  achievement: number
  achievementCount: number
  _all: number
}


export type TournamentAchievementAvgAggregateInputType = {
  achievementCount?: true
}

export type TournamentAchievementSumAggregateInputType = {
  achievementCount?: true
}

export type TournamentAchievementMinAggregateInputType = {
  id?: true
  bruteId?: true
  date?: true
  achievement?: true
  achievementCount?: true
}

export type TournamentAchievementMaxAggregateInputType = {
  id?: true
  bruteId?: true
  date?: true
  achievement?: true
  achievementCount?: true
}

export type TournamentAchievementCountAggregateInputType = {
  id?: true
  bruteId?: true
  date?: true
  achievement?: true
  achievementCount?: true
  _all?: true
}

export type TournamentAchievementAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TournamentAchievement to aggregate.
   */
  where?: Prisma.TournamentAchievementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentAchievements to fetch.
   */
  orderBy?: Prisma.TournamentAchievementOrderByWithRelationInput | Prisma.TournamentAchievementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TournamentAchievementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentAchievements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentAchievements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TournamentAchievements
  **/
  _count?: true | TournamentAchievementCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TournamentAchievementAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TournamentAchievementSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TournamentAchievementMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TournamentAchievementMaxAggregateInputType
}

export type GetTournamentAchievementAggregateType<T extends TournamentAchievementAggregateArgs> = {
      [P in keyof T & keyof AggregateTournamentAchievement]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTournamentAchievement[P]>
    : Prisma.GetScalarType<T[P], AggregateTournamentAchievement[P]>
}




export type TournamentAchievementGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TournamentAchievementWhereInput
  orderBy?: Prisma.TournamentAchievementOrderByWithAggregationInput | Prisma.TournamentAchievementOrderByWithAggregationInput[]
  by: Prisma.TournamentAchievementScalarFieldEnum[] | Prisma.TournamentAchievementScalarFieldEnum
  having?: Prisma.TournamentAchievementScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TournamentAchievementCountAggregateInputType | true
  _avg?: TournamentAchievementAvgAggregateInputType
  _sum?: TournamentAchievementSumAggregateInputType
  _min?: TournamentAchievementMinAggregateInputType
  _max?: TournamentAchievementMaxAggregateInputType
}

export type TournamentAchievementGroupByOutputType = {
  id: string
  bruteId: string
  date: Date
  achievement: $Enums.AchievementName
  achievementCount: number
  _count: TournamentAchievementCountAggregateOutputType | null
  _avg: TournamentAchievementAvgAggregateOutputType | null
  _sum: TournamentAchievementSumAggregateOutputType | null
  _min: TournamentAchievementMinAggregateOutputType | null
  _max: TournamentAchievementMaxAggregateOutputType | null
}

export type GetTournamentAchievementGroupByPayload<T extends TournamentAchievementGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TournamentAchievementGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TournamentAchievementGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TournamentAchievementGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TournamentAchievementGroupByOutputType[P]>
      }
    >
  >



export type TournamentAchievementWhereInput = {
  AND?: Prisma.TournamentAchievementWhereInput | Prisma.TournamentAchievementWhereInput[]
  OR?: Prisma.TournamentAchievementWhereInput[]
  NOT?: Prisma.TournamentAchievementWhereInput | Prisma.TournamentAchievementWhereInput[]
  id?: Prisma.UuidFilter<"TournamentAchievement"> | string
  bruteId?: Prisma.UuidFilter<"TournamentAchievement"> | string
  date?: Prisma.DateTimeFilter<"TournamentAchievement"> | Date | string
  achievement?: Prisma.EnumAchievementNameFilter<"TournamentAchievement"> | $Enums.AchievementName
  achievementCount?: Prisma.IntFilter<"TournamentAchievement"> | number
  brute?: Prisma.XOR<Prisma.BruteScalarRelationFilter, Prisma.BruteWhereInput>
}

export type TournamentAchievementOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  bruteId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  achievement?: Prisma.SortOrder
  achievementCount?: Prisma.SortOrder
  brute?: Prisma.BruteOrderByWithRelationInput
}

export type TournamentAchievementWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  achievement_bruteId?: Prisma.TournamentAchievementAchievementBruteIdCompoundUniqueInput
  AND?: Prisma.TournamentAchievementWhereInput | Prisma.TournamentAchievementWhereInput[]
  OR?: Prisma.TournamentAchievementWhereInput[]
  NOT?: Prisma.TournamentAchievementWhereInput | Prisma.TournamentAchievementWhereInput[]
  bruteId?: Prisma.UuidFilter<"TournamentAchievement"> | string
  date?: Prisma.DateTimeFilter<"TournamentAchievement"> | Date | string
  achievement?: Prisma.EnumAchievementNameFilter<"TournamentAchievement"> | $Enums.AchievementName
  achievementCount?: Prisma.IntFilter<"TournamentAchievement"> | number
  brute?: Prisma.XOR<Prisma.BruteScalarRelationFilter, Prisma.BruteWhereInput>
}, "id" | "id" | "achievement_bruteId">

export type TournamentAchievementOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  bruteId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  achievement?: Prisma.SortOrder
  achievementCount?: Prisma.SortOrder
  _count?: Prisma.TournamentAchievementCountOrderByAggregateInput
  _avg?: Prisma.TournamentAchievementAvgOrderByAggregateInput
  _max?: Prisma.TournamentAchievementMaxOrderByAggregateInput
  _min?: Prisma.TournamentAchievementMinOrderByAggregateInput
  _sum?: Prisma.TournamentAchievementSumOrderByAggregateInput
}

export type TournamentAchievementScalarWhereWithAggregatesInput = {
  AND?: Prisma.TournamentAchievementScalarWhereWithAggregatesInput | Prisma.TournamentAchievementScalarWhereWithAggregatesInput[]
  OR?: Prisma.TournamentAchievementScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TournamentAchievementScalarWhereWithAggregatesInput | Prisma.TournamentAchievementScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"TournamentAchievement"> | string
  bruteId?: Prisma.UuidWithAggregatesFilter<"TournamentAchievement"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"TournamentAchievement"> | Date | string
  achievement?: Prisma.EnumAchievementNameWithAggregatesFilter<"TournamentAchievement"> | $Enums.AchievementName
  achievementCount?: Prisma.IntWithAggregatesFilter<"TournamentAchievement"> | number
}

export type TournamentAchievementCreateInput = {
  id?: string
  date: Date | string
  achievement: $Enums.AchievementName
  achievementCount: number
  brute: Prisma.BruteCreateNestedOneWithoutTournamentAchievementsInput
}

export type TournamentAchievementUncheckedCreateInput = {
  id?: string
  bruteId: string
  date: Date | string
  achievement: $Enums.AchievementName
  achievementCount: number
}

export type TournamentAchievementUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  achievement?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  achievementCount?: Prisma.IntFieldUpdateOperationsInput | number
  brute?: Prisma.BruteUpdateOneRequiredWithoutTournamentAchievementsNestedInput
}

export type TournamentAchievementUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bruteId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  achievement?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  achievementCount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TournamentAchievementCreateManyInput = {
  id?: string
  bruteId: string
  date: Date | string
  achievement: $Enums.AchievementName
  achievementCount: number
}

export type TournamentAchievementUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  achievement?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  achievementCount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TournamentAchievementUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bruteId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  achievement?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  achievementCount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TournamentAchievementListRelationFilter = {
  every?: Prisma.TournamentAchievementWhereInput
  some?: Prisma.TournamentAchievementWhereInput
  none?: Prisma.TournamentAchievementWhereInput
}

export type TournamentAchievementOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TournamentAchievementAchievementBruteIdCompoundUniqueInput = {
  achievement: $Enums.AchievementName
  bruteId: string
}

export type TournamentAchievementCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bruteId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  achievement?: Prisma.SortOrder
  achievementCount?: Prisma.SortOrder
}

export type TournamentAchievementAvgOrderByAggregateInput = {
  achievementCount?: Prisma.SortOrder
}

export type TournamentAchievementMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bruteId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  achievement?: Prisma.SortOrder
  achievementCount?: Prisma.SortOrder
}

export type TournamentAchievementMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bruteId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  achievement?: Prisma.SortOrder
  achievementCount?: Prisma.SortOrder
}

export type TournamentAchievementSumOrderByAggregateInput = {
  achievementCount?: Prisma.SortOrder
}

export type TournamentAchievementCreateNestedManyWithoutBruteInput = {
  create?: Prisma.XOR<Prisma.TournamentAchievementCreateWithoutBruteInput, Prisma.TournamentAchievementUncheckedCreateWithoutBruteInput> | Prisma.TournamentAchievementCreateWithoutBruteInput[] | Prisma.TournamentAchievementUncheckedCreateWithoutBruteInput[]
  connectOrCreate?: Prisma.TournamentAchievementCreateOrConnectWithoutBruteInput | Prisma.TournamentAchievementCreateOrConnectWithoutBruteInput[]
  createMany?: Prisma.TournamentAchievementCreateManyBruteInputEnvelope
  connect?: Prisma.TournamentAchievementWhereUniqueInput | Prisma.TournamentAchievementWhereUniqueInput[]
}

export type TournamentAchievementUncheckedCreateNestedManyWithoutBruteInput = {
  create?: Prisma.XOR<Prisma.TournamentAchievementCreateWithoutBruteInput, Prisma.TournamentAchievementUncheckedCreateWithoutBruteInput> | Prisma.TournamentAchievementCreateWithoutBruteInput[] | Prisma.TournamentAchievementUncheckedCreateWithoutBruteInput[]
  connectOrCreate?: Prisma.TournamentAchievementCreateOrConnectWithoutBruteInput | Prisma.TournamentAchievementCreateOrConnectWithoutBruteInput[]
  createMany?: Prisma.TournamentAchievementCreateManyBruteInputEnvelope
  connect?: Prisma.TournamentAchievementWhereUniqueInput | Prisma.TournamentAchievementWhereUniqueInput[]
}

export type TournamentAchievementUpdateManyWithoutBruteNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentAchievementCreateWithoutBruteInput, Prisma.TournamentAchievementUncheckedCreateWithoutBruteInput> | Prisma.TournamentAchievementCreateWithoutBruteInput[] | Prisma.TournamentAchievementUncheckedCreateWithoutBruteInput[]
  connectOrCreate?: Prisma.TournamentAchievementCreateOrConnectWithoutBruteInput | Prisma.TournamentAchievementCreateOrConnectWithoutBruteInput[]
  upsert?: Prisma.TournamentAchievementUpsertWithWhereUniqueWithoutBruteInput | Prisma.TournamentAchievementUpsertWithWhereUniqueWithoutBruteInput[]
  createMany?: Prisma.TournamentAchievementCreateManyBruteInputEnvelope
  set?: Prisma.TournamentAchievementWhereUniqueInput | Prisma.TournamentAchievementWhereUniqueInput[]
  disconnect?: Prisma.TournamentAchievementWhereUniqueInput | Prisma.TournamentAchievementWhereUniqueInput[]
  delete?: Prisma.TournamentAchievementWhereUniqueInput | Prisma.TournamentAchievementWhereUniqueInput[]
  connect?: Prisma.TournamentAchievementWhereUniqueInput | Prisma.TournamentAchievementWhereUniqueInput[]
  update?: Prisma.TournamentAchievementUpdateWithWhereUniqueWithoutBruteInput | Prisma.TournamentAchievementUpdateWithWhereUniqueWithoutBruteInput[]
  updateMany?: Prisma.TournamentAchievementUpdateManyWithWhereWithoutBruteInput | Prisma.TournamentAchievementUpdateManyWithWhereWithoutBruteInput[]
  deleteMany?: Prisma.TournamentAchievementScalarWhereInput | Prisma.TournamentAchievementScalarWhereInput[]
}

export type TournamentAchievementUncheckedUpdateManyWithoutBruteNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentAchievementCreateWithoutBruteInput, Prisma.TournamentAchievementUncheckedCreateWithoutBruteInput> | Prisma.TournamentAchievementCreateWithoutBruteInput[] | Prisma.TournamentAchievementUncheckedCreateWithoutBruteInput[]
  connectOrCreate?: Prisma.TournamentAchievementCreateOrConnectWithoutBruteInput | Prisma.TournamentAchievementCreateOrConnectWithoutBruteInput[]
  upsert?: Prisma.TournamentAchievementUpsertWithWhereUniqueWithoutBruteInput | Prisma.TournamentAchievementUpsertWithWhereUniqueWithoutBruteInput[]
  createMany?: Prisma.TournamentAchievementCreateManyBruteInputEnvelope
  set?: Prisma.TournamentAchievementWhereUniqueInput | Prisma.TournamentAchievementWhereUniqueInput[]
  disconnect?: Prisma.TournamentAchievementWhereUniqueInput | Prisma.TournamentAchievementWhereUniqueInput[]
  delete?: Prisma.TournamentAchievementWhereUniqueInput | Prisma.TournamentAchievementWhereUniqueInput[]
  connect?: Prisma.TournamentAchievementWhereUniqueInput | Prisma.TournamentAchievementWhereUniqueInput[]
  update?: Prisma.TournamentAchievementUpdateWithWhereUniqueWithoutBruteInput | Prisma.TournamentAchievementUpdateWithWhereUniqueWithoutBruteInput[]
  updateMany?: Prisma.TournamentAchievementUpdateManyWithWhereWithoutBruteInput | Prisma.TournamentAchievementUpdateManyWithWhereWithoutBruteInput[]
  deleteMany?: Prisma.TournamentAchievementScalarWhereInput | Prisma.TournamentAchievementScalarWhereInput[]
}

export type EnumAchievementNameFieldUpdateOperationsInput = {
  set?: $Enums.AchievementName
}

export type TournamentAchievementCreateWithoutBruteInput = {
  id?: string
  date: Date | string
  achievement: $Enums.AchievementName
  achievementCount: number
}

export type TournamentAchievementUncheckedCreateWithoutBruteInput = {
  id?: string
  date: Date | string
  achievement: $Enums.AchievementName
  achievementCount: number
}

export type TournamentAchievementCreateOrConnectWithoutBruteInput = {
  where: Prisma.TournamentAchievementWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentAchievementCreateWithoutBruteInput, Prisma.TournamentAchievementUncheckedCreateWithoutBruteInput>
}

export type TournamentAchievementCreateManyBruteInputEnvelope = {
  data: Prisma.TournamentAchievementCreateManyBruteInput | Prisma.TournamentAchievementCreateManyBruteInput[]
  skipDuplicates?: boolean
}

export type TournamentAchievementUpsertWithWhereUniqueWithoutBruteInput = {
  where: Prisma.TournamentAchievementWhereUniqueInput
  update: Prisma.XOR<Prisma.TournamentAchievementUpdateWithoutBruteInput, Prisma.TournamentAchievementUncheckedUpdateWithoutBruteInput>
  create: Prisma.XOR<Prisma.TournamentAchievementCreateWithoutBruteInput, Prisma.TournamentAchievementUncheckedCreateWithoutBruteInput>
}

export type TournamentAchievementUpdateWithWhereUniqueWithoutBruteInput = {
  where: Prisma.TournamentAchievementWhereUniqueInput
  data: Prisma.XOR<Prisma.TournamentAchievementUpdateWithoutBruteInput, Prisma.TournamentAchievementUncheckedUpdateWithoutBruteInput>
}

export type TournamentAchievementUpdateManyWithWhereWithoutBruteInput = {
  where: Prisma.TournamentAchievementScalarWhereInput
  data: Prisma.XOR<Prisma.TournamentAchievementUpdateManyMutationInput, Prisma.TournamentAchievementUncheckedUpdateManyWithoutBruteInput>
}

export type TournamentAchievementScalarWhereInput = {
  AND?: Prisma.TournamentAchievementScalarWhereInput | Prisma.TournamentAchievementScalarWhereInput[]
  OR?: Prisma.TournamentAchievementScalarWhereInput[]
  NOT?: Prisma.TournamentAchievementScalarWhereInput | Prisma.TournamentAchievementScalarWhereInput[]
  id?: Prisma.UuidFilter<"TournamentAchievement"> | string
  bruteId?: Prisma.UuidFilter<"TournamentAchievement"> | string
  date?: Prisma.DateTimeFilter<"TournamentAchievement"> | Date | string
  achievement?: Prisma.EnumAchievementNameFilter<"TournamentAchievement"> | $Enums.AchievementName
  achievementCount?: Prisma.IntFilter<"TournamentAchievement"> | number
}

export type TournamentAchievementCreateManyBruteInput = {
  id?: string
  date: Date | string
  achievement: $Enums.AchievementName
  achievementCount: number
}

export type TournamentAchievementUpdateWithoutBruteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  achievement?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  achievementCount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TournamentAchievementUncheckedUpdateWithoutBruteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  achievement?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  achievementCount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TournamentAchievementUncheckedUpdateManyWithoutBruteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  achievement?: Prisma.EnumAchievementNameFieldUpdateOperationsInput | $Enums.AchievementName
  achievementCount?: Prisma.IntFieldUpdateOperationsInput | number
}



export type TournamentAchievementSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bruteId?: boolean
  date?: boolean
  achievement?: boolean
  achievementCount?: boolean
  brute?: boolean | Prisma.BruteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tournamentAchievement"]>

export type TournamentAchievementSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bruteId?: boolean
  date?: boolean
  achievement?: boolean
  achievementCount?: boolean
  brute?: boolean | Prisma.BruteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tournamentAchievement"]>

export type TournamentAchievementSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bruteId?: boolean
  date?: boolean
  achievement?: boolean
  achievementCount?: boolean
  brute?: boolean | Prisma.BruteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tournamentAchievement"]>

export type TournamentAchievementSelectScalar = {
  id?: boolean
  bruteId?: boolean
  date?: boolean
  achievement?: boolean
  achievementCount?: boolean
}

export type TournamentAchievementOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "bruteId" | "date" | "achievement" | "achievementCount", ExtArgs["result"]["tournamentAchievement"]>
export type TournamentAchievementInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  brute?: boolean | Prisma.BruteDefaultArgs<ExtArgs>
}
export type TournamentAchievementIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  brute?: boolean | Prisma.BruteDefaultArgs<ExtArgs>
}
export type TournamentAchievementIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  brute?: boolean | Prisma.BruteDefaultArgs<ExtArgs>
}

export type $TournamentAchievementPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TournamentAchievement"
  objects: {
    brute: Prisma.$BrutePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    bruteId: string
    date: Date
    achievement: $Enums.AchievementName
    achievementCount: number
  }, ExtArgs["result"]["tournamentAchievement"]>
  composites: {}
}

export type TournamentAchievementGetPayload<S extends boolean | null | undefined | TournamentAchievementDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TournamentAchievementPayload, S>

export type TournamentAchievementCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TournamentAchievementFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: TournamentAchievementCountAggregateInputType | true
  }

export interface TournamentAchievementDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TournamentAchievement'], meta: { name: 'TournamentAchievement' } }
  /**
   * Find zero or one TournamentAchievement that matches the filter.
   * @param {TournamentAchievementFindUniqueArgs} args - Arguments to find a TournamentAchievement
   * @example
   * // Get one TournamentAchievement
   * const tournamentAchievement = await prisma.tournamentAchievement.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TournamentAchievementFindUniqueArgs>(args: Prisma.SelectSubset<T, TournamentAchievementFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TournamentAchievementClient<runtime.Types.Result.GetResult<Prisma.$TournamentAchievementPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TournamentAchievement that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TournamentAchievementFindUniqueOrThrowArgs} args - Arguments to find a TournamentAchievement
   * @example
   * // Get one TournamentAchievement
   * const tournamentAchievement = await prisma.tournamentAchievement.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TournamentAchievementFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TournamentAchievementFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TournamentAchievementClient<runtime.Types.Result.GetResult<Prisma.$TournamentAchievementPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TournamentAchievement that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentAchievementFindFirstArgs} args - Arguments to find a TournamentAchievement
   * @example
   * // Get one TournamentAchievement
   * const tournamentAchievement = await prisma.tournamentAchievement.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TournamentAchievementFindFirstArgs>(args?: Prisma.SelectSubset<T, TournamentAchievementFindFirstArgs<ExtArgs>>): Prisma.Prisma__TournamentAchievementClient<runtime.Types.Result.GetResult<Prisma.$TournamentAchievementPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TournamentAchievement that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentAchievementFindFirstOrThrowArgs} args - Arguments to find a TournamentAchievement
   * @example
   * // Get one TournamentAchievement
   * const tournamentAchievement = await prisma.tournamentAchievement.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TournamentAchievementFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TournamentAchievementFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TournamentAchievementClient<runtime.Types.Result.GetResult<Prisma.$TournamentAchievementPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TournamentAchievements that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentAchievementFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TournamentAchievements
   * const tournamentAchievements = await prisma.tournamentAchievement.findMany()
   * 
   * // Get first 10 TournamentAchievements
   * const tournamentAchievements = await prisma.tournamentAchievement.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tournamentAchievementWithIdOnly = await prisma.tournamentAchievement.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TournamentAchievementFindManyArgs>(args?: Prisma.SelectSubset<T, TournamentAchievementFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentAchievementPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TournamentAchievement.
   * @param {TournamentAchievementCreateArgs} args - Arguments to create a TournamentAchievement.
   * @example
   * // Create one TournamentAchievement
   * const TournamentAchievement = await prisma.tournamentAchievement.create({
   *   data: {
   *     // ... data to create a TournamentAchievement
   *   }
   * })
   * 
   */
  create<T extends TournamentAchievementCreateArgs>(args: Prisma.SelectSubset<T, TournamentAchievementCreateArgs<ExtArgs>>): Prisma.Prisma__TournamentAchievementClient<runtime.Types.Result.GetResult<Prisma.$TournamentAchievementPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TournamentAchievements.
   * @param {TournamentAchievementCreateManyArgs} args - Arguments to create many TournamentAchievements.
   * @example
   * // Create many TournamentAchievements
   * const tournamentAchievement = await prisma.tournamentAchievement.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TournamentAchievementCreateManyArgs>(args?: Prisma.SelectSubset<T, TournamentAchievementCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TournamentAchievements and returns the data saved in the database.
   * @param {TournamentAchievementCreateManyAndReturnArgs} args - Arguments to create many TournamentAchievements.
   * @example
   * // Create many TournamentAchievements
   * const tournamentAchievement = await prisma.tournamentAchievement.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TournamentAchievements and only return the `id`
   * const tournamentAchievementWithIdOnly = await prisma.tournamentAchievement.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TournamentAchievementCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TournamentAchievementCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentAchievementPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TournamentAchievement.
   * @param {TournamentAchievementDeleteArgs} args - Arguments to delete one TournamentAchievement.
   * @example
   * // Delete one TournamentAchievement
   * const TournamentAchievement = await prisma.tournamentAchievement.delete({
   *   where: {
   *     // ... filter to delete one TournamentAchievement
   *   }
   * })
   * 
   */
  delete<T extends TournamentAchievementDeleteArgs>(args: Prisma.SelectSubset<T, TournamentAchievementDeleteArgs<ExtArgs>>): Prisma.Prisma__TournamentAchievementClient<runtime.Types.Result.GetResult<Prisma.$TournamentAchievementPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TournamentAchievement.
   * @param {TournamentAchievementUpdateArgs} args - Arguments to update one TournamentAchievement.
   * @example
   * // Update one TournamentAchievement
   * const tournamentAchievement = await prisma.tournamentAchievement.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TournamentAchievementUpdateArgs>(args: Prisma.SelectSubset<T, TournamentAchievementUpdateArgs<ExtArgs>>): Prisma.Prisma__TournamentAchievementClient<runtime.Types.Result.GetResult<Prisma.$TournamentAchievementPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TournamentAchievements.
   * @param {TournamentAchievementDeleteManyArgs} args - Arguments to filter TournamentAchievements to delete.
   * @example
   * // Delete a few TournamentAchievements
   * const { count } = await prisma.tournamentAchievement.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TournamentAchievementDeleteManyArgs>(args?: Prisma.SelectSubset<T, TournamentAchievementDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TournamentAchievements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentAchievementUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TournamentAchievements
   * const tournamentAchievement = await prisma.tournamentAchievement.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TournamentAchievementUpdateManyArgs>(args: Prisma.SelectSubset<T, TournamentAchievementUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TournamentAchievements and returns the data updated in the database.
   * @param {TournamentAchievementUpdateManyAndReturnArgs} args - Arguments to update many TournamentAchievements.
   * @example
   * // Update many TournamentAchievements
   * const tournamentAchievement = await prisma.tournamentAchievement.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TournamentAchievements and only return the `id`
   * const tournamentAchievementWithIdOnly = await prisma.tournamentAchievement.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TournamentAchievementUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TournamentAchievementUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentAchievementPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TournamentAchievement.
   * @param {TournamentAchievementUpsertArgs} args - Arguments to update or create a TournamentAchievement.
   * @example
   * // Update or create a TournamentAchievement
   * const tournamentAchievement = await prisma.tournamentAchievement.upsert({
   *   create: {
   *     // ... data to create a TournamentAchievement
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TournamentAchievement we want to update
   *   }
   * })
   */
  upsert<T extends TournamentAchievementUpsertArgs>(args: Prisma.SelectSubset<T, TournamentAchievementUpsertArgs<ExtArgs>>): Prisma.Prisma__TournamentAchievementClient<runtime.Types.Result.GetResult<Prisma.$TournamentAchievementPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TournamentAchievements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentAchievementCountArgs} args - Arguments to filter TournamentAchievements to count.
   * @example
   * // Count the number of TournamentAchievements
   * const count = await prisma.tournamentAchievement.count({
   *   where: {
   *     // ... the filter for the TournamentAchievements we want to count
   *   }
   * })
  **/
  count<T extends TournamentAchievementCountArgs>(
    args?: Prisma.Subset<T, TournamentAchievementCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TournamentAchievementCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TournamentAchievement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentAchievementAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TournamentAchievementAggregateArgs>(args: Prisma.Subset<T, TournamentAchievementAggregateArgs>): Prisma.PrismaPromise<GetTournamentAchievementAggregateType<T>>

  /**
   * Group by TournamentAchievement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentAchievementGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TournamentAchievementGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TournamentAchievementGroupByArgs['orderBy'] }
      : { orderBy?: TournamentAchievementGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TournamentAchievementGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTournamentAchievementGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TournamentAchievement model
 */
readonly fields: TournamentAchievementFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TournamentAchievement.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TournamentAchievementClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  brute<T extends Prisma.BruteDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BruteDefaultArgs<ExtArgs>>): Prisma.Prisma__BruteClient<runtime.Types.Result.GetResult<Prisma.$BrutePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TournamentAchievement model
 */
export interface TournamentAchievementFieldRefs {
  readonly id: Prisma.FieldRef<"TournamentAchievement", 'String'>
  readonly bruteId: Prisma.FieldRef<"TournamentAchievement", 'String'>
  readonly date: Prisma.FieldRef<"TournamentAchievement", 'DateTime'>
  readonly achievement: Prisma.FieldRef<"TournamentAchievement", 'AchievementName'>
  readonly achievementCount: Prisma.FieldRef<"TournamentAchievement", 'Int'>
}
    

// Custom InputTypes
/**
 * TournamentAchievement findUnique
 */
export type TournamentAchievementFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentAchievement
   */
  select?: Prisma.TournamentAchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentAchievement
   */
  omit?: Prisma.TournamentAchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentAchievementInclude<ExtArgs> | null
  /**
   * Filter, which TournamentAchievement to fetch.
   */
  where: Prisma.TournamentAchievementWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TournamentAchievement findUniqueOrThrow
 */
export type TournamentAchievementFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentAchievement
   */
  select?: Prisma.TournamentAchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentAchievement
   */
  omit?: Prisma.TournamentAchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentAchievementInclude<ExtArgs> | null
  /**
   * Filter, which TournamentAchievement to fetch.
   */
  where: Prisma.TournamentAchievementWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TournamentAchievement findFirst
 */
export type TournamentAchievementFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentAchievement
   */
  select?: Prisma.TournamentAchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentAchievement
   */
  omit?: Prisma.TournamentAchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentAchievementInclude<ExtArgs> | null
  /**
   * Filter, which TournamentAchievement to fetch.
   */
  where?: Prisma.TournamentAchievementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentAchievements to fetch.
   */
  orderBy?: Prisma.TournamentAchievementOrderByWithRelationInput | Prisma.TournamentAchievementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TournamentAchievements.
   */
  cursor?: Prisma.TournamentAchievementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentAchievements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentAchievements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentAchievements.
   */
  distinct?: Prisma.TournamentAchievementScalarFieldEnum | Prisma.TournamentAchievementScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TournamentAchievement findFirstOrThrow
 */
export type TournamentAchievementFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentAchievement
   */
  select?: Prisma.TournamentAchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentAchievement
   */
  omit?: Prisma.TournamentAchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentAchievementInclude<ExtArgs> | null
  /**
   * Filter, which TournamentAchievement to fetch.
   */
  where?: Prisma.TournamentAchievementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentAchievements to fetch.
   */
  orderBy?: Prisma.TournamentAchievementOrderByWithRelationInput | Prisma.TournamentAchievementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TournamentAchievements.
   */
  cursor?: Prisma.TournamentAchievementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentAchievements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentAchievements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentAchievements.
   */
  distinct?: Prisma.TournamentAchievementScalarFieldEnum | Prisma.TournamentAchievementScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TournamentAchievement findMany
 */
export type TournamentAchievementFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentAchievement
   */
  select?: Prisma.TournamentAchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentAchievement
   */
  omit?: Prisma.TournamentAchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentAchievementInclude<ExtArgs> | null
  /**
   * Filter, which TournamentAchievements to fetch.
   */
  where?: Prisma.TournamentAchievementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentAchievements to fetch.
   */
  orderBy?: Prisma.TournamentAchievementOrderByWithRelationInput | Prisma.TournamentAchievementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TournamentAchievements.
   */
  cursor?: Prisma.TournamentAchievementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentAchievements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentAchievements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentAchievements.
   */
  distinct?: Prisma.TournamentAchievementScalarFieldEnum | Prisma.TournamentAchievementScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TournamentAchievement create
 */
export type TournamentAchievementCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentAchievement
   */
  select?: Prisma.TournamentAchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentAchievement
   */
  omit?: Prisma.TournamentAchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentAchievementInclude<ExtArgs> | null
  /**
   * The data needed to create a TournamentAchievement.
   */
  data: Prisma.XOR<Prisma.TournamentAchievementCreateInput, Prisma.TournamentAchievementUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TournamentAchievement createMany
 */
export type TournamentAchievementCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TournamentAchievements.
   */
  data: Prisma.TournamentAchievementCreateManyInput | Prisma.TournamentAchievementCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TournamentAchievement createManyAndReturn
 */
export type TournamentAchievementCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentAchievement
   */
  select?: Prisma.TournamentAchievementSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentAchievement
   */
  omit?: Prisma.TournamentAchievementOmit<ExtArgs> | null
  /**
   * The data used to create many TournamentAchievements.
   */
  data: Prisma.TournamentAchievementCreateManyInput | Prisma.TournamentAchievementCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentAchievementIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TournamentAchievement update
 */
export type TournamentAchievementUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentAchievement
   */
  select?: Prisma.TournamentAchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentAchievement
   */
  omit?: Prisma.TournamentAchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentAchievementInclude<ExtArgs> | null
  /**
   * The data needed to update a TournamentAchievement.
   */
  data: Prisma.XOR<Prisma.TournamentAchievementUpdateInput, Prisma.TournamentAchievementUncheckedUpdateInput>
  /**
   * Choose, which TournamentAchievement to update.
   */
  where: Prisma.TournamentAchievementWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TournamentAchievement updateMany
 */
export type TournamentAchievementUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TournamentAchievements.
   */
  data: Prisma.XOR<Prisma.TournamentAchievementUpdateManyMutationInput, Prisma.TournamentAchievementUncheckedUpdateManyInput>
  /**
   * Filter which TournamentAchievements to update
   */
  where?: Prisma.TournamentAchievementWhereInput
  /**
   * Limit how many TournamentAchievements to update.
   */
  limit?: number
}

/**
 * TournamentAchievement updateManyAndReturn
 */
export type TournamentAchievementUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentAchievement
   */
  select?: Prisma.TournamentAchievementSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentAchievement
   */
  omit?: Prisma.TournamentAchievementOmit<ExtArgs> | null
  /**
   * The data used to update TournamentAchievements.
   */
  data: Prisma.XOR<Prisma.TournamentAchievementUpdateManyMutationInput, Prisma.TournamentAchievementUncheckedUpdateManyInput>
  /**
   * Filter which TournamentAchievements to update
   */
  where?: Prisma.TournamentAchievementWhereInput
  /**
   * Limit how many TournamentAchievements to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentAchievementIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TournamentAchievement upsert
 */
export type TournamentAchievementUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentAchievement
   */
  select?: Prisma.TournamentAchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentAchievement
   */
  omit?: Prisma.TournamentAchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentAchievementInclude<ExtArgs> | null
  /**
   * The filter to search for the TournamentAchievement to update in case it exists.
   */
  where: Prisma.TournamentAchievementWhereUniqueInput
  /**
   * In case the TournamentAchievement found by the `where` argument doesn't exist, create a new TournamentAchievement with this data.
   */
  create: Prisma.XOR<Prisma.TournamentAchievementCreateInput, Prisma.TournamentAchievementUncheckedCreateInput>
  /**
   * In case the TournamentAchievement was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TournamentAchievementUpdateInput, Prisma.TournamentAchievementUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TournamentAchievement delete
 */
export type TournamentAchievementDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentAchievement
   */
  select?: Prisma.TournamentAchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentAchievement
   */
  omit?: Prisma.TournamentAchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentAchievementInclude<ExtArgs> | null
  /**
   * Filter which TournamentAchievement to delete.
   */
  where: Prisma.TournamentAchievementWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * TournamentAchievement deleteMany
 */
export type TournamentAchievementDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TournamentAchievements to delete
   */
  where?: Prisma.TournamentAchievementWhereInput
  /**
   * Limit how many TournamentAchievements to delete.
   */
  limit?: number
}

/**
 * TournamentAchievement without action
 */
export type TournamentAchievementDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentAchievement
   */
  select?: Prisma.TournamentAchievementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentAchievement
   */
  omit?: Prisma.TournamentAchievementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentAchievementInclude<ExtArgs> | null
}
