"use strict";
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.SortOrder = exports.ConfigScalarFieldEnum = exports.NotificationScalarFieldEnum = exports.EventScalarFieldEnum = exports.ReleaseScalarFieldEnum = exports.InventoryItemScalarFieldEnum = exports.ClanWarFightersScalarFieldEnum = exports.ClanWarScalarFieldEnum = exports.BossDamageScalarFieldEnum = exports.ClanPostScalarFieldEnum = exports.ClanThreadScalarFieldEnum = exports.ClanScalarFieldEnum = exports.KnownFingerprintScalarFieldEnum = exports.BannedFingerprintScalarFieldEnum = exports.BannedIpScalarFieldEnum = exports.BannedWordScalarFieldEnum = exports.ServerStateScalarFieldEnum = exports.BruteReportScalarFieldEnum = exports.AchievementScalarFieldEnum = exports.TournamentXpScalarFieldEnum = exports.TournamentGoldScalarFieldEnum = exports.TournamentAchievementScalarFieldEnum = exports.TournamentScalarFieldEnum = exports.DestinyChoiceScalarFieldEnum = exports.LogScalarFieldEnum = exports.FightScalarFieldEnum = exports.BruteStartingStatsScalarFieldEnum = exports.BruteScalarFieldEnum = exports.UserLogScalarFieldEnum = exports.RelationLoadStrategy = exports.UserScalarFieldEnum = exports.TransactionIsolationLevel = exports.ModelName = exports.AnyNull = exports.JsonNull = exports.DbNull = exports.NullTypes = exports.prismaVersion = exports.getExtensionContext = exports.Decimal = exports.Sql = exports.raw = exports.join = exports.empty = exports.sql = exports.PrismaClientValidationError = exports.PrismaClientInitializationError = exports.PrismaClientRustPanicError = exports.PrismaClientUnknownRequestError = exports.PrismaClientKnownRequestError = void 0;
exports.defineExtension = exports.NullsOrder = exports.QueryMode = void 0;
const runtime = __importStar(require("@prisma/client/runtime/client"));
/**
 * Prisma Errors
 */
exports.PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError;
exports.PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError;
exports.PrismaClientRustPanicError = runtime.PrismaClientRustPanicError;
exports.PrismaClientInitializationError = runtime.PrismaClientInitializationError;
exports.PrismaClientValidationError = runtime.PrismaClientValidationError;
/**
 * Re-export of sql-template-tag
 */
exports.sql = runtime.sqltag;
exports.empty = runtime.empty;
exports.join = runtime.join;
exports.raw = runtime.raw;
exports.Sql = runtime.Sql;
/**
 * Decimal.js
 */
exports.Decimal = runtime.Decimal;
exports.getExtensionContext = runtime.Extensions.getExtensionContext;
/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
exports.prismaVersion = {
    client: "7.8.0",
    engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
};
exports.NullTypes = {
    DbNull: runtime.NullTypes.DbNull,
    JsonNull: runtime.NullTypes.JsonNull,
    AnyNull: runtime.NullTypes.AnyNull,
};
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
exports.DbNull = runtime.DbNull;
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
exports.JsonNull = runtime.JsonNull;
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
exports.AnyNull = runtime.AnyNull;
exports.ModelName = {
    User: 'User',
    UserLog: 'UserLog',
    Brute: 'Brute',
    BruteStartingStats: 'BruteStartingStats',
    Fight: 'Fight',
    Log: 'Log',
    DestinyChoice: 'DestinyChoice',
    Tournament: 'Tournament',
    TournamentAchievement: 'TournamentAchievement',
    TournamentGold: 'TournamentGold',
    TournamentXp: 'TournamentXp',
    Achievement: 'Achievement',
    BruteReport: 'BruteReport',
    ServerState: 'ServerState',
    BannedWord: 'BannedWord',
    BannedIp: 'BannedIp',
    BannedFingerprint: 'BannedFingerprint',
    KnownFingerprint: 'KnownFingerprint',
    Clan: 'Clan',
    ClanThread: 'ClanThread',
    ClanPost: 'ClanPost',
    BossDamage: 'BossDamage',
    ClanWar: 'ClanWar',
    ClanWarFighters: 'ClanWarFighters',
    InventoryItem: 'InventoryItem',
    Release: 'Release',
    Event: 'Event',
    Notification: 'Notification',
    Config: 'Config'
};
/**
 * Enums
 */
exports.TransactionIsolationLevel = runtime.makeStrictEnum({
    ReadUncommitted: 'ReadUncommitted',
    ReadCommitted: 'ReadCommitted',
    RepeatableRead: 'RepeatableRead',
    Serializable: 'Serializable'
});
exports.UserScalarFieldEnum = {
    id: 'id',
    lang: 'lang',
    name: 'name',
    admin: 'admin',
    moderator: 'moderator',
    connexionToken: 'connexionToken',
    bruteLimit: 'bruteLimit',
    gold: 'gold',
    fightSpeed: 'fightSpeed',
    backgroundMusic: 'backgroundMusic',
    dinorpgDone: 'dinorpgDone',
    ips: 'ips',
    fingerprints: 'fingerprints',
    createdAt: 'createdAt',
    bannedAt: 'bannedAt',
    banReason: 'banReason',
    displayVersusPage: 'displayVersusPage',
    displayOpponentDetails: 'displayOpponentDetails',
    transferedBrutesCount: 'transferedBrutesCount',
    lastSeen: 'lastSeen'
};
exports.RelationLoadStrategy = {
    query: 'query',
    join: 'join'
};
exports.UserLogScalarFieldEnum = {
    id: 'id',
    date: 'date',
    userId: 'userId',
    type: 'type',
    bruteId: 'bruteId',
    gold: 'gold',
    oldName: 'oldName',
    targetUserId: 'targetUserId'
};
exports.BruteScalarFieldEnum = {
    id: 'id',
    name: 'name',
    deletedAt: 'deletedAt',
    createdAt: 'createdAt',
    willBeDeletedAt: 'willBeDeletedAt',
    deletionReason: 'deletionReason',
    destinyPath: 'destinyPath',
    previousDestinyPath: 'previousDestinyPath',
    level: 'level',
    xp: 'xp',
    hp: 'hp',
    enduranceStat: 'enduranceStat',
    enduranceModifier: 'enduranceModifier',
    enduranceValue: 'enduranceValue',
    strengthStat: 'strengthStat',
    strengthModifier: 'strengthModifier',
    strengthValue: 'strengthValue',
    agilityStat: 'agilityStat',
    agilityModifier: 'agilityModifier',
    agilityValue: 'agilityValue',
    speedStat: 'speedStat',
    speedModifier: 'speedModifier',
    speedValue: 'speedValue',
    ranking: 'ranking',
    gender: 'gender',
    userId: 'userId',
    body: 'body',
    colors: 'colors',
    weapons: 'weapons',
    skills: 'skills',
    pets: 'pets',
    ascensions: 'ascensions',
    ascendedWeapons: 'ascendedWeapons',
    ascendedSkills: 'ascendedSkills',
    ascendedPets: 'ascendedPets',
    masterId: 'masterId',
    pupilsCount: 'pupilsCount',
    clanId: 'clanId',
    registeredForTournament: 'registeredForTournament',
    nextTournamentDate: 'nextTournamentDate',
    currentTournamentDate: 'currentTournamentDate',
    currentTournamentStepWatched: 'currentTournamentStepWatched',
    globalTournamentWatchedDate: 'globalTournamentWatchedDate',
    globalTournamentRoundWatched: 'globalTournamentRoundWatched',
    eventTournamentWatchedDate: 'eventTournamentWatchedDate',
    eventTournamentRoundWatched: 'eventTournamentRoundWatched',
    lastFight: 'lastFight',
    fightsLeft: 'fightsLeft',
    victories: 'victories',
    losses: 'losses',
    opponentsGeneratedAt: 'opponentsGeneratedAt',
    canRankUpSince: 'canRankUpSince',
    favorite: 'favorite',
    wantToJoinClanId: 'wantToJoinClanId',
    tournamentWins: 'tournamentWins',
    eventId: 'eventId',
    resets: 'resets'
};
exports.BruteStartingStatsScalarFieldEnum = {
    id: 'id',
    endurance: 'endurance',
    strength: 'strength',
    agility: 'agility',
    speed: 'speed',
    bruteId: 'bruteId'
};
exports.FightScalarFieldEnum = {
    id: 'id',
    date: 'date',
    brute1Id: 'brute1Id',
    brute2Id: 'brute2Id',
    winnerId: 'winnerId',
    loserId: 'loserId',
    winner: 'winner',
    loser: 'loser',
    steps: 'steps',
    fighters: 'fighters',
    tournamentId: 'tournamentId',
    tournamentStep: 'tournamentStep',
    modifiers: 'modifiers',
    background: 'background',
    clanWarId: 'clanWarId',
    favoriteCount: 'favoriteCount'
};
exports.LogScalarFieldEnum = {
    id: 'id',
    date: 'date',
    currentBruteId: 'currentBruteId',
    type: 'type',
    level: 'level',
    brute: 'brute',
    fightId: 'fightId',
    xp: 'xp',
    gold: 'gold',
    template: 'template',
    destinyChoiceId: 'destinyChoiceId'
};
exports.DestinyChoiceScalarFieldEnum = {
    id: 'id',
    bruteId: 'bruteId',
    path: 'path',
    type: 'type',
    skill: 'skill',
    weapon: 'weapon',
    pet: 'pet',
    originalSkill: 'originalSkill',
    originalWeapon: 'originalWeapon',
    originalPet: 'originalPet',
    stat1: 'stat1',
    stat1Value: 'stat1Value',
    stat2: 'stat2',
    stat2Value: 'stat2Value'
};
exports.TournamentScalarFieldEnum = {
    id: 'id',
    date: 'date',
    type: 'type',
    rounds: 'rounds',
    eventId: 'eventId'
};
exports.TournamentAchievementScalarFieldEnum = {
    id: 'id',
    bruteId: 'bruteId',
    date: 'date',
    achievement: 'achievement',
    achievementCount: 'achievementCount'
};
exports.TournamentGoldScalarFieldEnum = {
    id: 'id',
    date: 'date',
    userId: 'userId',
    gold: 'gold'
};
exports.TournamentXpScalarFieldEnum = {
    id: 'id',
    date: 'date',
    bruteId: 'bruteId',
    xp: 'xp'
};
exports.AchievementScalarFieldEnum = {
    id: 'id',
    name: 'name',
    count: 'count',
    bruteId: 'bruteId',
    userId: 'userId'
};
exports.BruteReportScalarFieldEnum = {
    id: 'id',
    bruteId: 'bruteId',
    bruteName: 'bruteName',
    reason: 'reason',
    count: 'count',
    date: 'date',
    status: 'status',
    handlerId: 'handlerId',
    handledAt: 'handledAt'
};
exports.ServerStateScalarFieldEnum = {
    id: 'id',
    globalTournamentValid: 'globalTournamentValid',
    activeModifiers: 'activeModifiers',
    modifiersEndAt: 'modifiersEndAt',
    nextModifiers: 'nextModifiers'
};
exports.BannedWordScalarFieldEnum = {
    id: 'id',
    word: 'word'
};
exports.BannedIpScalarFieldEnum = {
    id: 'id'
};
exports.BannedFingerprintScalarFieldEnum = {
    id: 'id'
};
exports.KnownFingerprintScalarFieldEnum = {
    id: 'id',
    description: 'description',
    createdAt: 'createdAt'
};
exports.ClanScalarFieldEnum = {
    id: 'id',
    name: 'name',
    deletedAt: 'deletedAt',
    limit: 'limit',
    points: 'points',
    elo: 'elo',
    boss: 'boss',
    damageOnBoss: 'damageOnBoss',
    masterId: 'masterId',
    participateInClanWar: 'participateInClanWar'
};
exports.ClanThreadScalarFieldEnum = {
    id: 'id',
    clanId: 'clanId',
    creatorId: 'creatorId',
    title: 'title',
    locked: 'locked',
    pinned: 'pinned',
    postCount: 'postCount',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
};
exports.ClanPostScalarFieldEnum = {
    id: 'id',
    threadId: 'threadId',
    authorId: 'authorId',
    date: 'date',
    message: 'message'
};
exports.BossDamageScalarFieldEnum = {
    id: 'id',
    bruteId: 'bruteId',
    clanId: 'clanId',
    damage: 'damage'
};
exports.ClanWarScalarFieldEnum = {
    id: 'id',
    duration: 'duration',
    type: 'type',
    date: 'date',
    status: 'status',
    attackerId: 'attackerId',
    attackerEloChange: 'attackerEloChange',
    attackerWins: 'attackerWins',
    defenderId: 'defenderId',
    defenderEloChange: 'defenderEloChange',
    defenderWins: 'defenderWins',
    winnerId: 'winnerId'
};
exports.ClanWarFightersScalarFieldEnum = {
    id: 'id',
    clanWarId: 'clanWarId',
    day: 'day'
};
exports.InventoryItemScalarFieldEnum = {
    id: 'id',
    type: 'type',
    count: 'count',
    bruteId: 'bruteId',
    userId: 'userId'
};
exports.ReleaseScalarFieldEnum = {
    version: 'version',
    date: 'date'
};
exports.EventScalarFieldEnum = {
    id: 'id',
    date: 'date',
    type: 'type',
    maxLevel: 'maxLevel',
    maxRound: 'maxRound',
    status: 'status',
    winnerId: 'winnerId',
    finishedAt: 'finishedAt',
    sortedBrutes: 'sortedBrutes'
};
exports.NotificationScalarFieldEnum = {
    id: 'id',
    userId: 'userId',
    message: 'message',
    severity: 'severity',
    link: 'link',
    read: 'read',
    date: 'date'
};
exports.ConfigScalarFieldEnum = {
    key: 'key',
    value: 'value',
    updatedAt: 'updatedAt'
};
exports.SortOrder = {
    asc: 'asc',
    desc: 'desc'
};
exports.QueryMode = {
    default: 'default',
    insensitive: 'insensitive'
};
exports.NullsOrder = {
    first: 'first',
    last: 'last'
};
exports.defineExtension = runtime.Extensions.defineExtension;
//# sourceMappingURL=prismaNamespace.js.map