
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  UserLog: 'UserLog',
  Brute: 'Brute',
  BruteStartingStats: 'BruteStartingStats',
  Fight: 'Fight',
  Log: 'Log',
  DestinyChoice: 'DestinyChoice',
  Tournament: 'Tournament',
  TournamentAchievement: 'TournamentAchievement',
  TournamentGold: 'TournamentGold',
  TournamentXp: 'TournamentXp',
  Achievement: 'Achievement',
  BruteReport: 'BruteReport',
  ServerState: 'ServerState',
  BannedWord: 'BannedWord',
  BannedIp: 'BannedIp',
  BannedFingerprint: 'BannedFingerprint',
  KnownFingerprint: 'KnownFingerprint',
  Clan: 'Clan',
  ClanThread: 'ClanThread',
  ClanPost: 'ClanPost',
  BossDamage: 'BossDamage',
  ClanWar: 'ClanWar',
  ClanWarFighters: 'ClanWarFighters',
  InventoryItem: 'InventoryItem',
  Release: 'Release',
  Event: 'Event',
  Notification: 'Notification',
  Config: 'Config'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  lang: 'lang',
  name: 'name',
  admin: 'admin',
  moderator: 'moderator',
  connexionToken: 'connexionToken',
  bruteLimit: 'bruteLimit',
  gold: 'gold',
  fightSpeed: 'fightSpeed',
  backgroundMusic: 'backgroundMusic',
  dinorpgDone: 'dinorpgDone',
  ips: 'ips',
  fingerprints: 'fingerprints',
  createdAt: 'createdAt',
  bannedAt: 'bannedAt',
  banReason: 'banReason',
  displayVersusPage: 'displayVersusPage',
  displayOpponentDetails: 'displayOpponentDetails',
  transferedBrutesCount: 'transferedBrutesCount',
  lastSeen: 'lastSeen'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const RelationLoadStrategy = {
  query: 'query',
  join: 'join'
} as const

export type RelationLoadStrategy = (typeof RelationLoadStrategy)[keyof typeof RelationLoadStrategy]


export const UserLogScalarFieldEnum = {
  id: 'id',
  date: 'date',
  userId: 'userId',
  type: 'type',
  bruteId: 'bruteId',
  gold: 'gold',
  oldName: 'oldName',
  targetUserId: 'targetUserId'
} as const

export type UserLogScalarFieldEnum = (typeof UserLogScalarFieldEnum)[keyof typeof UserLogScalarFieldEnum]


export const BruteScalarFieldEnum = {
  id: 'id',
  name: 'name',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  willBeDeletedAt: 'willBeDeletedAt',
  deletionReason: 'deletionReason',
  destinyPath: 'destinyPath',
  previousDestinyPath: 'previousDestinyPath',
  level: 'level',
  xp: 'xp',
  hp: 'hp',
  enduranceStat: 'enduranceStat',
  enduranceModifier: 'enduranceModifier',
  enduranceValue: 'enduranceValue',
  strengthStat: 'strengthStat',
  strengthModifier: 'strengthModifier',
  strengthValue: 'strengthValue',
  agilityStat: 'agilityStat',
  agilityModifier: 'agilityModifier',
  agilityValue: 'agilityValue',
  speedStat: 'speedStat',
  speedModifier: 'speedModifier',
  speedValue: 'speedValue',
  ranking: 'ranking',
  gender: 'gender',
  userId: 'userId',
  body: 'body',
  colors: 'colors',
  weapons: 'weapons',
  skills: 'skills',
  pets: 'pets',
  ascensions: 'ascensions',
  ascendedWeapons: 'ascendedWeapons',
  ascendedSkills: 'ascendedSkills',
  ascendedPets: 'ascendedPets',
  masterId: 'masterId',
  pupilsCount: 'pupilsCount',
  clanId: 'clanId',
  registeredForTournament: 'registeredForTournament',
  nextTournamentDate: 'nextTournamentDate',
  currentTournamentDate: 'currentTournamentDate',
  currentTournamentStepWatched: 'currentTournamentStepWatched',
  globalTournamentWatchedDate: 'globalTournamentWatchedDate',
  globalTournamentRoundWatched: 'globalTournamentRoundWatched',
  eventTournamentWatchedDate: 'eventTournamentWatchedDate',
  eventTournamentRoundWatched: 'eventTournamentRoundWatched',
  lastFight: 'lastFight',
  fightsLeft: 'fightsLeft',
  victories: 'victories',
  losses: 'losses',
  opponentsGeneratedAt: 'opponentsGeneratedAt',
  canRankUpSince: 'canRankUpSince',
  favorite: 'favorite',
  wantToJoinClanId: 'wantToJoinClanId',
  tournamentWins: 'tournamentWins',
  eventId: 'eventId',
  resets: 'resets'
} as const

export type BruteScalarFieldEnum = (typeof BruteScalarFieldEnum)[keyof typeof BruteScalarFieldEnum]


export const BruteStartingStatsScalarFieldEnum = {
  id: 'id',
  endurance: 'endurance',
  strength: 'strength',
  agility: 'agility',
  speed: 'speed',
  bruteId: 'bruteId'
} as const

export type BruteStartingStatsScalarFieldEnum = (typeof BruteStartingStatsScalarFieldEnum)[keyof typeof BruteStartingStatsScalarFieldEnum]


export const FightScalarFieldEnum = {
  id: 'id',
  date: 'date',
  brute1Id: 'brute1Id',
  brute2Id: 'brute2Id',
  winnerId: 'winnerId',
  loserId: 'loserId',
  winner: 'winner',
  loser: 'loser',
  steps: 'steps',
  fighters: 'fighters',
  tournamentId: 'tournamentId',
  tournamentStep: 'tournamentStep',
  modifiers: 'modifiers',
  background: 'background',
  clanWarId: 'clanWarId',
  favoriteCount: 'favoriteCount'
} as const

export type FightScalarFieldEnum = (typeof FightScalarFieldEnum)[keyof typeof FightScalarFieldEnum]


export const LogScalarFieldEnum = {
  id: 'id',
  date: 'date',
  currentBruteId: 'currentBruteId',
  type: 'type',
  level: 'level',
  brute: 'brute',
  fightId: 'fightId',
  xp: 'xp',
  gold: 'gold',
  template: 'template',
  destinyChoiceId: 'destinyChoiceId'
} as const

export type LogScalarFieldEnum = (typeof LogScalarFieldEnum)[keyof typeof LogScalarFieldEnum]


export const DestinyChoiceScalarFieldEnum = {
  id: 'id',
  bruteId: 'bruteId',
  path: 'path',
  type: 'type',
  skill: 'skill',
  weapon: 'weapon',
  pet: 'pet',
  originalSkill: 'originalSkill',
  originalWeapon: 'originalWeapon',
  originalPet: 'originalPet',
  stat1: 'stat1',
  stat1Value: 'stat1Value',
  stat2: 'stat2',
  stat2Value: 'stat2Value'
} as const

export type DestinyChoiceScalarFieldEnum = (typeof DestinyChoiceScalarFieldEnum)[keyof typeof DestinyChoiceScalarFieldEnum]


export const TournamentScalarFieldEnum = {
  id: 'id',
  date: 'date',
  type: 'type',
  rounds: 'rounds',
  eventId: 'eventId'
} as const

export type TournamentScalarFieldEnum = (typeof TournamentScalarFieldEnum)[keyof typeof TournamentScalarFieldEnum]


export const TournamentAchievementScalarFieldEnum = {
  id: 'id',
  bruteId: 'bruteId',
  date: 'date',
  achievement: 'achievement',
  achievementCount: 'achievementCount'
} as const

export type TournamentAchievementScalarFieldEnum = (typeof TournamentAchievementScalarFieldEnum)[keyof typeof TournamentAchievementScalarFieldEnum]


export const TournamentGoldScalarFieldEnum = {
  id: 'id',
  date: 'date',
  userId: 'userId',
  gold: 'gold'
} as const

export type TournamentGoldScalarFieldEnum = (typeof TournamentGoldScalarFieldEnum)[keyof typeof TournamentGoldScalarFieldEnum]


export const TournamentXpScalarFieldEnum = {
  id: 'id',
  date: 'date',
  bruteId: 'bruteId',
  xp: 'xp'
} as const

export type TournamentXpScalarFieldEnum = (typeof TournamentXpScalarFieldEnum)[keyof typeof TournamentXpScalarFieldEnum]


export const AchievementScalarFieldEnum = {
  id: 'id',
  name: 'name',
  count: 'count',
  bruteId: 'bruteId',
  userId: 'userId'
} as const

export type AchievementScalarFieldEnum = (typeof AchievementScalarFieldEnum)[keyof typeof AchievementScalarFieldEnum]


export const BruteReportScalarFieldEnum = {
  id: 'id',
  bruteId: 'bruteId',
  bruteName: 'bruteName',
  reason: 'reason',
  count: 'count',
  date: 'date',
  status: 'status',
  handlerId: 'handlerId',
  handledAt: 'handledAt'
} as const

export type BruteReportScalarFieldEnum = (typeof BruteReportScalarFieldEnum)[keyof typeof BruteReportScalarFieldEnum]


export const ServerStateScalarFieldEnum = {
  id: 'id',
  globalTournamentValid: 'globalTournamentValid',
  activeModifiers: 'activeModifiers',
  modifiersEndAt: 'modifiersEndAt',
  nextModifiers: 'nextModifiers'
} as const

export type ServerStateScalarFieldEnum = (typeof ServerStateScalarFieldEnum)[keyof typeof ServerStateScalarFieldEnum]


export const BannedWordScalarFieldEnum = {
  id: 'id',
  word: 'word'
} as const

export type BannedWordScalarFieldEnum = (typeof BannedWordScalarFieldEnum)[keyof typeof BannedWordScalarFieldEnum]


export const BannedIpScalarFieldEnum = {
  id: 'id'
} as const

export type BannedIpScalarFieldEnum = (typeof BannedIpScalarFieldEnum)[keyof typeof BannedIpScalarFieldEnum]


export const BannedFingerprintScalarFieldEnum = {
  id: 'id'
} as const

export type BannedFingerprintScalarFieldEnum = (typeof BannedFingerprintScalarFieldEnum)[keyof typeof BannedFingerprintScalarFieldEnum]


export const KnownFingerprintScalarFieldEnum = {
  id: 'id',
  description: 'description',
  createdAt: 'createdAt'
} as const

export type KnownFingerprintScalarFieldEnum = (typeof KnownFingerprintScalarFieldEnum)[keyof typeof KnownFingerprintScalarFieldEnum]


export const ClanScalarFieldEnum = {
  id: 'id',
  name: 'name',
  deletedAt: 'deletedAt',
  limit: 'limit',
  points: 'points',
  elo: 'elo',
  boss: 'boss',
  damageOnBoss: 'damageOnBoss',
  masterId: 'masterId',
  participateInClanWar: 'participateInClanWar'
} as const

export type ClanScalarFieldEnum = (typeof ClanScalarFieldEnum)[keyof typeof ClanScalarFieldEnum]


export const ClanThreadScalarFieldEnum = {
  id: 'id',
  clanId: 'clanId',
  creatorId: 'creatorId',
  title: 'title',
  locked: 'locked',
  pinned: 'pinned',
  postCount: 'postCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClanThreadScalarFieldEnum = (typeof ClanThreadScalarFieldEnum)[keyof typeof ClanThreadScalarFieldEnum]


export const ClanPostScalarFieldEnum = {
  id: 'id',
  threadId: 'threadId',
  authorId: 'authorId',
  date: 'date',
  message: 'message'
} as const

export type ClanPostScalarFieldEnum = (typeof ClanPostScalarFieldEnum)[keyof typeof ClanPostScalarFieldEnum]


export const BossDamageScalarFieldEnum = {
  id: 'id',
  bruteId: 'bruteId',
  clanId: 'clanId',
  damage: 'damage'
} as const

export type BossDamageScalarFieldEnum = (typeof BossDamageScalarFieldEnum)[keyof typeof BossDamageScalarFieldEnum]


export const ClanWarScalarFieldEnum = {
  id: 'id',
  duration: 'duration',
  type: 'type',
  date: 'date',
  status: 'status',
  attackerId: 'attackerId',
  attackerEloChange: 'attackerEloChange',
  attackerWins: 'attackerWins',
  defenderId: 'defenderId',
  defenderEloChange: 'defenderEloChange',
  defenderWins: 'defenderWins',
  winnerId: 'winnerId'
} as const

export type ClanWarScalarFieldEnum = (typeof ClanWarScalarFieldEnum)[keyof typeof ClanWarScalarFieldEnum]


export const ClanWarFightersScalarFieldEnum = {
  id: 'id',
  clanWarId: 'clanWarId',
  day: 'day'
} as const

export type ClanWarFightersScalarFieldEnum = (typeof ClanWarFightersScalarFieldEnum)[keyof typeof ClanWarFightersScalarFieldEnum]


export const InventoryItemScalarFieldEnum = {
  id: 'id',
  type: 'type',
  count: 'count',
  bruteId: 'bruteId',
  userId: 'userId'
} as const

export type InventoryItemScalarFieldEnum = (typeof InventoryItemScalarFieldEnum)[keyof typeof InventoryItemScalarFieldEnum]


export const ReleaseScalarFieldEnum = {
  version: 'version',
  date: 'date'
} as const

export type ReleaseScalarFieldEnum = (typeof ReleaseScalarFieldEnum)[keyof typeof ReleaseScalarFieldEnum]


export const EventScalarFieldEnum = {
  id: 'id',
  date: 'date',
  type: 'type',
  maxLevel: 'maxLevel',
  maxRound: 'maxRound',
  status: 'status',
  winnerId: 'winnerId',
  finishedAt: 'finishedAt',
  sortedBrutes: 'sortedBrutes'
} as const

export type EventScalarFieldEnum = (typeof EventScalarFieldEnum)[keyof typeof EventScalarFieldEnum]


export const NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  message: 'message',
  severity: 'severity',
  link: 'link',
  read: 'read',
  date: 'date'
} as const

export type NotificationScalarFieldEnum = (typeof NotificationScalarFieldEnum)[keyof typeof NotificationScalarFieldEnum]


export const ConfigScalarFieldEnum = {
  key: 'key',
  value: 'value',
  updatedAt: 'updatedAt'
} as const

export type ConfigScalarFieldEnum = (typeof ConfigScalarFieldEnum)[keyof typeof ConfigScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

