import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

const COMMIT_HASH = 'f9b5add9d29a456c0d1ab234d382e140c7734385';
const OLD_TRANSLATIONS_PATH = 'client/src/assets/i18n';
const NEW_TRANSLATIONS_PATH = 'client/src/i18n/locales';

const LANGUAGES = ['de', 'en', 'es', 'fr', 'it', 'ko', 'pt', 'ru'];

interface Translations {
  [key: string]: string | Translations;
}

/**
 * Comprehensive mapping from old structure to new split files
 * Generated by buildKeyMapping.ts
 */

// Mapping from old prefixes to new file names
const PREFIX_TO_FILE: Record<string, string> = {
  'achievementRankings': 'achievementRanking',
  'achievements': 'achievement',
  'ascendWith': 'ascend',
  'banReason': 'user',
  'breakRoom': 'clan',
  'clanWar': 'clan',
  'clansRanking': 'clan',
  'deletionReason': 'common',
  'nextFighters': 'clan',
  'perkType': 'ascend',
  'tournamentHistory': 'tournamentHistory',
  'tournamentOf': 'tournament',
  'userProfile': 'user',
};

// Mapping from root-level keys to file names
const ROOT_KEY_TO_FILE: Record<string, string> = {
  'accept': 'common', 'accepted': 'admin', 'acceptJoinRequest': 'clan', 'account': 'common',
  'accountDeleted': 'user', 'accuracy': 'common', 'achievement': 'common', 'achievementRankings': 'achievementRanking',
  'achievements': 'common', 'actions': 'clan', 'activeModifiers': 'common', 'adminPanel': 'admin',
  'afterBlock': 'common', 'againstThrows': 'common', 'Agi': 'common', 'agility': 'common',
  'allRead': 'common', 'alreadyRegistered': 'common', 'arena': 'common', 'armor': 'common',
  'arrow': 'common', 'ascend': 'achievement', 'ascendConfirm': 'ascend', 'ascendConfirmShort': 'ascend',
  'ascension': 'ascend', 'ascensionExplanationText': 'ascend', 'ascensions': 'common', 'askToJoin': 'clan',
  'atOneHp': 'common', 'attacker': 'clan', 'attackers': 'common', 'authing': 'common',
  'automaticallyQualified': 'common', 'axe': 'common', 'background': 'common', 'backToCell': 'common',
  'backup': 'common', 'balletShoes': 'common', 'ban': 'user', 'banConfirm': 'user',
  'banSuccess': 'user', 'bareHands': 'common', 'baton': 'common', 'bear': 'achievement',
  'betaDescription': 'common', 'betaReset': 'common', 'betaTitle': 'common', 'block': 'common',
  'blunt': 'common', 'bodybuilder': 'common', 'bomb': 'common', 'boss': 'clan',
  'breakRoom': 'clan', 'broadsword': 'common', 'brute': 'common', 'bruteCell': 'common',
  'bruteIsPreparing': 'common', 'bruteIsResting': 'common', 'bruteNotRegistered': 'common', 'bruteRegistered': 'common',
  'bruteRemoved': 'clan', 'brutes': 'common', 'bruteSetForDeletion': 'common', 'bruteTransfer': 'transferBrute',
  'bruteTransferred': 'transferBrute', 'bumps': 'common', 'byUser': 'achievementRanking', 'callToFight': 'common',
  'cancel': 'common', 'cancelJoinRequest': 'clan', 'chaining': 'common', 'challengeBoss': 'clan',
  'changeAppearance': 'common', 'changeColors': 'common', 'character': 'common', 'chef': 'common',
  'choiceBackground': 'common', 'chooseAsFavorite': 'hall', 'chooseClanName': 'clan', 'chooseName': 'common',
  'chooseOneOfTheFollowingBonuses': 'levelUp', 'clan': 'common', 'clanCreated': 'clan', 'clanLeft': 'clan',
  'clanMaster': 'clan', 'clanMasterChanged': 'clan', 'clanNameLength': 'clan', 'clansRanking': 'clan',
  'clanWar': 'clan', 'clanWarHistory': 'clan', 'clanWarsEnabled': 'clan', 'combo': 'common',
  'comeBackInOneHour': 'common', 'common': 'common', 'confirmAcceptRequest': 'clan', 'confirmBruteTransfer': 'transferBrute',
  'confirmCancelRequest': 'clan', 'confirmFriendlyWar': 'clan', 'confirmJoin': 'clan', 'confirmLeaveClan': 'clan',
  'confirmLockThread': 'clan', 'confirmRejectRequest': 'clan', 'confirmRemoveFromClan': 'clan', 'confirmSetNewMaster': 'clan',
  'connect': 'common', 'continue': 'common', 'copyUserId': 'common', 'counter': 'common',
  'counterAttack': 'common', 'create': 'clan', 'createABrute': 'event', 'createAClan': 'clan',
  'createBrute': 'common', 'created': 'common', 'creator': 'clan', 'criticalChance': 'common',
  'criticalDamage': 'common', 'cryOfTheDamned': 'common', 'currentEvents': 'event', 'dailyTournament': 'common',
  'damage': 'common', 'dareChallenge': 'versus', 'darkMode': 'common', 'date': 'common',
  'day': 'common', 'dayOver': 'event', 'de-version': 'common', 'default': 'common',
  'defender': 'clan', 'defenders': 'common', 'deflect': 'common', 'deleteAccount': 'user',
  'deleteAccountConfirm': 'user', 'deleted': 'clan', 'deleteThread': 'clan', 'destinyOf': 'common',
  'determination': 'common', 'dexterity': 'common', 'dinorpg': 'common', 'dinoRpgRewardsSuccess': 'user',
  'directquiz': 'common', 'disableBackgroundMusic': 'common', 'disableSound': 'common', 'disarm': 'common',
  'discord': 'common', 'displayOpponentDetails': 'common', 'displayVersusPage': 'common', 'dog1': 'common',
  'dog2': 'common', 'dog3': 'common', 'drawChance': 'common', 'editThread': 'clan',
  'eliminatedBy': 'common', 'elo': 'clan', 'eMush': 'common', 'en-version': 'common',
  'enableBackgroundMusic': 'common', 'enableSound': 'common', 'endurance': 'common', 'enter!': 'common',
  'epic': 'common', 'ePopotamo': 'common', 'es-version': 'common', 'eternalfest': 'common',
  'eternalKingdom': 'common', 'evasion': 'common', 'event': 'common', 'eventBrute': 'common',
  'eventHistory': 'common', 'events': 'common', 'experience': 'ranking', 'externalRewards': 'user',
  'fan': 'common', 'fast': 'common', 'fasterFights': 'common', 'fastMetabolism': 'common',
  'favoriteFights': 'user', 'features': 'patchNotes', 'feed': 'common', 'felineAgility': 'achievement',
  'fierceBrute': 'common', 'fight': 'common', 'fightLeft': 'common', 'fights': 'common',
  'fightsLeft': 'common', 'finals': 'tournament', 'fingerprintError': 'common', 'fingerprintLoading': 'common',
  'first': 'clan', 'firstStrike': 'common', 'fistsOfFury': 'common', 'fixes': 'patchNotes',
  'flail': 'common', 'flashFlood': 'common', 'follow': 'common', 'followed': 'common',
  'followingFeed': 'followingFeed', 'forum': 'clan', 'fr-version': 'common', 'friendlyWarDeclared': 'clan',
  'fryingPan': 'common', 'generatingTournaments': 'generating', 'globalTournament': 'common', 'globalTournamentOf': 'common',
  'go': 'common', 'goBackToYourCell': 'clan', 'gold': 'common', 'goldNeededForNewBrute': 'common',
  'halbard': 'common', 'hall': 'hall', 'hammer': 'common', 'handledBy': 'admin',
  'haste': 'common', 'hatchet': 'common', 'healthPoints': 'common', 'heavy': 'common',
  'herculeanStrength': 'achievement', 'hideaway': 'common', 'hideDamage': 'clan', 'hitSpeed': 'common',
  'home': 'common', 'hostility': 'common', 'HP': 'common', 'hpMalus': 'common',
  'hypnosis': 'common', 'immortality': 'common', 'in': 'common', 'initiative': 'common',
  'invalidName': 'common', 'inventory': 'common', 'ironHead': 'common', 'joinAClan': 'common',
  'joinRequests': 'clan', 'keyboard': 'common', 'knife': 'common', 'lance': 'common',
  'last': 'clan', 'lastReply': 'clan', 'lastSeen': 'common', 'leadSkeleton': 'common',
  'leave': 'clan', 'leaveClan': 'clan', 'leek': 'common', 'legendary': 'common',
  'level': 'common', 'levelLower': 'levelUp', 'levelUp': 'common', 'lightMode': 'common',
  'lightningBolt': 'achievement', 'lockBruteAppearance': 'common', 'locked': 'clan', 'lockThread': 'clan',
  'login': 'common', 'loginError': 'home', 'loginSuccess': 'home', 'logout': 'common',
  'logoutSuccess': 'common', 'long': 'common', 'lvl_0': 'common', 'lvl_1': 'common',
  'lvl_10': 'common', 'lvl_11': 'common', 'lvl_2': 'common', 'lvl_3': 'common',
  'lvl_4': 'common', 'lvl_5': 'common', 'lvl_6': 'common', 'lvl_7': 'common',
  'lvl_8': 'common', 'lvl_9': 'common', 'mammothBone': 'common', 'martialArts': 'common',
  'master': 'common', 'maxLevel': 'achievement', 'maxPerBrute': 'common', 'maxPerFight': 'common',
  'maxTierReached': 'levelUp', 'members': 'clan', 'missingContent': 'clan', 'missingTitle': 'clan',
  'moderation': 'common', 'monk': 'common', 'moreGames': 'common', 'morningStar': 'common',
  'msg': 'clan', 'mug': 'common', 'multiplier': 'common', 'MyBrute': 'common',
  'MyBruteIllustration': 'common', 'myClan': 'clan', 'myHordes': 'common', 'nameChangeConfirm': 'common',
  'nameUnavailable': 'home', 'neoparc': 'common', 'net': 'common', 'newBrute': 'common',
  'newFightsTomorrow': 'common', 'newLevelFor': 'levelUp', 'newPatchNotesAvailable': 'common', 'newPet': 'common',
  'newSkill': 'common', 'newWeapon': 'common', 'next': 'common', 'nextBrute': 'cell',
  'nextFighters': 'clan', 'nextOpponent': 'common', 'noEvent': 'event', 'noFightsLeft': 'clan',
  'none': 'common', 'noNotifications': 'common', 'noodleBowl': 'common', 'notifications': 'common',
  'odds': 'common', 'opponent-damage': 'common', 'orNotToBe': 'common', 'otherGames': 'common',
  'outdatedVersion': 'common', 'panther': 'achievement', 'participants': 'event', 'patchNotes': 'common',
  'pending': 'admin', 'petUpgrade': 'levelUp', 'pinned': 'clan', 'pinThread': 'clan',
  'piopio': 'common', 'pleaseLogin': 'home', 'pleaseWait': 'generating', 'points': 'clan',
  'previous': 'common', 'previousBrute': 'cell', 'profile': 'common', 'pt-version': 'common',
  'pupils': 'common', 'quarterFinals': 'tournament', 'racquet': 'common', 'ranking': 'common',
  'rankingPrioritizeAscensions': 'ascend', 'rankings': 'ranking', 'rankingUpdatedDaily': 'common', 'rankUp': 'common',
  'rankUpConfirm': 'common', 'rare': 'common', 'reach': 'common', 'reached': 'levelUp',
  'reconnaissance': 'common', 'refLink': 'cell', 'regeneration': 'common', 'regenerationStat': 'common',
  'reject': 'common', 'rejected': 'admin', 'rejectJoinRequest': 'clan', 'relentless': 'common',
  'removeFromClan': 'clan', 'removeFromFavorites': 'hall', 'reply': 'clan', 'replyPosted': 'clan',
  'report': 'cell', 'reportAccepted': 'admin', 'reportCancelled': 'admin', 'reportConfirm': 'cell',
  'reportedBy': 'admin', 'reportName': 'cell', 'reportRejected': 'admin', 'reportSuccess': 'cell',
  'repulse': 'common', 'requestAccepted': 'clan', 'requestCanceled': 'clan', 'requestRejected': 'clan',
  'requestSent': 'clan', 'reset': 'cell', 'resetConfirm': 'cell', 'resetEventConfirm': 'cell',
  'resetSuccess': 'cell', 'resetVisuals': 'resetVisuals', 'resetVisualsConfirm': 'resetVisuals', 'resetVisualsDescription': 'resetVisuals',
  'resetVisualsSuccess': 'resetVisuals', 'resistant': 'common', 'result': 'tournamentHistory', 'reversal': 'common',
  'round': 'tournament', 'ru-version': 'common', 'sabotage': 'common', 'sabotageStat': 'common',
  'saboteur': 'common', 'sacrifice': 'cell', 'sacrificeConfirm': 'cell', 'sacrificeSuccess': 'cell',
  'sai': 'common', 'scimitar': 'common', 'searchBrute': 'common', 'searchByName': 'clan',
  'searchForParticipant': 'event', 'seeParticipants': 'event', 'semiFinals': 'tournament', 'send': 'clan',
  'serverTime': 'common', 'setAsClanMaster': 'clan', 'setAsWatched': 'common', 'setNewMaster': 'clan',
  'settings': 'common', 'shadow': 'common', 'sharp': 'common', 'shield': 'common',
  'shock': 'common', 'showDamage': 'clan', 'showMore': 'common', 'shuriken': 'common',
  'sixthSense': 'common', 'skillUpgrade': 'levelUp', 'skills': 'common', 'Spe': 'common',
  'speed': 'common', 'spy': 'common', 'startFight': 'versus', 'startThread': 'clan',
  'startWithWeapon': 'common', 'stat': 'common', 'status': 'admin', 'Str': 'common',
  'strength': 'common', 'supers': 'common', 'survival': 'common', 'sword': 'common',
  'taggedForDeletion': 'common', 'tamer': 'common', 'thief': 'common', 'thrown': 'common',
  'title': 'clan', 'titles': 'hall', 'toBeABrute': 'common', 'toggleWar': 'clan',
  'total': 'common', 'toughenedSkin': 'common', 'tournament': 'common', 'tournamentHistory': 'tournamentHistory',
  'tournamentOf': 'tournament', 'tournamentVictoriesUntilAscend': 'common', 'tournamentVictoriesUntilRankUp': 'common', 'tournaments': 'common',
  'tragicPotion': 'common', 'transferBrute': 'transferBrute', 'treat': 'common', 'trident': 'common',
  'trombone': 'common', 'types': 'common', 'unban': 'user', 'unbanConfirm': 'user',
  'unbanSuccess': 'user', 'uncommon': 'common', 'unfollow': 'common', 'unfollowed': 'common',
  'unlimited': 'common', 'unlockBruteAppearance': 'common', 'unpinThread': 'clan', 'untouchable': 'common',
  'usageRate': 'common', 'userIdCopied': 'common', 'userProfile': 'user', 'validate': 'common',
  'value': 'common', 'vampirism': 'common', 'victories': 'common', 'vitality': 'achievement',
  'vs': 'user', 'W/L': 'clan', 'warAccepted': 'clan', 'warCanceled': 'clan',
  'weapons': 'common', 'weaponsBonuses': 'cell', 'weaponsMaster': 'common', 'weaponUpgrade': 'levelUp',
  'whip': 'common', 'wiki': 'common', 'winrate': 'common', 'wins-losses': 'common',
  'youAreAboutToAscend': 'ascend', 'youCanRegisterYourBrute': 'common', 'youHaveOneFightLeft': 'common', 'youHaveXFightsLeft': 'common',
  'youMustSelectToAscend': 'ascend', 'youWillAscendWith': 'ascend', 'youWillAscendWithDog': 'ascend',
};

/**
 * Map old key to new key structure using the comprehensive mapping
 */
function mapOldKeyToNew(oldKey: string): string {
  // Check if key has a prefix (contains a dot)
  if (!oldKey.includes('.')) {
    // Root-level key - use mapping or default to common
    const targetFile = ROOT_KEY_TO_FILE[oldKey] || 'common';
    return `${targetFile}.${oldKey}`;
  }

  // Split on first dot
  const dotIndex = oldKey.indexOf('.');
  const prefix = oldKey.substring(0, dotIndex);
  const rest = oldKey.substring(dotIndex + 1);

  // Use prefix mapping or keep original
  const targetFile = PREFIX_TO_FILE[prefix] || prefix;

  return `${targetFile}.${rest}`;
}

/**
 * Fetch old translation file from git commit
 */
function fetchOldTranslations(lang: string): Translations {
  try {
    const command = `git show ${COMMIT_HASH}:${OLD_TRANSLATIONS_PATH}/${lang}.json`;
    const content = execSync(command, { encoding: 'utf-8' });
    return JSON.parse(content);
  } catch (error) {
    console.error(`Failed to fetch old translations for ${lang}:`, error);
    return {};
  }
}

/**
 * Read all current split translation files for a language
 */
function readCurrentTranslations(lang: string): Map<string, { file: string; content: Translations }> {
  const langPath = path.join(process.cwd(), NEW_TRANSLATIONS_PATH, lang);
  const files = fs.readdirSync(langPath).filter(f => f.endsWith('.json'));

  const result = new Map<string, { file: string; content: Translations }>();

  for (const file of files) {
    const filePath = path.join(langPath, file);
    const content = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    result.set(file, { file: filePath, content });
  }

  return result;
}

/**
 * Flatten nested object with dot notation
 */
function flattenObject(obj: Translations, prefix = ''): Map<string, string> {
  const result = new Map<string, string>();

  for (const [key, value] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${key}` : key;

    if (typeof value === 'string') {
      result.set(fullKey, value);
    } else if (typeof value === 'object' && value !== null) {
      const nested = flattenObject(value, fullKey);
      for (const [nestedKey, nestedValue] of nested.entries()) {
        result.set(nestedKey, nestedValue);
      }
    }
  }

  return result;
}

/**
 * Set value in nested object using dot notation path
 */
function setNestedValue(obj: Translations, path: string, value: string): void {
  const keys = path.split('.');
  let current: any = obj;

  for (let i = 0; i < keys.length - 1; i++) {
    if (!(keys[i] in current)) {
      current[keys[i]] = {};
    }
    current = current[keys[i]];
  }

  current[keys[keys.length - 1]] = value;
}

/**
 * Restore old translations for a specific language
 */
function restoreTranslations(lang: string): void {
  console.log(`\n Processing ${lang.toUpperCase()}...`);

  // Fetch old translations
  const oldTranslations = fetchOldTranslations(lang);
  const oldFlat = flattenObject(oldTranslations);

  if (oldFlat.size === 0) {
    console.log(`  ⚠️  No old translations found for ${lang}`);
    return;
  }

  console.log(`  📖 Found ${oldFlat.size} old translation keys`);

  // Read current split translations
  const currentFiles = readCurrentTranslations(lang);
  console.log(`  📁 Found ${currentFiles.size} current translation files`);

  // Flatten current translations
  const currentFlat = new Map<string, string>();
  for (const [fileName, { content }] of currentFiles.entries()) {
    const fileKey = fileName.replace('.json', '');
    const flattened = flattenObject(content, fileKey);
    for (const [key, value] of flattened.entries()) {
      currentFlat.set(key, value);
    }
  }

  console.log(`  🔍 Found ${currentFlat.size} current translation keys`);

  // Compare and track changes
  const changes = new Map<string, { old: string; new: string; mappedKey: string }>();

  for (const [oldKey, oldValue] of oldFlat.entries()) {
    // Map the old key to the new structure
    const mappedKey = mapOldKeyToNew(oldKey);

    const currentValue = currentFlat.get(mappedKey);

    if (currentValue !== undefined && currentValue !== oldValue) {
      changes.set(oldKey, { old: oldValue, new: currentValue, mappedKey });
    }
  }

  console.log(`  🔄 Found ${changes.size} translations to revert`);

  if (changes.size === 0) {
    console.log(`  ✅ No changes needed for ${lang}`);
    return;
  }

  // Restore old values in split files
  const updatedFiles = new Map<string, Translations>();

  for (const [fileName, { content }] of currentFiles.entries()) {
    updatedFiles.set(fileName, JSON.parse(JSON.stringify(content))); // Deep clone
  }

  for (const [oldKey, { old, mappedKey }] of changes.entries()) {
    // Use the mapped key to determine which file this belongs to
    const parts = mappedKey.split('.');
    const fileName = `${parts[0]}.json`;
    const pathWithinFile = parts.slice(1).join('.');

    if (updatedFiles.has(fileName)) {
      const fileContent = updatedFiles.get(fileName)!;
      setNestedValue(fileContent, pathWithinFile, old);
    }
  }

  // Write updated files
  let filesWritten = 0;
  for (const [fileName, { file }] of currentFiles.entries()) {
    const updatedContent = updatedFiles.get(fileName);
    if (updatedContent) {
      fs.writeFileSync(file, JSON.stringify(updatedContent, null, 2) + '\n', 'utf-8');
      filesWritten++;
    }
  }

  console.log(`  ✅ Updated ${filesWritten} files for ${lang}`);

  // Show some examples of changes
  if (changes.size > 0) {
    console.log(`  📝 Example changes:`);
    let count = 0;
    for (const [key, { old, new: newVal, mappedKey }] of changes.entries()) {
      if (count++ >= 3) break;
      console.log(`     ${key} (-> ${mappedKey}):`);
      console.log(`       Old: "${old}"`);
      console.log(`       New: "${newVal}"`);
    }
    if (changes.size > 3) {
      console.log(`     ... and ${changes.size - 3} more`);
    }
  }
}

/**
 * Main function
 */
function main(): void {
  console.log('🚀 Starting translation restoration...');
  console.log(`📍 Commit: ${COMMIT_HASH}`);
  console.log(`🌍 Languages: ${LANGUAGES.join(', ')}`);

  for (const lang of LANGUAGES) {
    try {
      restoreTranslations(lang);
    } catch (error) {
      console.error(`❌ Error processing ${lang}:`, error);
    }
  }

  console.log('\n✨ Translation restoration complete!');
}

main();
