const skills = [
  { name: 'herculeanStrength' as const, icon: '1' },
  { name: 'felinAgility' as const, icon: '2' },
  { name: 'lightningBolt' as const, icon: '3' },
  { name: 'vitality' as const, icon: '4' },
  { name: 'immortality' as const, icon: '5' },
  { name: 'weaponsMaster' as const, icon: '6' },
  { name: 'martialArts' as const, icon: '7' },
  { name: 'sixthSense' as const, icon: '8' },
  { name: 'hostility' as const, icon: '9' },
  { name: 'fistsOfFury' as const, icon: '10' },
  { name: 'shield' as const, icon: '11' },
  { name: 'armor' as const, icon: '12' },
  { name: 'toughenedSkin' as const, icon: '13' },
  { name: 'untouchable' as const, icon: '14' },
  { name: 'sabotage' as const, icon: '15' },
  { name: 'shock' as const, icon: '16' },
  { name: 'bodybuilder' as const, icon: '17' },
  { name: 'relentless' as const, icon: '18' },
  { name: 'survival' as const, icon: '19' },
  { name: 'thief' as const, icon: '28' },
  { name: 'fierceBrute' as const, icon: '29' },
  { name: 'tragicPotion' as const, icon: '30' },
  { name: 'net' as const, icon: '31' },
  { name: 'bomb' as const, icon: '32' },
  { name: 'hammer' as const, icon: '33' },
  { name: 'cryOfTheDamned' as const, icon: '34' },
  { name: 'hypnosis' as const, icon: '35' },
  { name: 'flashFlood' as const, icon: '36' },
];

export default skills;